namespace Empresa_laboral_ADNE___Proyecto_PTC.Vista
{
    partial class ConfiguraciónDeUsuarioForm
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(ConfiguraciónDeUsuarioForm));
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties13 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties14 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties15 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties16 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties17 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties18 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties19 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties20 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties21 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties22 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties23 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties24 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            this.bunifuGradientPanel3 = new Bunifu.UI.WinForms.BunifuGradientPanel();
            this.bunifuGradientPanel1 = new Bunifu.UI.WinForms.BunifuGradientPanel();
            this.bunifuShadowPanel2 = new Bunifu.UI.WinForms.BunifuShadowPanel();
            this.txtCorreo = new Bunifu.UI.WinForms.BunifuTextBox();
            this.lblCorreo = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuPanel3 = new Bunifu.UI.WinForms.BunifuPanel();
            this.btnGuardar = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.bunifuPanel1 = new Bunifu.UI.WinForms.BunifuPanel();
            this.bunifuPanel2 = new Bunifu.UI.WinForms.BunifuPanel();
            this.btnEliminar = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.bunifuPanel4 = new Bunifu.UI.WinForms.BunifuPanel();
            this.btnCargarImagen = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.picProfesional = new Bunifu.UI.WinForms.BunifuPictureBox();
            this.bunifuShadowPanel7 = new Bunifu.UI.WinForms.BunifuShadowPanel();
            this.txtTelefono = new Bunifu.UI.WinForms.BunifuTextBox();
            this.lblTelefono = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuShadowPanel4 = new Bunifu.UI.WinForms.BunifuShadowPanel();
            this.txtUsuario = new Bunifu.UI.WinForms.BunifuTextBox();
            this.lblUsuario = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuShadowPanel5 = new Bunifu.UI.WinForms.BunifuShadowPanel();
            this.txtDui = new Bunifu.UI.WinForms.BunifuTextBox();
            this.lblDocumento = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuShadowPanel3 = new Bunifu.UI.WinForms.BunifuShadowPanel();
            this.txtApellido = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuShadowPanel1 = new Bunifu.UI.WinForms.BunifuShadowPanel();
            this.txtNombre = new Bunifu.UI.WinForms.BunifuTextBox();
            this.lblApellidos = new Bunifu.UI.WinForms.BunifuLabel();
            this.lblNombres = new Bunifu.UI.WinForms.BunifuLabel();
            this.Titulo_Registrar = new Bunifu.UI.WinForms.BunifuLabel();
            this.Notificacion1 = new Bunifu.UI.WinForms.BunifuSnackbar(this.components);
            this.ofdImagen = new System.Windows.Forms.OpenFileDialog();
            this.bunifuGradientPanel3.SuspendLayout();
            this.bunifuGradientPanel1.SuspendLayout();
            this.bunifuShadowPanel2.SuspendLayout();
            this.bunifuPanel3.SuspendLayout();
            this.bunifuPanel1.SuspendLayout();
            this.bunifuPanel2.SuspendLayout();
            this.bunifuPanel4.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.picProfesional)).BeginInit();
            this.bunifuShadowPanel7.SuspendLayout();
            this.bunifuShadowPanel4.SuspendLayout();
            this.bunifuShadowPanel5.SuspendLayout();
            this.bunifuShadowPanel3.SuspendLayout();
            this.bunifuShadowPanel1.SuspendLayout();
            this.SuspendLayout();
            // 
            // bunifuGradientPanel3
            // 
            this.bunifuGradientPanel3.BackColor = System.Drawing.Color.Transparent;
            this.bunifuGradientPanel3.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuGradientPanel3.BackgroundImage")));
            this.bunifuGradientPanel3.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.bunifuGradientPanel3.BorderRadius = 15;
            this.bunifuGradientPanel3.Controls.Add(this.bunifuGradientPanel1);
            this.bunifuGradientPanel3.Controls.Add(this.Titulo_Registrar);
            this.bunifuGradientPanel3.Dock = System.Windows.Forms.DockStyle.Fill;
            this.bunifuGradientPanel3.GradientBottomLeft = System.Drawing.Color.FromArgb(((int)(((byte)(53)))), ((int)(((byte)(163)))), ((int)(((byte)(170)))));
            this.bunifuGradientPanel3.GradientBottomRight = System.Drawing.Color.FromArgb(((int)(((byte)(54)))), ((int)(((byte)(181)))), ((int)(((byte)(166)))));
            this.bunifuGradientPanel3.GradientTopLeft = System.Drawing.Color.FromArgb(((int)(((byte)(54)))), ((int)(((byte)(164)))), ((int)(((byte)(171)))));
            this.bunifuGradientPanel3.GradientTopRight = System.Drawing.Color.FromArgb(((int)(((byte)(56)))), ((int)(((byte)(174)))), ((int)(((byte)(167)))));
            this.bunifuGradientPanel3.Location = new System.Drawing.Point(0, 0);
            this.bunifuGradientPanel3.Name = "bunifuGradientPanel3";
            this.bunifuGradientPanel3.Quality = 10;
            this.bunifuGradientPanel3.Size = new System.Drawing.Size(1264, 681);
            this.bunifuGradientPanel3.TabIndex = 2;
            // 
            // bunifuGradientPanel1
            // 
            this.bunifuGradientPanel1.BackColor = System.Drawing.Color.Transparent;
            this.bunifuGradientPanel1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuGradientPanel1.BackgroundImage")));
            this.bunifuGradientPanel1.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.bunifuGradientPanel1.BorderRadius = 15;
            this.bunifuGradientPanel1.Controls.Add(this.bunifuShadowPanel2);
            this.bunifuGradientPanel1.Controls.Add(this.lblCorreo);
            this.bunifuGradientPanel1.Controls.Add(this.bunifuPanel3);
            this.bunifuGradientPanel1.Controls.Add(this.bunifuPanel1);
            this.bunifuGradientPanel1.Controls.Add(this.bunifuShadowPanel7);
            this.bunifuGradientPanel1.Controls.Add(this.lblTelefono);
            this.bunifuGradientPanel1.Controls.Add(this.bunifuShadowPanel4);
            this.bunifuGradientPanel1.Controls.Add(this.lblUsuario);
            this.bunifuGradientPanel1.Controls.Add(this.bunifuShadowPanel5);
            this.bunifuGradientPanel1.Controls.Add(this.lblDocumento);
            this.bunifuGradientPanel1.Controls.Add(this.bunifuShadowPanel3);
            this.bunifuGradientPanel1.Controls.Add(this.bunifuShadowPanel1);
            this.bunifuGradientPanel1.Controls.Add(this.lblApellidos);
            this.bunifuGradientPanel1.Controls.Add(this.lblNombres);
            this.bunifuGradientPanel1.GradientBottomLeft = System.Drawing.Color.FromArgb(((int)(((byte)(222)))), ((int)(((byte)(243)))), ((int)(((byte)(242)))));
            this.bunifuGradientPanel1.GradientBottomRight = System.Drawing.Color.FromArgb(((int)(((byte)(187)))), ((int)(((byte)(251)))), ((int)(((byte)(244)))));
            this.bunifuGradientPanel1.GradientTopLeft = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(248)))), ((int)(((byte)(248)))));
            this.bunifuGradientPanel1.GradientTopRight = System.Drawing.Color.FromArgb(((int)(((byte)(216)))), ((int)(((byte)(243)))), ((int)(((byte)(241)))));
            this.bunifuGradientPanel1.Location = new System.Drawing.Point(51, 94);
            this.bunifuGradientPanel1.Name = "bunifuGradientPanel1";
            this.bunifuGradientPanel1.Quality = 10;
            this.bunifuGradientPanel1.Size = new System.Drawing.Size(1158, 554);
            this.bunifuGradientPanel1.TabIndex = 2;
            // 
            // bunifuShadowPanel2
            // 
            this.bunifuShadowPanel2.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.bunifuShadowPanel2.BackColor = System.Drawing.Color.Transparent;
            this.bunifuShadowPanel2.BorderColor = System.Drawing.Color.Transparent;
            this.bunifuShadowPanel2.BorderRadius = 12;
            this.bunifuShadowPanel2.BorderThickness = 1;
            this.bunifuShadowPanel2.Controls.Add(this.txtCorreo);
            this.bunifuShadowPanel2.FillStyle = Bunifu.UI.WinForms.BunifuShadowPanel.FillStyles.Solid;
            this.bunifuShadowPanel2.GradientMode = Bunifu.UI.WinForms.BunifuShadowPanel.GradientModes.Vertical;
            this.bunifuShadowPanel2.Location = new System.Drawing.Point(777, 188);
            this.bunifuShadowPanel2.Name = "bunifuShadowPanel2";
            this.bunifuShadowPanel2.PanelColor = System.Drawing.Color.Transparent;
            this.bunifuShadowPanel2.PanelColor2 = System.Drawing.Color.Transparent;
            this.bunifuShadowPanel2.ShadowColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.bunifuShadowPanel2.ShadowDept = 2;
            this.bunifuShadowPanel2.ShadowDepth = 5;
            this.bunifuShadowPanel2.ShadowStyle = Bunifu.UI.WinForms.BunifuShadowPanel.ShadowStyles.Surrounded;
            this.bunifuShadowPanel2.ShadowTopLeftVisible = false;
            this.bunifuShadowPanel2.Size = new System.Drawing.Size(300, 57);
            this.bunifuShadowPanel2.Style = Bunifu.UI.WinForms.BunifuShadowPanel.BevelStyles.Flat;
            this.bunifuShadowPanel2.TabIndex = 67;
            // 
            // txtCorreo
            // 
            this.txtCorreo.AcceptsReturn = false;
            this.txtCorreo.AcceptsTab = false;
            this.txtCorreo.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.txtCorreo.AnimationSpeed = 200;
            this.txtCorreo.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtCorreo.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtCorreo.AutoSizeHeight = true;
            this.txtCorreo.BackColor = System.Drawing.Color.Transparent;
            this.txtCorreo.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtCorreo.BackgroundImage")));
            this.txtCorreo.BorderColorActive = System.Drawing.Color.Teal;
            this.txtCorreo.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtCorreo.BorderColorHover = System.Drawing.Color.LightSeaGreen;
            this.txtCorreo.BorderColorIdle = System.Drawing.Color.Transparent;
            this.txtCorreo.BorderRadius = 12;
            this.txtCorreo.BorderThickness = 0;
            this.txtCorreo.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.txtCorreo.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtCorreo.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtCorreo.DefaultFont = new System.Drawing.Font("Century Gothic", 14.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtCorreo.DefaultText = "";
            this.txtCorreo.FillColor = System.Drawing.Color.White;
            this.txtCorreo.HideSelection = true;
            this.txtCorreo.IconLeft = null;
            this.txtCorreo.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtCorreo.IconPadding = 10;
            this.txtCorreo.IconRight = null;
            this.txtCorreo.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtCorreo.Lines = new string[0];
            this.txtCorreo.Location = new System.Drawing.Point(4, 1);
            this.txtCorreo.MaxLength = 30;
            this.txtCorreo.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtCorreo.Modified = false;
            this.txtCorreo.Multiline = false;
            this.txtCorreo.Name = "txtCorreo";
            stateProperties1.BorderColor = System.Drawing.Color.Teal;
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtCorreo.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtCorreo.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.LightSeaGreen;
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtCorreo.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.Transparent;
            stateProperties4.FillColor = System.Drawing.Color.White;
            stateProperties4.ForeColor = System.Drawing.Color.Empty;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtCorreo.OnIdleState = stateProperties4;
            this.txtCorreo.Padding = new System.Windows.Forms.Padding(3);
            this.txtCorreo.PasswordChar = '\0';
            this.txtCorreo.PlaceholderForeColor = System.Drawing.Color.Gray;
            this.txtCorreo.PlaceholderText = "Correo electrónico";
            this.txtCorreo.ReadOnly = false;
            this.txtCorreo.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtCorreo.SelectedText = "";
            this.txtCorreo.SelectionLength = 0;
            this.txtCorreo.SelectionStart = 0;
            this.txtCorreo.ShortcutsEnabled = false;
            this.txtCorreo.Size = new System.Drawing.Size(294, 50);
            this.txtCorreo.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtCorreo.TabIndex = 0;
            this.txtCorreo.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtCorreo.TextMarginBottom = 0;
            this.txtCorreo.TextMarginLeft = 3;
            this.txtCorreo.TextMarginTop = 1;
            this.txtCorreo.TextPlaceholder = "Correo electrónico";
            this.txtCorreo.UseSystemPasswordChar = false;
            this.txtCorreo.WordWrap = true;
            // 
            // lblCorreo
            // 
            this.lblCorreo.AllowParentOverrides = false;
            this.lblCorreo.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.lblCorreo.AutoEllipsis = false;
            this.lblCorreo.CursorType = null;
            this.lblCorreo.Font = new System.Drawing.Font("Century Gothic", 14.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblCorreo.Location = new System.Drawing.Point(782, 151);
            this.lblCorreo.Name = "lblCorreo";
            this.lblCorreo.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.lblCorreo.Size = new System.Drawing.Size(68, 23);
            this.lblCorreo.TabIndex = 68;
            this.lblCorreo.TabStop = false;
            this.lblCorreo.Text = "Correo:";
            this.lblCorreo.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.lblCorreo.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuPanel3
            // 
            this.bunifuPanel3.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.bunifuPanel3.BackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.bunifuPanel3.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuPanel3.BackgroundImage")));
            this.bunifuPanel3.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.bunifuPanel3.BorderColor = System.Drawing.Color.Transparent;
            this.bunifuPanel3.BorderRadius = 15;
            this.bunifuPanel3.BorderThickness = 0;
            this.bunifuPanel3.Controls.Add(this.btnGuardar);
            this.bunifuPanel3.Location = new System.Drawing.Point(857, 446);
            this.bunifuPanel3.Name = "bunifuPanel3";
            this.bunifuPanel3.ShowBorders = true;
            this.bunifuPanel3.Size = new System.Drawing.Size(247, 67);
            this.bunifuPanel3.TabIndex = 70;
            // 
            // btnGuardar
            // 
            this.btnGuardar.AllowAnimations = true;
            this.btnGuardar.AllowMouseEffects = true;
            this.btnGuardar.AllowToggling = false;
            this.btnGuardar.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.btnGuardar.AnimationSpeed = 200;
            this.btnGuardar.AutoGenerateColors = false;
            this.btnGuardar.AutoRoundBorders = false;
            this.btnGuardar.AutoSizeLeftIcon = true;
            this.btnGuardar.AutoSizeRightIcon = true;
            this.btnGuardar.BackColor = System.Drawing.Color.Transparent;
            this.btnGuardar.BackColor1 = System.Drawing.Color.DarkTurquoise;
            this.btnGuardar.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnGuardar.BackgroundImage")));
            this.btnGuardar.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnGuardar.ButtonText = "Guardar";
            this.btnGuardar.ButtonTextMarginLeft = 0;
            this.btnGuardar.ColorContrastOnClick = 45;
            this.btnGuardar.ColorContrastOnHover = 45;
            this.btnGuardar.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.btnGuardar.CustomizableEdges = borderEdges1;
            this.btnGuardar.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnGuardar.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnGuardar.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnGuardar.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnGuardar.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.btnGuardar.Font = new System.Drawing.Font("Century Gothic", 15F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnGuardar.ForeColor = System.Drawing.Color.White;
            this.btnGuardar.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnGuardar.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnGuardar.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnGuardar.IconMarginLeft = 11;
            this.btnGuardar.IconPadding = 10;
            this.btnGuardar.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnGuardar.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnGuardar.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnGuardar.IconSize = 25;
            this.btnGuardar.IdleBorderColor = System.Drawing.Color.DarkTurquoise;
            this.btnGuardar.IdleBorderRadius = 15;
            this.btnGuardar.IdleBorderThickness = 1;
            this.btnGuardar.IdleFillColor = System.Drawing.Color.DarkTurquoise;
            this.btnGuardar.IdleIconLeftImage = null;
            this.btnGuardar.IdleIconRightImage = null;
            this.btnGuardar.IndicateFocus = false;
            this.btnGuardar.Location = new System.Drawing.Point(0, 0);
            this.btnGuardar.Name = "btnGuardar";
            this.btnGuardar.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnGuardar.OnDisabledState.BorderRadius = 15;
            this.btnGuardar.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnGuardar.OnDisabledState.BorderThickness = 1;
            this.btnGuardar.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnGuardar.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnGuardar.OnDisabledState.IconLeftImage = null;
            this.btnGuardar.OnDisabledState.IconRightImage = null;
            this.btnGuardar.onHoverState.BorderColor = System.Drawing.Color.MediumTurquoise;
            this.btnGuardar.onHoverState.BorderRadius = 15;
            this.btnGuardar.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnGuardar.onHoverState.BorderThickness = 1;
            this.btnGuardar.onHoverState.FillColor = System.Drawing.Color.MediumTurquoise;
            this.btnGuardar.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnGuardar.onHoverState.IconLeftImage = null;
            this.btnGuardar.onHoverState.IconRightImage = null;
            this.btnGuardar.OnIdleState.BorderColor = System.Drawing.Color.DarkTurquoise;
            this.btnGuardar.OnIdleState.BorderRadius = 15;
            this.btnGuardar.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnGuardar.OnIdleState.BorderThickness = 1;
            this.btnGuardar.OnIdleState.FillColor = System.Drawing.Color.DarkTurquoise;
            this.btnGuardar.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnGuardar.OnIdleState.IconLeftImage = null;
            this.btnGuardar.OnIdleState.IconRightImage = null;
            this.btnGuardar.OnPressedState.BorderColor = System.Drawing.Color.LightSeaGreen;
            this.btnGuardar.OnPressedState.BorderRadius = 15;
            this.btnGuardar.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnGuardar.OnPressedState.BorderThickness = 1;
            this.btnGuardar.OnPressedState.FillColor = System.Drawing.Color.LightSeaGreen;
            this.btnGuardar.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnGuardar.OnPressedState.IconLeftImage = null;
            this.btnGuardar.OnPressedState.IconRightImage = null;
            this.btnGuardar.Size = new System.Drawing.Size(247, 64);
            this.btnGuardar.TabIndex = 0;
            this.btnGuardar.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnGuardar.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnGuardar.TextMarginLeft = 0;
            this.btnGuardar.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnGuardar.UseDefaultRadiusAndThickness = true;
            // 
            // bunifuPanel1
            // 
            this.bunifuPanel1.BackgroundColor = System.Drawing.Color.Transparent;
            this.bunifuPanel1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuPanel1.BackgroundImage")));
            this.bunifuPanel1.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.bunifuPanel1.BorderColor = System.Drawing.Color.LightGray;
            this.bunifuPanel1.BorderRadius = 5;
            this.bunifuPanel1.BorderThickness = 1;
            this.bunifuPanel1.Controls.Add(this.bunifuPanel2);
            this.bunifuPanel1.Controls.Add(this.bunifuPanel4);
            this.bunifuPanel1.Controls.Add(this.picProfesional);
            this.bunifuPanel1.Location = new System.Drawing.Point(66, 279);
            this.bunifuPanel1.Name = "bunifuPanel1";
            this.bunifuPanel1.ShowBorders = true;
            this.bunifuPanel1.Size = new System.Drawing.Size(651, 244);
            this.bunifuPanel1.TabIndex = 71;
            // 
            // bunifuPanel2
            // 
            this.bunifuPanel2.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.bunifuPanel2.BackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.bunifuPanel2.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuPanel2.BackgroundImage")));
            this.bunifuPanel2.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.bunifuPanel2.BorderColor = System.Drawing.Color.Transparent;
            this.bunifuPanel2.BorderRadius = 15;
            this.bunifuPanel2.BorderThickness = 0;
            this.bunifuPanel2.Controls.Add(this.btnEliminar);
            this.bunifuPanel2.Location = new System.Drawing.Point(358, 132);
            this.bunifuPanel2.Name = "bunifuPanel2";
            this.bunifuPanel2.ShowBorders = true;
            this.bunifuPanel2.Size = new System.Drawing.Size(254, 62);
            this.bunifuPanel2.TabIndex = 70;
            // 
            // btnEliminar
            // 
            this.btnEliminar.AllowAnimations = true;
            this.btnEliminar.AllowMouseEffects = true;
            this.btnEliminar.AllowToggling = false;
            this.btnEliminar.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.btnEliminar.AnimationSpeed = 200;
            this.btnEliminar.AutoGenerateColors = false;
            this.btnEliminar.AutoRoundBorders = false;
            this.btnEliminar.AutoSizeLeftIcon = true;
            this.btnEliminar.AutoSizeRightIcon = true;
            this.btnEliminar.BackColor = System.Drawing.Color.Transparent;
            this.btnEliminar.BackColor1 = System.Drawing.Color.DarkTurquoise;
            this.btnEliminar.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnEliminar.BackgroundImage")));
            this.btnEliminar.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnEliminar.ButtonText = "Eliminar";
            this.btnEliminar.ButtonTextMarginLeft = 0;
            this.btnEliminar.ColorContrastOnClick = 45;
            this.btnEliminar.ColorContrastOnHover = 45;
            this.btnEliminar.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.btnEliminar.CustomizableEdges = borderEdges2;
            this.btnEliminar.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnEliminar.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnEliminar.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnEliminar.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnEliminar.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.btnEliminar.Font = new System.Drawing.Font("Century Gothic", 15F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnEliminar.ForeColor = System.Drawing.Color.White;
            this.btnEliminar.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnEliminar.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnEliminar.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnEliminar.IconMarginLeft = 11;
            this.btnEliminar.IconPadding = 10;
            this.btnEliminar.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnEliminar.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnEliminar.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnEliminar.IconSize = 25;
            this.btnEliminar.IdleBorderColor = System.Drawing.Color.DarkTurquoise;
            this.btnEliminar.IdleBorderRadius = 15;
            this.btnEliminar.IdleBorderThickness = 1;
            this.btnEliminar.IdleFillColor = System.Drawing.Color.DarkTurquoise;
            this.btnEliminar.IdleIconLeftImage = null;
            this.btnEliminar.IdleIconRightImage = null;
            this.btnEliminar.IndicateFocus = false;
            this.btnEliminar.Location = new System.Drawing.Point(1, 0);
            this.btnEliminar.Name = "btnEliminar";
            this.btnEliminar.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnEliminar.OnDisabledState.BorderRadius = 15;
            this.btnEliminar.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnEliminar.OnDisabledState.BorderThickness = 1;
            this.btnEliminar.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnEliminar.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnEliminar.OnDisabledState.IconLeftImage = null;
            this.btnEliminar.OnDisabledState.IconRightImage = null;
            this.btnEliminar.onHoverState.BorderColor = System.Drawing.Color.MediumTurquoise;
            this.btnEliminar.onHoverState.BorderRadius = 15;
            this.btnEliminar.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnEliminar.onHoverState.BorderThickness = 1;
            this.btnEliminar.onHoverState.FillColor = System.Drawing.Color.MediumTurquoise;
            this.btnEliminar.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnEliminar.onHoverState.IconLeftImage = null;
            this.btnEliminar.onHoverState.IconRightImage = null;
            this.btnEliminar.OnIdleState.BorderColor = System.Drawing.Color.DarkTurquoise;
            this.btnEliminar.OnIdleState.BorderRadius = 15;
            this.btnEliminar.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnEliminar.OnIdleState.BorderThickness = 1;
            this.btnEliminar.OnIdleState.FillColor = System.Drawing.Color.DarkTurquoise;
            this.btnEliminar.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnEliminar.OnIdleState.IconLeftImage = null;
            this.btnEliminar.OnIdleState.IconRightImage = null;
            this.btnEliminar.OnPressedState.BorderColor = System.Drawing.Color.LightSeaGreen;
            this.btnEliminar.OnPressedState.BorderRadius = 15;
            this.btnEliminar.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnEliminar.OnPressedState.BorderThickness = 1;
            this.btnEliminar.OnPressedState.FillColor = System.Drawing.Color.LightSeaGreen;
            this.btnEliminar.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnEliminar.OnPressedState.IconLeftImage = null;
            this.btnEliminar.OnPressedState.IconRightImage = null;
            this.btnEliminar.Size = new System.Drawing.Size(253, 58);
            this.btnEliminar.TabIndex = 0;
            this.btnEliminar.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnEliminar.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnEliminar.TextMarginLeft = 0;
            this.btnEliminar.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnEliminar.UseDefaultRadiusAndThickness = true;
            // 
            // bunifuPanel4
            // 
            this.bunifuPanel4.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.bunifuPanel4.BackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.bunifuPanel4.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuPanel4.BackgroundImage")));
            this.bunifuPanel4.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.bunifuPanel4.BorderColor = System.Drawing.Color.Transparent;
            this.bunifuPanel4.BorderRadius = 15;
            this.bunifuPanel4.BorderThickness = 0;
            this.bunifuPanel4.Controls.Add(this.btnCargarImagen);
            this.bunifuPanel4.Location = new System.Drawing.Point(357, 50);
            this.bunifuPanel4.Name = "bunifuPanel4";
            this.bunifuPanel4.ShowBorders = true;
            this.bunifuPanel4.Size = new System.Drawing.Size(254, 62);
            this.bunifuPanel4.TabIndex = 69;
            // 
            // btnCargarImagen
            // 
            this.btnCargarImagen.AllowAnimations = true;
            this.btnCargarImagen.AllowMouseEffects = true;
            this.btnCargarImagen.AllowToggling = false;
            this.btnCargarImagen.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.btnCargarImagen.AnimationSpeed = 200;
            this.btnCargarImagen.AutoGenerateColors = false;
            this.btnCargarImagen.AutoRoundBorders = false;
            this.btnCargarImagen.AutoSizeLeftIcon = true;
            this.btnCargarImagen.AutoSizeRightIcon = true;
            this.btnCargarImagen.BackColor = System.Drawing.Color.Transparent;
            this.btnCargarImagen.BackColor1 = System.Drawing.Color.DarkTurquoise;
            this.btnCargarImagen.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnCargarImagen.BackgroundImage")));
            this.btnCargarImagen.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnCargarImagen.ButtonText = "Cambiar";
            this.btnCargarImagen.ButtonTextMarginLeft = 0;
            this.btnCargarImagen.ColorContrastOnClick = 45;
            this.btnCargarImagen.ColorContrastOnHover = 45;
            this.btnCargarImagen.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.btnCargarImagen.CustomizableEdges = borderEdges3;
            this.btnCargarImagen.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnCargarImagen.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnCargarImagen.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnCargarImagen.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnCargarImagen.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.btnCargarImagen.Font = new System.Drawing.Font("Century Gothic", 15F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnCargarImagen.ForeColor = System.Drawing.Color.White;
            this.btnCargarImagen.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnCargarImagen.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnCargarImagen.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnCargarImagen.IconMarginLeft = 11;
            this.btnCargarImagen.IconPadding = 10;
            this.btnCargarImagen.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnCargarImagen.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnCargarImagen.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnCargarImagen.IconSize = 25;
            this.btnCargarImagen.IdleBorderColor = System.Drawing.Color.DarkTurquoise;
            this.btnCargarImagen.IdleBorderRadius = 15;
            this.btnCargarImagen.IdleBorderThickness = 1;
            this.btnCargarImagen.IdleFillColor = System.Drawing.Color.DarkTurquoise;
            this.btnCargarImagen.IdleIconLeftImage = null;
            this.btnCargarImagen.IdleIconRightImage = null;
            this.btnCargarImagen.IndicateFocus = false;
            this.btnCargarImagen.Location = new System.Drawing.Point(1, 0);
            this.btnCargarImagen.Name = "btnCargarImagen";
            this.btnCargarImagen.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnCargarImagen.OnDisabledState.BorderRadius = 15;
            this.btnCargarImagen.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnCargarImagen.OnDisabledState.BorderThickness = 1;
            this.btnCargarImagen.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnCargarImagen.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnCargarImagen.OnDisabledState.IconLeftImage = null;
            this.btnCargarImagen.OnDisabledState.IconRightImage = null;
            this.btnCargarImagen.onHoverState.BorderColor = System.Drawing.Color.MediumTurquoise;
            this.btnCargarImagen.onHoverState.BorderRadius = 15;
            this.btnCargarImagen.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnCargarImagen.onHoverState.BorderThickness = 1;
            this.btnCargarImagen.onHoverState.FillColor = System.Drawing.Color.MediumTurquoise;
            this.btnCargarImagen.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnCargarImagen.onHoverState.IconLeftImage = null;
            this.btnCargarImagen.onHoverState.IconRightImage = null;
            this.btnCargarImagen.OnIdleState.BorderColor = System.Drawing.Color.DarkTurquoise;
            this.btnCargarImagen.OnIdleState.BorderRadius = 15;
            this.btnCargarImagen.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnCargarImagen.OnIdleState.BorderThickness = 1;
            this.btnCargarImagen.OnIdleState.FillColor = System.Drawing.Color.DarkTurquoise;
            this.btnCargarImagen.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnCargarImagen.OnIdleState.IconLeftImage = null;
            this.btnCargarImagen.OnIdleState.IconRightImage = null;
            this.btnCargarImagen.OnPressedState.BorderColor = System.Drawing.Color.LightSeaGreen;
            this.btnCargarImagen.OnPressedState.BorderRadius = 15;
            this.btnCargarImagen.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnCargarImagen.OnPressedState.BorderThickness = 1;
            this.btnCargarImagen.OnPressedState.FillColor = System.Drawing.Color.LightSeaGreen;
            this.btnCargarImagen.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnCargarImagen.OnPressedState.IconLeftImage = null;
            this.btnCargarImagen.OnPressedState.IconRightImage = null;
            this.btnCargarImagen.Size = new System.Drawing.Size(253, 58);
            this.btnCargarImagen.TabIndex = 0;
            this.btnCargarImagen.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnCargarImagen.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnCargarImagen.TextMarginLeft = 0;
            this.btnCargarImagen.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnCargarImagen.UseDefaultRadiusAndThickness = true;
            // 
            // picProfesional
            // 
            this.picProfesional.AllowFocused = false;
            this.picProfesional.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.picProfesional.AutoSizeHeight = true;
            this.picProfesional.BorderRadius = 112;
            this.picProfesional.Image = ((System.Drawing.Image)(resources.GetObject("picProfesional.Image")));
            this.picProfesional.IsCircle = false;
            this.picProfesional.Location = new System.Drawing.Point(38, 10);
            this.picProfesional.Name = "picProfesional";
            this.picProfesional.Size = new System.Drawing.Size(225, 225);
            this.picProfesional.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.picProfesional.TabIndex = 70;
            this.picProfesional.TabStop = false;
            this.picProfesional.Type = Bunifu.UI.WinForms.BunifuPictureBox.Types.Circle;
            // 
            // bunifuShadowPanel7
            // 
            this.bunifuShadowPanel7.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.bunifuShadowPanel7.BackColor = System.Drawing.Color.Transparent;
            this.bunifuShadowPanel7.BorderColor = System.Drawing.Color.Transparent;
            this.bunifuShadowPanel7.BorderRadius = 12;
            this.bunifuShadowPanel7.BorderThickness = 1;
            this.bunifuShadowPanel7.Controls.Add(this.txtTelefono);
            this.bunifuShadowPanel7.FillStyle = Bunifu.UI.WinForms.BunifuShadowPanel.FillStyles.Solid;
            this.bunifuShadowPanel7.GradientMode = Bunifu.UI.WinForms.BunifuShadowPanel.GradientModes.Vertical;
            this.bunifuShadowPanel7.Location = new System.Drawing.Point(62, 193);
            this.bunifuShadowPanel7.Name = "bunifuShadowPanel7";
            this.bunifuShadowPanel7.PanelColor = System.Drawing.Color.Transparent;
            this.bunifuShadowPanel7.PanelColor2 = System.Drawing.Color.Transparent;
            this.bunifuShadowPanel7.ShadowColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.bunifuShadowPanel7.ShadowDept = 2;
            this.bunifuShadowPanel7.ShadowDepth = 5;
            this.bunifuShadowPanel7.ShadowStyle = Bunifu.UI.WinForms.BunifuShadowPanel.ShadowStyles.Surrounded;
            this.bunifuShadowPanel7.ShadowTopLeftVisible = false;
            this.bunifuShadowPanel7.Size = new System.Drawing.Size(300, 57);
            this.bunifuShadowPanel7.Style = Bunifu.UI.WinForms.BunifuShadowPanel.BevelStyles.Flat;
            this.bunifuShadowPanel7.TabIndex = 67;
            // 
            // txtTelefono
            // 
            this.txtTelefono.AcceptsReturn = false;
            this.txtTelefono.AcceptsTab = true;
            this.txtTelefono.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.txtTelefono.AnimationSpeed = 200;
            this.txtTelefono.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtTelefono.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtTelefono.AutoSizeHeight = true;
            this.txtTelefono.BackColor = System.Drawing.Color.Transparent;
            this.txtTelefono.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtTelefono.BackgroundImage")));
            this.txtTelefono.BorderColorActive = System.Drawing.Color.Teal;
            this.txtTelefono.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtTelefono.BorderColorHover = System.Drawing.Color.LightSeaGreen;
            this.txtTelefono.BorderColorIdle = System.Drawing.Color.Transparent;
            this.txtTelefono.BorderRadius = 12;
            this.txtTelefono.BorderThickness = 0;
            this.txtTelefono.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.txtTelefono.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtTelefono.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtTelefono.DefaultFont = new System.Drawing.Font("Century Gothic", 14.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtTelefono.DefaultText = "";
            this.txtTelefono.FillColor = System.Drawing.Color.White;
            this.txtTelefono.HideSelection = true;
            this.txtTelefono.IconLeft = null;
            this.txtTelefono.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtTelefono.IconPadding = 10;
            this.txtTelefono.IconRight = null;
            this.txtTelefono.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtTelefono.Lines = new string[0];
            this.txtTelefono.Location = new System.Drawing.Point(5, 2);
            this.txtTelefono.MaxLength = 10;
            this.txtTelefono.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtTelefono.Modified = false;
            this.txtTelefono.Multiline = false;
            this.txtTelefono.Name = "txtTelefono";
            stateProperties5.BorderColor = System.Drawing.Color.Teal;
            stateProperties5.FillColor = System.Drawing.Color.Empty;
            stateProperties5.ForeColor = System.Drawing.Color.Empty;
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtTelefono.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties6.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties6.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtTelefono.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = System.Drawing.Color.LightSeaGreen;
            stateProperties7.FillColor = System.Drawing.Color.Empty;
            stateProperties7.ForeColor = System.Drawing.Color.Empty;
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtTelefono.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.Transparent;
            stateProperties8.FillColor = System.Drawing.Color.White;
            stateProperties8.ForeColor = System.Drawing.Color.Empty;
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtTelefono.OnIdleState = stateProperties8;
            this.txtTelefono.Padding = new System.Windows.Forms.Padding(3);
            this.txtTelefono.PasswordChar = '\0';
            this.txtTelefono.PlaceholderForeColor = System.Drawing.Color.Gray;
            this.txtTelefono.PlaceholderText = "Teléfono";
            this.txtTelefono.ReadOnly = false;
            this.txtTelefono.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtTelefono.SelectedText = "";
            this.txtTelefono.SelectionLength = 0;
            this.txtTelefono.SelectionStart = 0;
            this.txtTelefono.ShortcutsEnabled = false;
            this.txtTelefono.Size = new System.Drawing.Size(294, 50);
            this.txtTelefono.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtTelefono.TabIndex = 2;
            this.txtTelefono.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtTelefono.TextMarginBottom = 0;
            this.txtTelefono.TextMarginLeft = 3;
            this.txtTelefono.TextMarginTop = 1;
            this.txtTelefono.TextPlaceholder = "Teléfono";
            this.txtTelefono.UseSystemPasswordChar = false;
            this.txtTelefono.WordWrap = true;
            // 
            // lblTelefono
            // 
            this.lblTelefono.AllowParentOverrides = false;
            this.lblTelefono.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.lblTelefono.AutoEllipsis = false;
            this.lblTelefono.CursorType = null;
            this.lblTelefono.Font = new System.Drawing.Font("Century Gothic", 14.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblTelefono.Location = new System.Drawing.Point(67, 154);
            this.lblTelefono.Name = "lblTelefono";
            this.lblTelefono.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.lblTelefono.Size = new System.Drawing.Size(82, 23);
            this.lblTelefono.TabIndex = 68;
            this.lblTelefono.TabStop = false;
            this.lblTelefono.Text = "Teléfono:";
            this.lblTelefono.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.lblTelefono.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuShadowPanel4
            // 
            this.bunifuShadowPanel4.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.bunifuShadowPanel4.BackColor = System.Drawing.Color.Transparent;
            this.bunifuShadowPanel4.BorderColor = System.Drawing.Color.Transparent;
            this.bunifuShadowPanel4.BorderRadius = 12;
            this.bunifuShadowPanel4.BorderThickness = 1;
            this.bunifuShadowPanel4.Controls.Add(this.txtUsuario);
            this.bunifuShadowPanel4.FillStyle = Bunifu.UI.WinForms.BunifuShadowPanel.FillStyles.Solid;
            this.bunifuShadowPanel4.GradientMode = Bunifu.UI.WinForms.BunifuShadowPanel.GradientModes.Vertical;
            this.bunifuShadowPanel4.Location = new System.Drawing.Point(415, 192);
            this.bunifuShadowPanel4.Name = "bunifuShadowPanel4";
            this.bunifuShadowPanel4.PanelColor = System.Drawing.Color.Transparent;
            this.bunifuShadowPanel4.PanelColor2 = System.Drawing.Color.Transparent;
            this.bunifuShadowPanel4.ShadowColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.bunifuShadowPanel4.ShadowDept = 2;
            this.bunifuShadowPanel4.ShadowDepth = 5;
            this.bunifuShadowPanel4.ShadowStyle = Bunifu.UI.WinForms.BunifuShadowPanel.ShadowStyles.Surrounded;
            this.bunifuShadowPanel4.ShadowTopLeftVisible = false;
            this.bunifuShadowPanel4.Size = new System.Drawing.Size(300, 57);
            this.bunifuShadowPanel4.Style = Bunifu.UI.WinForms.BunifuShadowPanel.BevelStyles.Flat;
            this.bunifuShadowPanel4.TabIndex = 62;
            // 
            // txtUsuario
            // 
            this.txtUsuario.AcceptsReturn = false;
            this.txtUsuario.AcceptsTab = false;
            this.txtUsuario.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.txtUsuario.AnimationSpeed = 200;
            this.txtUsuario.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtUsuario.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtUsuario.AutoSizeHeight = true;
            this.txtUsuario.BackColor = System.Drawing.Color.Transparent;
            this.txtUsuario.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtUsuario.BackgroundImage")));
            this.txtUsuario.BorderColorActive = System.Drawing.Color.Teal;
            this.txtUsuario.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtUsuario.BorderColorHover = System.Drawing.Color.LightSeaGreen;
            this.txtUsuario.BorderColorIdle = System.Drawing.Color.Transparent;
            this.txtUsuario.BorderRadius = 12;
            this.txtUsuario.BorderThickness = 0;
            this.txtUsuario.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.txtUsuario.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtUsuario.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtUsuario.DefaultFont = new System.Drawing.Font("Century Gothic", 14.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtUsuario.DefaultText = "";
            this.txtUsuario.FillColor = System.Drawing.Color.White;
            this.txtUsuario.HideSelection = true;
            this.txtUsuario.IconLeft = null;
            this.txtUsuario.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtUsuario.IconPadding = 10;
            this.txtUsuario.IconRight = null;
            this.txtUsuario.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtUsuario.Lines = new string[0];
            this.txtUsuario.Location = new System.Drawing.Point(4, 1);
            this.txtUsuario.MaxLength = 30;
            this.txtUsuario.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtUsuario.Modified = false;
            this.txtUsuario.Multiline = false;
            this.txtUsuario.Name = "txtUsuario";
            stateProperties9.BorderColor = System.Drawing.Color.Teal;
            stateProperties9.FillColor = System.Drawing.Color.Empty;
            stateProperties9.ForeColor = System.Drawing.Color.Empty;
            stateProperties9.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtUsuario.OnActiveState = stateProperties9;
            stateProperties10.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties10.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties10.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties10.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtUsuario.OnDisabledState = stateProperties10;
            stateProperties11.BorderColor = System.Drawing.Color.LightSeaGreen;
            stateProperties11.FillColor = System.Drawing.Color.Empty;
            stateProperties11.ForeColor = System.Drawing.Color.Empty;
            stateProperties11.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtUsuario.OnHoverState = stateProperties11;
            stateProperties12.BorderColor = System.Drawing.Color.Transparent;
            stateProperties12.FillColor = System.Drawing.Color.White;
            stateProperties12.ForeColor = System.Drawing.Color.Empty;
            stateProperties12.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtUsuario.OnIdleState = stateProperties12;
            this.txtUsuario.Padding = new System.Windows.Forms.Padding(3);
            this.txtUsuario.PasswordChar = '\0';
            this.txtUsuario.PlaceholderForeColor = System.Drawing.Color.Gray;
            this.txtUsuario.PlaceholderText = "Usuario";
            this.txtUsuario.ReadOnly = false;
            this.txtUsuario.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtUsuario.SelectedText = "";
            this.txtUsuario.SelectionLength = 0;
            this.txtUsuario.SelectionStart = 0;
            this.txtUsuario.ShortcutsEnabled = false;
            this.txtUsuario.Size = new System.Drawing.Size(294, 50);
            this.txtUsuario.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtUsuario.TabIndex = 0;
            this.txtUsuario.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtUsuario.TextMarginBottom = 0;
            this.txtUsuario.TextMarginLeft = 3;
            this.txtUsuario.TextMarginTop = 1;
            this.txtUsuario.TextPlaceholder = "Usuario";
            this.txtUsuario.UseSystemPasswordChar = false;
            this.txtUsuario.WordWrap = true;
            // 
            // lblUsuario
            // 
            this.lblUsuario.AllowParentOverrides = false;
            this.lblUsuario.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.lblUsuario.AutoEllipsis = false;
            this.lblUsuario.CursorType = null;
            this.lblUsuario.Font = new System.Drawing.Font("Century Gothic", 14.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblUsuario.Location = new System.Drawing.Point(420, 155);
            this.lblUsuario.Name = "lblUsuario";
            this.lblUsuario.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.lblUsuario.Size = new System.Drawing.Size(73, 23);
            this.lblUsuario.TabIndex = 66;
            this.lblUsuario.TabStop = false;
            this.lblUsuario.Text = "Usuario:";
            this.lblUsuario.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.lblUsuario.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuShadowPanel5
            // 
            this.bunifuShadowPanel5.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.bunifuShadowPanel5.BackColor = System.Drawing.Color.Transparent;
            this.bunifuShadowPanel5.BorderColor = System.Drawing.Color.Transparent;
            this.bunifuShadowPanel5.BorderRadius = 12;
            this.bunifuShadowPanel5.BorderThickness = 1;
            this.bunifuShadowPanel5.Controls.Add(this.txtDui);
            this.bunifuShadowPanel5.FillStyle = Bunifu.UI.WinForms.BunifuShadowPanel.FillStyles.Solid;
            this.bunifuShadowPanel5.GradientMode = Bunifu.UI.WinForms.BunifuShadowPanel.GradientModes.Vertical;
            this.bunifuShadowPanel5.Location = new System.Drawing.Point(62, 79);
            this.bunifuShadowPanel5.Name = "bunifuShadowPanel5";
            this.bunifuShadowPanel5.PanelColor = System.Drawing.Color.Transparent;
            this.bunifuShadowPanel5.PanelColor2 = System.Drawing.Color.Transparent;
            this.bunifuShadowPanel5.ShadowColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.bunifuShadowPanel5.ShadowDept = 2;
            this.bunifuShadowPanel5.ShadowDepth = 5;
            this.bunifuShadowPanel5.ShadowStyle = Bunifu.UI.WinForms.BunifuShadowPanel.ShadowStyles.Surrounded;
            this.bunifuShadowPanel5.ShadowTopLeftVisible = false;
            this.bunifuShadowPanel5.Size = new System.Drawing.Size(300, 57);
            this.bunifuShadowPanel5.Style = Bunifu.UI.WinForms.BunifuShadowPanel.BevelStyles.Flat;
            this.bunifuShadowPanel5.TabIndex = 61;
            // 
            // txtDui
            // 
            this.txtDui.AcceptsReturn = false;
            this.txtDui.AcceptsTab = true;
            this.txtDui.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.txtDui.AnimationSpeed = 200;
            this.txtDui.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtDui.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtDui.AutoSizeHeight = true;
            this.txtDui.BackColor = System.Drawing.Color.Transparent;
            this.txtDui.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtDui.BackgroundImage")));
            this.txtDui.BorderColorActive = System.Drawing.Color.Teal;
            this.txtDui.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtDui.BorderColorHover = System.Drawing.Color.LightSeaGreen;
            this.txtDui.BorderColorIdle = System.Drawing.Color.Transparent;
            this.txtDui.BorderRadius = 12;
            this.txtDui.BorderThickness = 0;
            this.txtDui.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.txtDui.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtDui.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtDui.DefaultFont = new System.Drawing.Font("Century Gothic", 14.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtDui.DefaultText = "";
            this.txtDui.FillColor = System.Drawing.Color.White;
            this.txtDui.HideSelection = true;
            this.txtDui.IconLeft = null;
            this.txtDui.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtDui.IconPadding = 10;
            this.txtDui.IconRight = null;
            this.txtDui.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtDui.Lines = new string[0];
            this.txtDui.Location = new System.Drawing.Point(5, 2);
            this.txtDui.MaxLength = 11;
            this.txtDui.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtDui.Modified = false;
            this.txtDui.Multiline = false;
            this.txtDui.Name = "txtDui";
            stateProperties13.BorderColor = System.Drawing.Color.Teal;
            stateProperties13.FillColor = System.Drawing.Color.Empty;
            stateProperties13.ForeColor = System.Drawing.Color.Empty;
            stateProperties13.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtDui.OnActiveState = stateProperties13;
            stateProperties14.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties14.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties14.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties14.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtDui.OnDisabledState = stateProperties14;
            stateProperties15.BorderColor = System.Drawing.Color.LightSeaGreen;
            stateProperties15.FillColor = System.Drawing.Color.Empty;
            stateProperties15.ForeColor = System.Drawing.Color.Empty;
            stateProperties15.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtDui.OnHoverState = stateProperties15;
            stateProperties16.BorderColor = System.Drawing.Color.Transparent;
            stateProperties16.FillColor = System.Drawing.Color.White;
            stateProperties16.ForeColor = System.Drawing.Color.Empty;
            stateProperties16.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtDui.OnIdleState = stateProperties16;
            this.txtDui.Padding = new System.Windows.Forms.Padding(3);
            this.txtDui.PasswordChar = '\0';
            this.txtDui.PlaceholderForeColor = System.Drawing.Color.Gray;
            this.txtDui.PlaceholderText = "Documento";
            this.txtDui.ReadOnly = false;
            this.txtDui.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtDui.SelectedText = "";
            this.txtDui.SelectionLength = 0;
            this.txtDui.SelectionStart = 0;
            this.txtDui.ShortcutsEnabled = false;
            this.txtDui.Size = new System.Drawing.Size(294, 50);
            this.txtDui.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtDui.TabIndex = 0;
            this.txtDui.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtDui.TextMarginBottom = 0;
            this.txtDui.TextMarginLeft = 3;
            this.txtDui.TextMarginTop = 1;
            this.txtDui.TextPlaceholder = "Documento";
            this.txtDui.UseSystemPasswordChar = false;
            this.txtDui.WordWrap = true;
            // 
            // lblDocumento
            // 
            this.lblDocumento.AllowParentOverrides = false;
            this.lblDocumento.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.lblDocumento.AutoEllipsis = false;
            this.lblDocumento.CursorType = null;
            this.lblDocumento.Font = new System.Drawing.Font("Century Gothic", 14.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblDocumento.Location = new System.Drawing.Point(66, 42);
            this.lblDocumento.Name = "lblDocumento";
            this.lblDocumento.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.lblDocumento.Size = new System.Drawing.Size(107, 23);
            this.lblDocumento.TabIndex = 65;
            this.lblDocumento.TabStop = false;
            this.lblDocumento.Text = "Documento";
            this.lblDocumento.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.lblDocumento.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuShadowPanel3
            // 
            this.bunifuShadowPanel3.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.bunifuShadowPanel3.BackColor = System.Drawing.Color.Transparent;
            this.bunifuShadowPanel3.BorderColor = System.Drawing.Color.Transparent;
            this.bunifuShadowPanel3.BorderRadius = 12;
            this.bunifuShadowPanel3.BorderThickness = 1;
            this.bunifuShadowPanel3.Controls.Add(this.txtApellido);
            this.bunifuShadowPanel3.FillStyle = Bunifu.UI.WinForms.BunifuShadowPanel.FillStyles.Solid;
            this.bunifuShadowPanel3.GradientMode = Bunifu.UI.WinForms.BunifuShadowPanel.GradientModes.Vertical;
            this.bunifuShadowPanel3.Location = new System.Drawing.Point(777, 79);
            this.bunifuShadowPanel3.Name = "bunifuShadowPanel3";
            this.bunifuShadowPanel3.PanelColor = System.Drawing.Color.Transparent;
            this.bunifuShadowPanel3.PanelColor2 = System.Drawing.Color.Transparent;
            this.bunifuShadowPanel3.ShadowColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.bunifuShadowPanel3.ShadowDept = 2;
            this.bunifuShadowPanel3.ShadowDepth = 5;
            this.bunifuShadowPanel3.ShadowStyle = Bunifu.UI.WinForms.BunifuShadowPanel.ShadowStyles.Surrounded;
            this.bunifuShadowPanel3.ShadowTopLeftVisible = false;
            this.bunifuShadowPanel3.Size = new System.Drawing.Size(300, 57);
            this.bunifuShadowPanel3.Style = Bunifu.UI.WinForms.BunifuShadowPanel.BevelStyles.Flat;
            this.bunifuShadowPanel3.TabIndex = 60;
            // 
            // txtApellido
            // 
            this.txtApellido.AcceptsReturn = false;
            this.txtApellido.AcceptsTab = true;
            this.txtApellido.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.txtApellido.AnimationSpeed = 200;
            this.txtApellido.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtApellido.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtApellido.AutoSizeHeight = true;
            this.txtApellido.BackColor = System.Drawing.Color.Transparent;
            this.txtApellido.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtApellido.BackgroundImage")));
            this.txtApellido.BorderColorActive = System.Drawing.Color.Teal;
            this.txtApellido.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtApellido.BorderColorHover = System.Drawing.Color.LightSeaGreen;
            this.txtApellido.BorderColorIdle = System.Drawing.Color.Transparent;
            this.txtApellido.BorderRadius = 12;
            this.txtApellido.BorderThickness = 0;
            this.txtApellido.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.txtApellido.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtApellido.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtApellido.DefaultFont = new System.Drawing.Font("Century Gothic", 14.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtApellido.DefaultText = "";
            this.txtApellido.FillColor = System.Drawing.Color.White;
            this.txtApellido.HideSelection = true;
            this.txtApellido.IconLeft = null;
            this.txtApellido.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtApellido.IconPadding = 10;
            this.txtApellido.IconRight = null;
            this.txtApellido.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtApellido.Lines = new string[0];
            this.txtApellido.Location = new System.Drawing.Point(6, 2);
            this.txtApellido.MaxLength = 65;
            this.txtApellido.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtApellido.Modified = false;
            this.txtApellido.Multiline = false;
            this.txtApellido.Name = "txtApellido";
            stateProperties17.BorderColor = System.Drawing.Color.Teal;
            stateProperties17.FillColor = System.Drawing.Color.Empty;
            stateProperties17.ForeColor = System.Drawing.Color.Empty;
            stateProperties17.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtApellido.OnActiveState = stateProperties17;
            stateProperties18.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties18.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties18.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties18.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtApellido.OnDisabledState = stateProperties18;
            stateProperties19.BorderColor = System.Drawing.Color.LightSeaGreen;
            stateProperties19.FillColor = System.Drawing.Color.Empty;
            stateProperties19.ForeColor = System.Drawing.Color.Empty;
            stateProperties19.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtApellido.OnHoverState = stateProperties19;
            stateProperties20.BorderColor = System.Drawing.Color.Transparent;
            stateProperties20.FillColor = System.Drawing.Color.White;
            stateProperties20.ForeColor = System.Drawing.Color.Empty;
            stateProperties20.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtApellido.OnIdleState = stateProperties20;
            this.txtApellido.Padding = new System.Windows.Forms.Padding(3);
            this.txtApellido.PasswordChar = '\0';
            this.txtApellido.PlaceholderForeColor = System.Drawing.Color.Gray;
            this.txtApellido.PlaceholderText = "Apellidos";
            this.txtApellido.ReadOnly = false;
            this.txtApellido.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtApellido.SelectedText = "";
            this.txtApellido.SelectionLength = 0;
            this.txtApellido.SelectionStart = 0;
            this.txtApellido.ShortcutsEnabled = false;
            this.txtApellido.Size = new System.Drawing.Size(294, 50);
            this.txtApellido.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtApellido.TabIndex = 0;
            this.txtApellido.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtApellido.TextMarginBottom = 0;
            this.txtApellido.TextMarginLeft = 3;
            this.txtApellido.TextMarginTop = 1;
            this.txtApellido.TextPlaceholder = "Apellidos";
            this.txtApellido.UseSystemPasswordChar = false;
            this.txtApellido.WordWrap = true;
            // 
            // bunifuShadowPanel1
            // 
            this.bunifuShadowPanel1.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.bunifuShadowPanel1.BackColor = System.Drawing.Color.Transparent;
            this.bunifuShadowPanel1.BorderColor = System.Drawing.Color.Transparent;
            this.bunifuShadowPanel1.BorderRadius = 12;
            this.bunifuShadowPanel1.BorderThickness = 1;
            this.bunifuShadowPanel1.Controls.Add(this.txtNombre);
            this.bunifuShadowPanel1.FillStyle = Bunifu.UI.WinForms.BunifuShadowPanel.FillStyles.Solid;
            this.bunifuShadowPanel1.GradientMode = Bunifu.UI.WinForms.BunifuShadowPanel.GradientModes.Vertical;
            this.bunifuShadowPanel1.Location = new System.Drawing.Point(420, 79);
            this.bunifuShadowPanel1.Name = "bunifuShadowPanel1";
            this.bunifuShadowPanel1.PanelColor = System.Drawing.Color.Transparent;
            this.bunifuShadowPanel1.PanelColor2 = System.Drawing.Color.Transparent;
            this.bunifuShadowPanel1.ShadowColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.bunifuShadowPanel1.ShadowDept = 2;
            this.bunifuShadowPanel1.ShadowDepth = 5;
            this.bunifuShadowPanel1.ShadowStyle = Bunifu.UI.WinForms.BunifuShadowPanel.ShadowStyles.Surrounded;
            this.bunifuShadowPanel1.ShadowTopLeftVisible = false;
            this.bunifuShadowPanel1.Size = new System.Drawing.Size(300, 57);
            this.bunifuShadowPanel1.Style = Bunifu.UI.WinForms.BunifuShadowPanel.BevelStyles.Flat;
            this.bunifuShadowPanel1.TabIndex = 59;
            // 
            // txtNombre
            // 
            this.txtNombre.AcceptsReturn = false;
            this.txtNombre.AcceptsTab = true;
            this.txtNombre.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.txtNombre.AnimationSpeed = 200;
            this.txtNombre.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtNombre.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtNombre.AutoSizeHeight = true;
            this.txtNombre.BackColor = System.Drawing.Color.Transparent;
            this.txtNombre.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtNombre.BackgroundImage")));
            this.txtNombre.BorderColorActive = System.Drawing.Color.Teal;
            this.txtNombre.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtNombre.BorderColorHover = System.Drawing.Color.LightSeaGreen;
            this.txtNombre.BorderColorIdle = System.Drawing.Color.Transparent;
            this.txtNombre.BorderRadius = 12;
            this.txtNombre.BorderThickness = 0;
            this.txtNombre.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.txtNombre.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtNombre.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtNombre.DefaultFont = new System.Drawing.Font("Century Gothic", 14.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtNombre.DefaultText = "";
            this.txtNombre.FillColor = System.Drawing.Color.White;
            this.txtNombre.HideSelection = true;
            this.txtNombre.IconLeft = null;
            this.txtNombre.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtNombre.IconPadding = 10;
            this.txtNombre.IconRight = null;
            this.txtNombre.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtNombre.Lines = new string[0];
            this.txtNombre.Location = new System.Drawing.Point(5, 2);
            this.txtNombre.MaxLength = 65;
            this.txtNombre.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtNombre.Modified = false;
            this.txtNombre.Multiline = false;
            this.txtNombre.Name = "txtNombre";
            stateProperties21.BorderColor = System.Drawing.Color.Teal;
            stateProperties21.FillColor = System.Drawing.Color.Empty;
            stateProperties21.ForeColor = System.Drawing.Color.Empty;
            stateProperties21.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtNombre.OnActiveState = stateProperties21;
            stateProperties22.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties22.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties22.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties22.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtNombre.OnDisabledState = stateProperties22;
            stateProperties23.BorderColor = System.Drawing.Color.LightSeaGreen;
            stateProperties23.FillColor = System.Drawing.Color.Empty;
            stateProperties23.ForeColor = System.Drawing.Color.Empty;
            stateProperties23.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtNombre.OnHoverState = stateProperties23;
            stateProperties24.BorderColor = System.Drawing.Color.Transparent;
            stateProperties24.FillColor = System.Drawing.Color.White;
            stateProperties24.ForeColor = System.Drawing.Color.Empty;
            stateProperties24.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtNombre.OnIdleState = stateProperties24;
            this.txtNombre.Padding = new System.Windows.Forms.Padding(3);
            this.txtNombre.PasswordChar = '\0';
            this.txtNombre.PlaceholderForeColor = System.Drawing.Color.Gray;
            this.txtNombre.PlaceholderText = "Nombres";
            this.txtNombre.ReadOnly = false;
            this.txtNombre.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtNombre.SelectedText = "";
            this.txtNombre.SelectionLength = 0;
            this.txtNombre.SelectionStart = 0;
            this.txtNombre.ShortcutsEnabled = false;
            this.txtNombre.Size = new System.Drawing.Size(294, 50);
            this.txtNombre.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtNombre.TabIndex = 0;
            this.txtNombre.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtNombre.TextMarginBottom = 0;
            this.txtNombre.TextMarginLeft = 3;
            this.txtNombre.TextMarginTop = 1;
            this.txtNombre.TextPlaceholder = "Nombres";
            this.txtNombre.UseSystemPasswordChar = false;
            this.txtNombre.WordWrap = true;
            // 
            // lblApellidos
            // 
            this.lblApellidos.AllowParentOverrides = false;
            this.lblApellidos.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.lblApellidos.AutoEllipsis = false;
            this.lblApellidos.CursorType = null;
            this.lblApellidos.Font = new System.Drawing.Font("Century Gothic", 14.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblApellidos.Location = new System.Drawing.Point(783, 41);
            this.lblApellidos.Name = "lblApellidos";
            this.lblApellidos.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.lblApellidos.Size = new System.Drawing.Size(92, 23);
            this.lblApellidos.TabIndex = 63;
            this.lblApellidos.TabStop = false;
            this.lblApellidos.Text = "Apellidos:";
            this.lblApellidos.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.lblApellidos.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // lblNombres
            // 
            this.lblNombres.AllowParentOverrides = false;
            this.lblNombres.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.lblNombres.AutoEllipsis = false;
            this.lblNombres.Cursor = System.Windows.Forms.Cursors.Default;
            this.lblNombres.CursorType = System.Windows.Forms.Cursors.Default;
            this.lblNombres.Font = new System.Drawing.Font("Century Gothic", 14.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblNombres.Location = new System.Drawing.Point(425, 41);
            this.lblNombres.Name = "lblNombres";
            this.lblNombres.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.lblNombres.Size = new System.Drawing.Size(88, 23);
            this.lblNombres.TabIndex = 64;
            this.lblNombres.TabStop = false;
            this.lblNombres.Text = "Nombres:";
            this.lblNombres.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.lblNombres.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // Titulo_Registrar
            // 
            this.Titulo_Registrar.AllowParentOverrides = false;
            this.Titulo_Registrar.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.Titulo_Registrar.AutoEllipsis = false;
            this.Titulo_Registrar.Cursor = System.Windows.Forms.Cursors.Default;
            this.Titulo_Registrar.CursorType = System.Windows.Forms.Cursors.Default;
            this.Titulo_Registrar.Font = new System.Drawing.Font("Century Gothic", 21.75F);
            this.Titulo_Registrar.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(42)))), ((int)(((byte)(86)))), ((int)(((byte)(100)))));
            this.Titulo_Registrar.Location = new System.Drawing.Point(60, 33);
            this.Titulo_Registrar.Name = "Titulo_Registrar";
            this.Titulo_Registrar.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.Titulo_Registrar.Size = new System.Drawing.Size(366, 36);
            this.Titulo_Registrar.TabIndex = 0;
            this.Titulo_Registrar.TabStop = false;
            this.Titulo_Registrar.Text = "Configuración de Usuario";
            this.Titulo_Registrar.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.Titulo_Registrar.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // Notificacion1
            // 
            this.Notificacion1.AllowDragging = false;
            this.Notificacion1.AllowMultipleViews = true;
            this.Notificacion1.ClickToClose = true;
            this.Notificacion1.DoubleClickToClose = true;
            this.Notificacion1.DurationAfterIdle = 3000;
            this.Notificacion1.ErrorOptions.ActionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.Notificacion1.ErrorOptions.ActionBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.Notificacion1.ErrorOptions.ActionBorderRadius = 1;
            this.Notificacion1.ErrorOptions.ActionFont = new System.Drawing.Font("Century Gothic", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.Notificacion1.ErrorOptions.ActionForeColor = System.Drawing.Color.Black;
            this.Notificacion1.ErrorOptions.BackColor = System.Drawing.Color.White;
            this.Notificacion1.ErrorOptions.BorderColor = System.Drawing.Color.White;
            this.Notificacion1.ErrorOptions.CloseIconColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(204)))), ((int)(((byte)(199)))));
            this.Notificacion1.ErrorOptions.Font = new System.Drawing.Font("Segoe UI", 9.75F);
            this.Notificacion1.ErrorOptions.ForeColor = System.Drawing.Color.Black;
            this.Notificacion1.ErrorOptions.Icon = ((System.Drawing.Image)(resources.GetObject("resource.Icon")));
            this.Notificacion1.ErrorOptions.IconLeftMargin = 12;
            this.Notificacion1.FadeCloseIcon = false;
            this.Notificacion1.Host = Bunifu.UI.WinForms.BunifuSnackbar.Hosts.FormOwner;
            this.Notificacion1.InformationOptions.ActionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.Notificacion1.InformationOptions.ActionBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.Notificacion1.InformationOptions.ActionBorderRadius = 1;
            this.Notificacion1.InformationOptions.ActionFont = new System.Drawing.Font("Segoe UI", 8.25F, System.Drawing.FontStyle.Bold);
            this.Notificacion1.InformationOptions.ActionForeColor = System.Drawing.Color.Black;
            this.Notificacion1.InformationOptions.BackColor = System.Drawing.Color.White;
            this.Notificacion1.InformationOptions.BorderColor = System.Drawing.Color.White;
            this.Notificacion1.InformationOptions.CloseIconColor = System.Drawing.Color.FromArgb(((int)(((byte)(145)))), ((int)(((byte)(213)))), ((int)(((byte)(255)))));
            this.Notificacion1.InformationOptions.Font = new System.Drawing.Font("Century Gothic", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.Notificacion1.InformationOptions.ForeColor = System.Drawing.Color.Black;
            this.Notificacion1.InformationOptions.Icon = ((System.Drawing.Image)(resources.GetObject("resource.Icon1")));
            this.Notificacion1.InformationOptions.IconLeftMargin = 12;
            this.Notificacion1.Margin = 10;
            this.Notificacion1.MaximumSize = new System.Drawing.Size(0, 0);
            this.Notificacion1.MaximumViews = 1;
            this.Notificacion1.MessageRightMargin = 15;
            this.Notificacion1.MessageTopMargin = 0;
            this.Notificacion1.MinimumSize = new System.Drawing.Size(0, 0);
            this.Notificacion1.ShowBorders = false;
            this.Notificacion1.ShowCloseIcon = false;
            this.Notificacion1.ShowIcon = true;
            this.Notificacion1.ShowShadows = true;
            this.Notificacion1.SuccessOptions.ActionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.Notificacion1.SuccessOptions.ActionBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.Notificacion1.SuccessOptions.ActionBorderRadius = 1;
            this.Notificacion1.SuccessOptions.ActionFont = new System.Drawing.Font("Segoe UI", 8.25F, System.Drawing.FontStyle.Bold);
            this.Notificacion1.SuccessOptions.ActionForeColor = System.Drawing.Color.Black;
            this.Notificacion1.SuccessOptions.BackColor = System.Drawing.Color.White;
            this.Notificacion1.SuccessOptions.BorderColor = System.Drawing.Color.White;
            this.Notificacion1.SuccessOptions.CloseIconColor = System.Drawing.Color.FromArgb(((int)(((byte)(246)))), ((int)(((byte)(255)))), ((int)(((byte)(237)))));
            this.Notificacion1.SuccessOptions.Font = new System.Drawing.Font("Segoe UI", 9.75F);
            this.Notificacion1.SuccessOptions.ForeColor = System.Drawing.Color.Black;
            this.Notificacion1.SuccessOptions.Icon = ((System.Drawing.Image)(resources.GetObject("resource.Icon2")));
            this.Notificacion1.SuccessOptions.IconLeftMargin = 12;
            this.Notificacion1.ViewsMargin = 7;
            this.Notificacion1.WarningOptions.ActionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.Notificacion1.WarningOptions.ActionBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.Notificacion1.WarningOptions.ActionBorderRadius = 1;
            this.Notificacion1.WarningOptions.ActionFont = new System.Drawing.Font("Segoe UI", 8.25F, System.Drawing.FontStyle.Bold);
            this.Notificacion1.WarningOptions.ActionForeColor = System.Drawing.Color.Black;
            this.Notificacion1.WarningOptions.BackColor = System.Drawing.Color.White;
            this.Notificacion1.WarningOptions.BorderColor = System.Drawing.Color.White;
            this.Notificacion1.WarningOptions.CloseIconColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(229)))), ((int)(((byte)(143)))));
            this.Notificacion1.WarningOptions.Font = new System.Drawing.Font("Segoe UI", 9.75F);
            this.Notificacion1.WarningOptions.ForeColor = System.Drawing.Color.Black;
            this.Notificacion1.WarningOptions.Icon = ((System.Drawing.Image)(resources.GetObject("resource.Icon3")));
            this.Notificacion1.WarningOptions.IconLeftMargin = 12;
            this.Notificacion1.ZoomCloseIcon = true;
            // 
            // ofdImagen
            // 
            this.ofdImagen.FileName = "ofdImagen";
            // 
            // ConfiguraciónDeUsuarioForm
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(54)))), ((int)(((byte)(164)))), ((int)(((byte)(171)))));
            this.ClientSize = new System.Drawing.Size(1264, 681);
            this.Controls.Add(this.bunifuGradientPanel3);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.SizableToolWindow;
            this.Icon = ((System.Drawing.Icon)(resources.GetObject("$this.Icon")));
            this.MaximumSize = new System.Drawing.Size(1280, 720);
            this.MinimumSize = new System.Drawing.Size(1280, 720);
            this.Name = "ConfiguraciónDeUsuarioForm";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "Configuración de Usuario";
            this.bunifuGradientPanel3.ResumeLayout(false);
            this.bunifuGradientPanel3.PerformLayout();
            this.bunifuGradientPanel1.ResumeLayout(false);
            this.bunifuGradientPanel1.PerformLayout();
            this.bunifuShadowPanel2.ResumeLayout(false);
            this.bunifuPanel3.ResumeLayout(false);
            this.bunifuPanel1.ResumeLayout(false);
            this.bunifuPanel2.ResumeLayout(false);
            this.bunifuPanel4.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.picProfesional)).EndInit();
            this.bunifuShadowPanel7.ResumeLayout(false);
            this.bunifuShadowPanel4.ResumeLayout(false);
            this.bunifuShadowPanel5.ResumeLayout(false);
            this.bunifuShadowPanel3.ResumeLayout(false);
            this.bunifuShadowPanel1.ResumeLayout(false);
            this.ResumeLayout(false);

        }

        #endregion

        public Bunifu.UI.WinForms.BunifuGradientPanel bunifuGradientPanel3;
        public Bunifu.UI.WinForms.BunifuGradientPanel bunifuGradientPanel1;
        public Bunifu.UI.WinForms.BunifuPanel bunifuPanel3;
        public Bunifu.UI.WinForms.BunifuButton.BunifuButton2 btnGuardar;
        private Bunifu.UI.WinForms.BunifuPanel bunifuPanel1;
        public Bunifu.UI.WinForms.BunifuPanel bunifuPanel2;
        public Bunifu.UI.WinForms.BunifuButton.BunifuButton2 btnEliminar;
        public Bunifu.UI.WinForms.BunifuPanel bunifuPanel4;
        public Bunifu.UI.WinForms.BunifuButton.BunifuButton2 btnCargarImagen;
        public Bunifu.UI.WinForms.BunifuPictureBox picProfesional;
        public Bunifu.UI.WinForms.BunifuShadowPanel bunifuShadowPanel7;
        public Bunifu.UI.WinForms.BunifuTextBox txtTelefono;
        public Bunifu.UI.WinForms.BunifuLabel lblTelefono;
        public Bunifu.UI.WinForms.BunifuShadowPanel bunifuShadowPanel4;
        public Bunifu.UI.WinForms.BunifuTextBox txtUsuario;
        public Bunifu.UI.WinForms.BunifuLabel lblUsuario;
        public Bunifu.UI.WinForms.BunifuShadowPanel bunifuShadowPanel5;
        public Bunifu.UI.WinForms.BunifuTextBox txtDui;
        public Bunifu.UI.WinForms.BunifuLabel lblDocumento;
        public Bunifu.UI.WinForms.BunifuShadowPanel bunifuShadowPanel3;
        public Bunifu.UI.WinForms.BunifuTextBox txtApellido;
        public Bunifu.UI.WinForms.BunifuShadowPanel bunifuShadowPanel1;
        public Bunifu.UI.WinForms.BunifuTextBox txtNombre;
        public Bunifu.UI.WinForms.BunifuLabel lblApellidos;
        public Bunifu.UI.WinForms.BunifuLabel lblNombres;
        public Bunifu.UI.WinForms.BunifuLabel Titulo_Registrar;
        public Bunifu.UI.WinForms.BunifuSnackbar Notificacion1;
        public Bunifu.UI.WinForms.BunifuShadowPanel bunifuShadowPanel2;
        public Bunifu.UI.WinForms.BunifuTextBox txtCorreo;
        public Bunifu.UI.WinForms.BunifuLabel lblCorreo;
        public System.Windows.Forms.OpenFileDialog ofdImagen;
    }
}