namespace Empresa_laboral_ADNE___Proyecto_PTC.Vista
{
    partial class PreguntasdeSeguridadForm
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(PreguntasdeSeguridadForm));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties25 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties26 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties27 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties28 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties29 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties30 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties31 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties32 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties33 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties34 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties35 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties36 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties37 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties38 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties39 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties40 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties41 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties42 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties43 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties44 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties45 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties46 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties47 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties48 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            this.pnlGradiente = new Bunifu.UI.WinForms.BunifuGradientPanel();
            this.pnlSombraFondo = new Bunifu.UI.WinForms.BunifuShadowPanel();
            this.pnlSombraBtn = new Bunifu.UI.WinForms.BunifuShadowPanel();
            this.btnVerificarPregunta = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.txtCuartaPregunta = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtTerceraPregunta = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtSegundaPregunta = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtPrimeraPregunta = new Bunifu.UI.WinForms.BunifuTextBox();
            this.cmbCuartaPregunta = new Bunifu.UI.WinForms.BunifuDropdown();
            this.cmbTerceraPregunta = new Bunifu.UI.WinForms.BunifuDropdown();
            this.cmbSegundaPregunta = new Bunifu.UI.WinForms.BunifuDropdown();
            this.cmbPrimeraPregunta = new Bunifu.UI.WinForms.BunifuDropdown();
            this.pnlSombraBoton = new Bunifu.UI.WinForms.BunifuShadowPanel();
            this.btnComprobar = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.lblTitulo = new Bunifu.UI.WinForms.BunifuLabel();
            this.txtUsuario = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtDocumento = new Bunifu.UI.WinForms.BunifuTextBox();
            this.pnlLineaDivisora = new Bunifu.UI.WinForms.BunifuPanel();
            this.lblIndicacion = new Bunifu.UI.WinForms.BunifuLabel();
            this.lblIngreseCredenciales = new Bunifu.UI.WinForms.BunifuLabel();
            this.pnlGradiente.SuspendLayout();
            this.pnlSombraFondo.SuspendLayout();
            this.pnlSombraBtn.SuspendLayout();
            this.pnlSombraBoton.SuspendLayout();
            this.SuspendLayout();
            // 
            // pnlGradiente
            // 
            this.pnlGradiente.BackColor = System.Drawing.Color.Transparent;
            this.pnlGradiente.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("pnlGradiente.BackgroundImage")));
            this.pnlGradiente.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.pnlGradiente.BorderRadius = 1;
            this.pnlGradiente.Controls.Add(this.pnlSombraFondo);
            this.pnlGradiente.Dock = System.Windows.Forms.DockStyle.Fill;
            this.pnlGradiente.GradientBottomLeft = System.Drawing.Color.Teal;
            this.pnlGradiente.GradientBottomRight = System.Drawing.Color.Teal;
            this.pnlGradiente.GradientTopLeft = System.Drawing.Color.LightSeaGreen;
            this.pnlGradiente.GradientTopRight = System.Drawing.Color.LightSeaGreen;
            this.pnlGradiente.Location = new System.Drawing.Point(0, 0);
            this.pnlGradiente.Name = "pnlGradiente";
            this.pnlGradiente.Padding = new System.Windows.Forms.Padding(30);
            this.pnlGradiente.Quality = 10;
            this.pnlGradiente.Size = new System.Drawing.Size(715, 874);
            this.pnlGradiente.TabIndex = 1;
            // 
            // pnlSombraFondo
            // 
            this.pnlSombraFondo.BackColor = System.Drawing.Color.Transparent;
            this.pnlSombraFondo.BorderColor = System.Drawing.Color.WhiteSmoke;
            this.pnlSombraFondo.BorderRadius = 25;
            this.pnlSombraFondo.BorderThickness = 1;
            this.pnlSombraFondo.Controls.Add(this.lblIngreseCredenciales);
            this.pnlSombraFondo.Controls.Add(this.lblIndicacion);
            this.pnlSombraFondo.Controls.Add(this.pnlLineaDivisora);
            this.pnlSombraFondo.Controls.Add(this.txtDocumento);
            this.pnlSombraFondo.Controls.Add(this.txtUsuario);
            this.pnlSombraFondo.Controls.Add(this.pnlSombraBtn);
            this.pnlSombraFondo.Controls.Add(this.txtCuartaPregunta);
            this.pnlSombraFondo.Controls.Add(this.txtTerceraPregunta);
            this.pnlSombraFondo.Controls.Add(this.txtSegundaPregunta);
            this.pnlSombraFondo.Controls.Add(this.txtPrimeraPregunta);
            this.pnlSombraFondo.Controls.Add(this.cmbCuartaPregunta);
            this.pnlSombraFondo.Controls.Add(this.cmbTerceraPregunta);
            this.pnlSombraFondo.Controls.Add(this.cmbSegundaPregunta);
            this.pnlSombraFondo.Controls.Add(this.cmbPrimeraPregunta);
            this.pnlSombraFondo.Controls.Add(this.pnlSombraBoton);
            this.pnlSombraFondo.Controls.Add(this.lblTitulo);
            this.pnlSombraFondo.Dock = System.Windows.Forms.DockStyle.Fill;
            this.pnlSombraFondo.FillStyle = Bunifu.UI.WinForms.BunifuShadowPanel.FillStyles.Solid;
            this.pnlSombraFondo.Font = new System.Drawing.Font("Century Gothic", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.pnlSombraFondo.GradientMode = Bunifu.UI.WinForms.BunifuShadowPanel.GradientModes.Vertical;
            this.pnlSombraFondo.Location = new System.Drawing.Point(30, 30);
            this.pnlSombraFondo.Name = "pnlSombraFondo";
            this.pnlSombraFondo.PanelColor = System.Drawing.Color.WhiteSmoke;
            this.pnlSombraFondo.PanelColor2 = System.Drawing.Color.WhiteSmoke;
            this.pnlSombraFondo.ShadowColor = System.Drawing.Color.FromArgb(((int)(((byte)(190)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.pnlSombraFondo.ShadowDept = 2;
            this.pnlSombraFondo.ShadowDepth = 5;
            this.pnlSombraFondo.ShadowStyle = Bunifu.UI.WinForms.BunifuShadowPanel.ShadowStyles.Surrounded;
            this.pnlSombraFondo.ShadowTopLeftVisible = false;
            this.pnlSombraFondo.Size = new System.Drawing.Size(655, 814);
            this.pnlSombraFondo.Style = Bunifu.UI.WinForms.BunifuShadowPanel.BevelStyles.Flat;
            this.pnlSombraFondo.TabIndex = 0;
            // 
            // pnlSombraBtn
            // 
            this.pnlSombraBtn.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right)));
            this.pnlSombraBtn.BackColor = System.Drawing.Color.Transparent;
            this.pnlSombraBtn.BorderColor = System.Drawing.Color.Transparent;
            this.pnlSombraBtn.BorderRadius = 10;
            this.pnlSombraBtn.BorderThickness = 1;
            this.pnlSombraBtn.Controls.Add(this.btnVerificarPregunta);
            this.pnlSombraBtn.FillStyle = Bunifu.UI.WinForms.BunifuShadowPanel.FillStyles.Solid;
            this.pnlSombraBtn.GradientMode = Bunifu.UI.WinForms.BunifuShadowPanel.GradientModes.Vertical;
            this.pnlSombraBtn.Location = new System.Drawing.Point(279, 709);
            this.pnlSombraBtn.Name = "pnlSombraBtn";
            this.pnlSombraBtn.Padding = new System.Windows.Forms.Padding(1, 1, 3, 3);
            this.pnlSombraBtn.PanelColor = System.Drawing.Color.Transparent;
            this.pnlSombraBtn.PanelColor2 = System.Drawing.Color.Transparent;
            this.pnlSombraBtn.ShadowColor = System.Drawing.Color.FromArgb(((int)(((byte)(90)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.pnlSombraBtn.ShadowDept = 2;
            this.pnlSombraBtn.ShadowDepth = 5;
            this.pnlSombraBtn.ShadowStyle = Bunifu.UI.WinForms.BunifuShadowPanel.ShadowStyles.Surrounded;
            this.pnlSombraBtn.ShadowTopLeftVisible = false;
            this.pnlSombraBtn.Size = new System.Drawing.Size(163, 65);
            this.pnlSombraBtn.Style = Bunifu.UI.WinForms.BunifuShadowPanel.BevelStyles.Flat;
            this.pnlSombraBtn.TabIndex = 7;
            // 
            // btnVerificarPregunta
            // 
            this.btnVerificarPregunta.AllowAnimations = true;
            this.btnVerificarPregunta.AllowMouseEffects = true;
            this.btnVerificarPregunta.AllowToggling = false;
            this.btnVerificarPregunta.AnimationSpeed = 200;
            this.btnVerificarPregunta.AutoGenerateColors = false;
            this.btnVerificarPregunta.AutoRoundBorders = false;
            this.btnVerificarPregunta.AutoSizeLeftIcon = true;
            this.btnVerificarPregunta.AutoSizeRightIcon = true;
            this.btnVerificarPregunta.BackColor = System.Drawing.Color.Transparent;
            this.btnVerificarPregunta.BackColor1 = System.Drawing.Color.LightSeaGreen;
            this.btnVerificarPregunta.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnVerificarPregunta.BackgroundImage")));
            this.btnVerificarPregunta.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnVerificarPregunta.ButtonText = "Verificar";
            this.btnVerificarPregunta.ButtonTextMarginLeft = 0;
            this.btnVerificarPregunta.ColorContrastOnClick = 45;
            this.btnVerificarPregunta.ColorContrastOnHover = 45;
            this.btnVerificarPregunta.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.btnVerificarPregunta.CustomizableEdges = borderEdges3;
            this.btnVerificarPregunta.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnVerificarPregunta.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnVerificarPregunta.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnVerificarPregunta.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnVerificarPregunta.Dock = System.Windows.Forms.DockStyle.Fill;
            this.btnVerificarPregunta.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.btnVerificarPregunta.Font = new System.Drawing.Font("Century Gothic", 14.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnVerificarPregunta.ForeColor = System.Drawing.Color.White;
            this.btnVerificarPregunta.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnVerificarPregunta.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.btnVerificarPregunta.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnVerificarPregunta.IconMarginLeft = 11;
            this.btnVerificarPregunta.IconPadding = 10;
            this.btnVerificarPregunta.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnVerificarPregunta.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.btnVerificarPregunta.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnVerificarPregunta.IconSize = 25;
            this.btnVerificarPregunta.IdleBorderColor = System.Drawing.Color.Transparent;
            this.btnVerificarPregunta.IdleBorderRadius = 15;
            this.btnVerificarPregunta.IdleBorderThickness = 1;
            this.btnVerificarPregunta.IdleFillColor = System.Drawing.Color.LightSeaGreen;
            this.btnVerificarPregunta.IdleIconLeftImage = null;
            this.btnVerificarPregunta.IdleIconRightImage = null;
            this.btnVerificarPregunta.IndicateFocus = false;
            this.btnVerificarPregunta.Location = new System.Drawing.Point(1, 1);
            this.btnVerificarPregunta.Name = "btnVerificarPregunta";
            this.btnVerificarPregunta.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnVerificarPregunta.OnDisabledState.BorderRadius = 15;
            this.btnVerificarPregunta.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnVerificarPregunta.OnDisabledState.BorderThickness = 1;
            this.btnVerificarPregunta.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnVerificarPregunta.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnVerificarPregunta.OnDisabledState.IconLeftImage = null;
            this.btnVerificarPregunta.OnDisabledState.IconRightImage = null;
            this.btnVerificarPregunta.onHoverState.BorderColor = System.Drawing.Color.Transparent;
            this.btnVerificarPregunta.onHoverState.BorderRadius = 15;
            this.btnVerificarPregunta.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnVerificarPregunta.onHoverState.BorderThickness = 1;
            this.btnVerificarPregunta.onHoverState.FillColor = System.Drawing.Color.MediumTurquoise;
            this.btnVerificarPregunta.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnVerificarPregunta.onHoverState.IconLeftImage = null;
            this.btnVerificarPregunta.onHoverState.IconRightImage = null;
            this.btnVerificarPregunta.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.btnVerificarPregunta.OnIdleState.BorderRadius = 15;
            this.btnVerificarPregunta.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnVerificarPregunta.OnIdleState.BorderThickness = 1;
            this.btnVerificarPregunta.OnIdleState.FillColor = System.Drawing.Color.LightSeaGreen;
            this.btnVerificarPregunta.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnVerificarPregunta.OnIdleState.IconLeftImage = null;
            this.btnVerificarPregunta.OnIdleState.IconRightImage = null;
            this.btnVerificarPregunta.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(3)))), ((int)(((byte)(166)))), ((int)(((byte)(158)))));
            this.btnVerificarPregunta.OnPressedState.BorderRadius = 15;
            this.btnVerificarPregunta.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnVerificarPregunta.OnPressedState.BorderThickness = 1;
            this.btnVerificarPregunta.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(3)))), ((int)(((byte)(166)))), ((int)(((byte)(158)))));
            this.btnVerificarPregunta.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnVerificarPregunta.OnPressedState.IconLeftImage = null;
            this.btnVerificarPregunta.OnPressedState.IconRightImage = null;
            this.btnVerificarPregunta.Size = new System.Drawing.Size(159, 61);
            this.btnVerificarPregunta.TabIndex = 5;
            this.btnVerificarPregunta.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnVerificarPregunta.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnVerificarPregunta.TextMarginLeft = 0;
            this.btnVerificarPregunta.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnVerificarPregunta.UseDefaultRadiusAndThickness = true;
            // 
            // txtCuartaPregunta
            // 
            this.txtCuartaPregunta.AcceptsReturn = false;
            this.txtCuartaPregunta.AcceptsTab = false;
            this.txtCuartaPregunta.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.txtCuartaPregunta.AnimationSpeed = 200;
            this.txtCuartaPregunta.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtCuartaPregunta.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtCuartaPregunta.AutoSizeHeight = true;
            this.txtCuartaPregunta.BackColor = System.Drawing.Color.Transparent;
            this.txtCuartaPregunta.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtCuartaPregunta.BackgroundImage")));
            this.txtCuartaPregunta.BorderColorActive = System.Drawing.Color.CadetBlue;
            this.txtCuartaPregunta.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtCuartaPregunta.BorderColorHover = System.Drawing.Color.DarkTurquoise;
            this.txtCuartaPregunta.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtCuartaPregunta.BorderRadius = 15;
            this.txtCuartaPregunta.BorderThickness = 1;
            this.txtCuartaPregunta.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.txtCuartaPregunta.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtCuartaPregunta.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtCuartaPregunta.DefaultFont = new System.Drawing.Font("Century Gothic", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtCuartaPregunta.DefaultText = "";
            this.txtCuartaPregunta.FillColor = System.Drawing.Color.White;
            this.txtCuartaPregunta.HideSelection = true;
            this.txtCuartaPregunta.IconLeft = null;
            this.txtCuartaPregunta.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtCuartaPregunta.IconPadding = 10;
            this.txtCuartaPregunta.IconRight = null;
            this.txtCuartaPregunta.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtCuartaPregunta.Lines = new string[0];
            this.txtCuartaPregunta.Location = new System.Drawing.Point(60, 627);
            this.txtCuartaPregunta.MaxLength = 40;
            this.txtCuartaPregunta.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtCuartaPregunta.Modified = false;
            this.txtCuartaPregunta.Multiline = false;
            this.txtCuartaPregunta.Name = "txtCuartaPregunta";
            stateProperties25.BorderColor = System.Drawing.Color.CadetBlue;
            stateProperties25.FillColor = System.Drawing.Color.Empty;
            stateProperties25.ForeColor = System.Drawing.Color.Empty;
            stateProperties25.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtCuartaPregunta.OnActiveState = stateProperties25;
            stateProperties26.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties26.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties26.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties26.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtCuartaPregunta.OnDisabledState = stateProperties26;
            stateProperties27.BorderColor = System.Drawing.Color.DarkTurquoise;
            stateProperties27.FillColor = System.Drawing.Color.Empty;
            stateProperties27.ForeColor = System.Drawing.Color.Empty;
            stateProperties27.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtCuartaPregunta.OnHoverState = stateProperties27;
            stateProperties28.BorderColor = System.Drawing.Color.Silver;
            stateProperties28.FillColor = System.Drawing.Color.White;
            stateProperties28.ForeColor = System.Drawing.Color.Empty;
            stateProperties28.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtCuartaPregunta.OnIdleState = stateProperties28;
            this.txtCuartaPregunta.Padding = new System.Windows.Forms.Padding(3);
            this.txtCuartaPregunta.PasswordChar = '\0';
            this.txtCuartaPregunta.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtCuartaPregunta.PlaceholderText = "Ingresa la respuesta";
            this.txtCuartaPregunta.ReadOnly = false;
            this.txtCuartaPregunta.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtCuartaPregunta.SelectedText = "";
            this.txtCuartaPregunta.SelectionLength = 0;
            this.txtCuartaPregunta.SelectionStart = 0;
            this.txtCuartaPregunta.ShortcutsEnabled = false;
            this.txtCuartaPregunta.Size = new System.Drawing.Size(546, 50);
            this.txtCuartaPregunta.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtCuartaPregunta.TabIndex = 14;
            this.txtCuartaPregunta.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtCuartaPregunta.TextMarginBottom = 0;
            this.txtCuartaPregunta.TextMarginLeft = 3;
            this.txtCuartaPregunta.TextMarginTop = 1;
            this.txtCuartaPregunta.TextPlaceholder = "Ingresa la respuesta";
            this.txtCuartaPregunta.UseSystemPasswordChar = false;
            this.txtCuartaPregunta.WordWrap = true;
            // 
            // txtTerceraPregunta
            // 
            this.txtTerceraPregunta.AcceptsReturn = false;
            this.txtTerceraPregunta.AcceptsTab = false;
            this.txtTerceraPregunta.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.txtTerceraPregunta.AnimationSpeed = 200;
            this.txtTerceraPregunta.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtTerceraPregunta.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtTerceraPregunta.AutoSizeHeight = true;
            this.txtTerceraPregunta.BackColor = System.Drawing.Color.Transparent;
            this.txtTerceraPregunta.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtTerceraPregunta.BackgroundImage")));
            this.txtTerceraPregunta.BorderColorActive = System.Drawing.Color.CadetBlue;
            this.txtTerceraPregunta.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtTerceraPregunta.BorderColorHover = System.Drawing.Color.DarkTurquoise;
            this.txtTerceraPregunta.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtTerceraPregunta.BorderRadius = 15;
            this.txtTerceraPregunta.BorderThickness = 1;
            this.txtTerceraPregunta.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.txtTerceraPregunta.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtTerceraPregunta.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtTerceraPregunta.DefaultFont = new System.Drawing.Font("Century Gothic", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtTerceraPregunta.DefaultText = "";
            this.txtTerceraPregunta.FillColor = System.Drawing.Color.White;
            this.txtTerceraPregunta.HideSelection = true;
            this.txtTerceraPregunta.IconLeft = null;
            this.txtTerceraPregunta.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtTerceraPregunta.IconPadding = 10;
            this.txtTerceraPregunta.IconRight = null;
            this.txtTerceraPregunta.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtTerceraPregunta.Lines = new string[0];
            this.txtTerceraPregunta.Location = new System.Drawing.Point(60, 523);
            this.txtTerceraPregunta.MaxLength = 40;
            this.txtTerceraPregunta.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtTerceraPregunta.Modified = false;
            this.txtTerceraPregunta.Multiline = false;
            this.txtTerceraPregunta.Name = "txtTerceraPregunta";
            stateProperties29.BorderColor = System.Drawing.Color.CadetBlue;
            stateProperties29.FillColor = System.Drawing.Color.Empty;
            stateProperties29.ForeColor = System.Drawing.Color.Empty;
            stateProperties29.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtTerceraPregunta.OnActiveState = stateProperties29;
            stateProperties30.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties30.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties30.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties30.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtTerceraPregunta.OnDisabledState = stateProperties30;
            stateProperties31.BorderColor = System.Drawing.Color.DarkTurquoise;
            stateProperties31.FillColor = System.Drawing.Color.Empty;
            stateProperties31.ForeColor = System.Drawing.Color.Empty;
            stateProperties31.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtTerceraPregunta.OnHoverState = stateProperties31;
            stateProperties32.BorderColor = System.Drawing.Color.Silver;
            stateProperties32.FillColor = System.Drawing.Color.White;
            stateProperties32.ForeColor = System.Drawing.Color.Empty;
            stateProperties32.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtTerceraPregunta.OnIdleState = stateProperties32;
            this.txtTerceraPregunta.Padding = new System.Windows.Forms.Padding(3);
            this.txtTerceraPregunta.PasswordChar = '\0';
            this.txtTerceraPregunta.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtTerceraPregunta.PlaceholderText = "Ingresa la respuesta";
            this.txtTerceraPregunta.ReadOnly = false;
            this.txtTerceraPregunta.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtTerceraPregunta.SelectedText = "";
            this.txtTerceraPregunta.SelectionLength = 0;
            this.txtTerceraPregunta.SelectionStart = 0;
            this.txtTerceraPregunta.ShortcutsEnabled = false;
            this.txtTerceraPregunta.Size = new System.Drawing.Size(546, 50);
            this.txtTerceraPregunta.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtTerceraPregunta.TabIndex = 13;
            this.txtTerceraPregunta.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtTerceraPregunta.TextMarginBottom = 0;
            this.txtTerceraPregunta.TextMarginLeft = 3;
            this.txtTerceraPregunta.TextMarginTop = 1;
            this.txtTerceraPregunta.TextPlaceholder = "Ingresa la respuesta";
            this.txtTerceraPregunta.UseSystemPasswordChar = false;
            this.txtTerceraPregunta.WordWrap = true;
            // 
            // txtSegundaPregunta
            // 
            this.txtSegundaPregunta.AcceptsReturn = false;
            this.txtSegundaPregunta.AcceptsTab = false;
            this.txtSegundaPregunta.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.txtSegundaPregunta.AnimationSpeed = 200;
            this.txtSegundaPregunta.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtSegundaPregunta.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtSegundaPregunta.AutoSizeHeight = true;
            this.txtSegundaPregunta.BackColor = System.Drawing.Color.Transparent;
            this.txtSegundaPregunta.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtSegundaPregunta.BackgroundImage")));
            this.txtSegundaPregunta.BorderColorActive = System.Drawing.Color.CadetBlue;
            this.txtSegundaPregunta.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtSegundaPregunta.BorderColorHover = System.Drawing.Color.DarkTurquoise;
            this.txtSegundaPregunta.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtSegundaPregunta.BorderRadius = 15;
            this.txtSegundaPregunta.BorderThickness = 1;
            this.txtSegundaPregunta.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.txtSegundaPregunta.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtSegundaPregunta.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtSegundaPregunta.DefaultFont = new System.Drawing.Font("Century Gothic", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtSegundaPregunta.DefaultText = "";
            this.txtSegundaPregunta.FillColor = System.Drawing.Color.White;
            this.txtSegundaPregunta.HideSelection = true;
            this.txtSegundaPregunta.IconLeft = null;
            this.txtSegundaPregunta.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtSegundaPregunta.IconPadding = 10;
            this.txtSegundaPregunta.IconRight = null;
            this.txtSegundaPregunta.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtSegundaPregunta.Lines = new string[0];
            this.txtSegundaPregunta.Location = new System.Drawing.Point(60, 420);
            this.txtSegundaPregunta.MaxLength = 40;
            this.txtSegundaPregunta.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtSegundaPregunta.Modified = false;
            this.txtSegundaPregunta.Multiline = false;
            this.txtSegundaPregunta.Name = "txtSegundaPregunta";
            stateProperties33.BorderColor = System.Drawing.Color.CadetBlue;
            stateProperties33.FillColor = System.Drawing.Color.Empty;
            stateProperties33.ForeColor = System.Drawing.Color.Empty;
            stateProperties33.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtSegundaPregunta.OnActiveState = stateProperties33;
            stateProperties34.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties34.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties34.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties34.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtSegundaPregunta.OnDisabledState = stateProperties34;
            stateProperties35.BorderColor = System.Drawing.Color.DarkTurquoise;
            stateProperties35.FillColor = System.Drawing.Color.Empty;
            stateProperties35.ForeColor = System.Drawing.Color.Empty;
            stateProperties35.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtSegundaPregunta.OnHoverState = stateProperties35;
            stateProperties36.BorderColor = System.Drawing.Color.Silver;
            stateProperties36.FillColor = System.Drawing.Color.White;
            stateProperties36.ForeColor = System.Drawing.Color.Empty;
            stateProperties36.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtSegundaPregunta.OnIdleState = stateProperties36;
            this.txtSegundaPregunta.Padding = new System.Windows.Forms.Padding(3);
            this.txtSegundaPregunta.PasswordChar = '\0';
            this.txtSegundaPregunta.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtSegundaPregunta.PlaceholderText = "Ingresa la respuesta";
            this.txtSegundaPregunta.ReadOnly = false;
            this.txtSegundaPregunta.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtSegundaPregunta.SelectedText = "";
            this.txtSegundaPregunta.SelectionLength = 0;
            this.txtSegundaPregunta.SelectionStart = 0;
            this.txtSegundaPregunta.ShortcutsEnabled = false;
            this.txtSegundaPregunta.Size = new System.Drawing.Size(546, 50);
            this.txtSegundaPregunta.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtSegundaPregunta.TabIndex = 12;
            this.txtSegundaPregunta.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtSegundaPregunta.TextMarginBottom = 0;
            this.txtSegundaPregunta.TextMarginLeft = 3;
            this.txtSegundaPregunta.TextMarginTop = 1;
            this.txtSegundaPregunta.TextPlaceholder = "Ingresa la respuesta";
            this.txtSegundaPregunta.UseSystemPasswordChar = false;
            this.txtSegundaPregunta.WordWrap = true;
            // 
            // txtPrimeraPregunta
            // 
            this.txtPrimeraPregunta.AcceptsReturn = false;
            this.txtPrimeraPregunta.AcceptsTab = false;
            this.txtPrimeraPregunta.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.txtPrimeraPregunta.AnimationSpeed = 200;
            this.txtPrimeraPregunta.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtPrimeraPregunta.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtPrimeraPregunta.AutoSizeHeight = true;
            this.txtPrimeraPregunta.BackColor = System.Drawing.Color.Transparent;
            this.txtPrimeraPregunta.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtPrimeraPregunta.BackgroundImage")));
            this.txtPrimeraPregunta.BorderColorActive = System.Drawing.Color.CadetBlue;
            this.txtPrimeraPregunta.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtPrimeraPregunta.BorderColorHover = System.Drawing.Color.DarkTurquoise;
            this.txtPrimeraPregunta.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtPrimeraPregunta.BorderRadius = 15;
            this.txtPrimeraPregunta.BorderThickness = 1;
            this.txtPrimeraPregunta.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.txtPrimeraPregunta.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtPrimeraPregunta.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtPrimeraPregunta.DefaultFont = new System.Drawing.Font("Century Gothic", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtPrimeraPregunta.DefaultText = "";
            this.txtPrimeraPregunta.FillColor = System.Drawing.Color.White;
            this.txtPrimeraPregunta.HideSelection = true;
            this.txtPrimeraPregunta.IconLeft = null;
            this.txtPrimeraPregunta.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtPrimeraPregunta.IconPadding = 10;
            this.txtPrimeraPregunta.IconRight = null;
            this.txtPrimeraPregunta.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtPrimeraPregunta.Lines = new string[0];
            this.txtPrimeraPregunta.Location = new System.Drawing.Point(60, 316);
            this.txtPrimeraPregunta.MaxLength = 40;
            this.txtPrimeraPregunta.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtPrimeraPregunta.Modified = false;
            this.txtPrimeraPregunta.Multiline = false;
            this.txtPrimeraPregunta.Name = "txtPrimeraPregunta";
            stateProperties37.BorderColor = System.Drawing.Color.CadetBlue;
            stateProperties37.FillColor = System.Drawing.Color.Empty;
            stateProperties37.ForeColor = System.Drawing.Color.Empty;
            stateProperties37.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtPrimeraPregunta.OnActiveState = stateProperties37;
            stateProperties38.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties38.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties38.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties38.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtPrimeraPregunta.OnDisabledState = stateProperties38;
            stateProperties39.BorderColor = System.Drawing.Color.DarkTurquoise;
            stateProperties39.FillColor = System.Drawing.Color.Empty;
            stateProperties39.ForeColor = System.Drawing.Color.Empty;
            stateProperties39.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtPrimeraPregunta.OnHoverState = stateProperties39;
            stateProperties40.BorderColor = System.Drawing.Color.Silver;
            stateProperties40.FillColor = System.Drawing.Color.White;
            stateProperties40.ForeColor = System.Drawing.Color.Empty;
            stateProperties40.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtPrimeraPregunta.OnIdleState = stateProperties40;
            this.txtPrimeraPregunta.Padding = new System.Windows.Forms.Padding(3);
            this.txtPrimeraPregunta.PasswordChar = '\0';
            this.txtPrimeraPregunta.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtPrimeraPregunta.PlaceholderText = "Ingresa la respuesta";
            this.txtPrimeraPregunta.ReadOnly = false;
            this.txtPrimeraPregunta.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtPrimeraPregunta.SelectedText = "";
            this.txtPrimeraPregunta.SelectionLength = 0;
            this.txtPrimeraPregunta.SelectionStart = 0;
            this.txtPrimeraPregunta.ShortcutsEnabled = false;
            this.txtPrimeraPregunta.Size = new System.Drawing.Size(546, 50);
            this.txtPrimeraPregunta.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtPrimeraPregunta.TabIndex = 11;
            this.txtPrimeraPregunta.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtPrimeraPregunta.TextMarginBottom = 0;
            this.txtPrimeraPregunta.TextMarginLeft = 3;
            this.txtPrimeraPregunta.TextMarginTop = 1;
            this.txtPrimeraPregunta.TextPlaceholder = "Ingresa la respuesta";
            this.txtPrimeraPregunta.UseSystemPasswordChar = false;
            this.txtPrimeraPregunta.WordWrap = true;
            // 
            // cmbCuartaPregunta
            // 
            this.cmbCuartaPregunta.BackColor = System.Drawing.Color.Transparent;
            this.cmbCuartaPregunta.BackgroundColor = System.Drawing.Color.White;
            this.cmbCuartaPregunta.BorderColor = System.Drawing.Color.Silver;
            this.cmbCuartaPregunta.BorderRadius = 5;
            this.cmbCuartaPregunta.Color = System.Drawing.Color.Silver;
            this.cmbCuartaPregunta.Direction = Bunifu.UI.WinForms.BunifuDropdown.Directions.Down;
            this.cmbCuartaPregunta.DisabledBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            this.cmbCuartaPregunta.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.cmbCuartaPregunta.DisabledColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            this.cmbCuartaPregunta.DisabledForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            this.cmbCuartaPregunta.DisabledIndicatorColor = System.Drawing.Color.DarkGray;
            this.cmbCuartaPregunta.DrawMode = System.Windows.Forms.DrawMode.OwnerDrawFixed;
            this.cmbCuartaPregunta.DropdownBorderThickness = Bunifu.UI.WinForms.BunifuDropdown.BorderThickness.Thin;
            this.cmbCuartaPregunta.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cmbCuartaPregunta.DropDownTextAlign = Bunifu.UI.WinForms.BunifuDropdown.TextAlign.Left;
            this.cmbCuartaPregunta.FillDropDown = true;
            this.cmbCuartaPregunta.FillIndicator = false;
            this.cmbCuartaPregunta.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.cmbCuartaPregunta.Font = new System.Drawing.Font("Century Gothic", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.cmbCuartaPregunta.ForeColor = System.Drawing.Color.Black;
            this.cmbCuartaPregunta.FormattingEnabled = true;
            this.cmbCuartaPregunta.Icon = null;
            this.cmbCuartaPregunta.IndicatorAlignment = Bunifu.UI.WinForms.BunifuDropdown.Indicator.Right;
            this.cmbCuartaPregunta.IndicatorColor = System.Drawing.Color.Teal;
            this.cmbCuartaPregunta.IndicatorLocation = Bunifu.UI.WinForms.BunifuDropdown.Indicator.Right;
            this.cmbCuartaPregunta.IndicatorThickness = 2;
            this.cmbCuartaPregunta.IsDropdownOpened = false;
            this.cmbCuartaPregunta.ItemBackColor = System.Drawing.Color.White;
            this.cmbCuartaPregunta.ItemBorderColor = System.Drawing.Color.White;
            this.cmbCuartaPregunta.ItemForeColor = System.Drawing.Color.Black;
            this.cmbCuartaPregunta.ItemHeight = 26;
            this.cmbCuartaPregunta.ItemHighLightColor = System.Drawing.Color.DarkTurquoise;
            this.cmbCuartaPregunta.ItemHighLightForeColor = System.Drawing.Color.White;
            this.cmbCuartaPregunta.ItemTopMargin = 3;
            this.cmbCuartaPregunta.Location = new System.Drawing.Point(60, 589);
            this.cmbCuartaPregunta.Name = "cmbCuartaPregunta";
            this.cmbCuartaPregunta.Size = new System.Drawing.Size(545, 32);
            this.cmbCuartaPregunta.TabIndex = 10;
            this.cmbCuartaPregunta.Text = null;
            this.cmbCuartaPregunta.TextAlignment = Bunifu.UI.WinForms.BunifuDropdown.TextAlign.Left;
            this.cmbCuartaPregunta.TextLeftMargin = 5;
            // 
            // cmbTerceraPregunta
            // 
            this.cmbTerceraPregunta.BackColor = System.Drawing.Color.Transparent;
            this.cmbTerceraPregunta.BackgroundColor = System.Drawing.Color.White;
            this.cmbTerceraPregunta.BorderColor = System.Drawing.Color.Silver;
            this.cmbTerceraPregunta.BorderRadius = 5;
            this.cmbTerceraPregunta.Color = System.Drawing.Color.Silver;
            this.cmbTerceraPregunta.Direction = Bunifu.UI.WinForms.BunifuDropdown.Directions.Down;
            this.cmbTerceraPregunta.DisabledBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            this.cmbTerceraPregunta.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.cmbTerceraPregunta.DisabledColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            this.cmbTerceraPregunta.DisabledForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            this.cmbTerceraPregunta.DisabledIndicatorColor = System.Drawing.Color.DarkGray;
            this.cmbTerceraPregunta.DrawMode = System.Windows.Forms.DrawMode.OwnerDrawFixed;
            this.cmbTerceraPregunta.DropdownBorderThickness = Bunifu.UI.WinForms.BunifuDropdown.BorderThickness.Thin;
            this.cmbTerceraPregunta.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cmbTerceraPregunta.DropDownTextAlign = Bunifu.UI.WinForms.BunifuDropdown.TextAlign.Left;
            this.cmbTerceraPregunta.FillDropDown = true;
            this.cmbTerceraPregunta.FillIndicator = false;
            this.cmbTerceraPregunta.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.cmbTerceraPregunta.Font = new System.Drawing.Font("Century Gothic", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.cmbTerceraPregunta.ForeColor = System.Drawing.Color.Black;
            this.cmbTerceraPregunta.FormattingEnabled = true;
            this.cmbTerceraPregunta.Icon = null;
            this.cmbTerceraPregunta.IndicatorAlignment = Bunifu.UI.WinForms.BunifuDropdown.Indicator.Right;
            this.cmbTerceraPregunta.IndicatorColor = System.Drawing.Color.Teal;
            this.cmbTerceraPregunta.IndicatorLocation = Bunifu.UI.WinForms.BunifuDropdown.Indicator.Right;
            this.cmbTerceraPregunta.IndicatorThickness = 2;
            this.cmbTerceraPregunta.IsDropdownOpened = false;
            this.cmbTerceraPregunta.ItemBackColor = System.Drawing.Color.White;
            this.cmbTerceraPregunta.ItemBorderColor = System.Drawing.Color.White;
            this.cmbTerceraPregunta.ItemForeColor = System.Drawing.Color.Black;
            this.cmbTerceraPregunta.ItemHeight = 26;
            this.cmbTerceraPregunta.ItemHighLightColor = System.Drawing.Color.DarkTurquoise;
            this.cmbTerceraPregunta.ItemHighLightForeColor = System.Drawing.Color.White;
            this.cmbTerceraPregunta.ItemTopMargin = 3;
            this.cmbTerceraPregunta.Location = new System.Drawing.Point(60, 485);
            this.cmbTerceraPregunta.Name = "cmbTerceraPregunta";
            this.cmbTerceraPregunta.Size = new System.Drawing.Size(545, 32);
            this.cmbTerceraPregunta.TabIndex = 9;
            this.cmbTerceraPregunta.Text = null;
            this.cmbTerceraPregunta.TextAlignment = Bunifu.UI.WinForms.BunifuDropdown.TextAlign.Left;
            this.cmbTerceraPregunta.TextLeftMargin = 5;
            // 
            // cmbSegundaPregunta
            // 
            this.cmbSegundaPregunta.BackColor = System.Drawing.Color.Transparent;
            this.cmbSegundaPregunta.BackgroundColor = System.Drawing.Color.White;
            this.cmbSegundaPregunta.BorderColor = System.Drawing.Color.Silver;
            this.cmbSegundaPregunta.BorderRadius = 5;
            this.cmbSegundaPregunta.Color = System.Drawing.Color.Silver;
            this.cmbSegundaPregunta.Direction = Bunifu.UI.WinForms.BunifuDropdown.Directions.Down;
            this.cmbSegundaPregunta.DisabledBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            this.cmbSegundaPregunta.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.cmbSegundaPregunta.DisabledColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            this.cmbSegundaPregunta.DisabledForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            this.cmbSegundaPregunta.DisabledIndicatorColor = System.Drawing.Color.DarkGray;
            this.cmbSegundaPregunta.DrawMode = System.Windows.Forms.DrawMode.OwnerDrawFixed;
            this.cmbSegundaPregunta.DropdownBorderThickness = Bunifu.UI.WinForms.BunifuDropdown.BorderThickness.Thin;
            this.cmbSegundaPregunta.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cmbSegundaPregunta.DropDownTextAlign = Bunifu.UI.WinForms.BunifuDropdown.TextAlign.Left;
            this.cmbSegundaPregunta.FillDropDown = true;
            this.cmbSegundaPregunta.FillIndicator = false;
            this.cmbSegundaPregunta.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.cmbSegundaPregunta.Font = new System.Drawing.Font("Century Gothic", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.cmbSegundaPregunta.ForeColor = System.Drawing.Color.Black;
            this.cmbSegundaPregunta.FormattingEnabled = true;
            this.cmbSegundaPregunta.Icon = null;
            this.cmbSegundaPregunta.IndicatorAlignment = Bunifu.UI.WinForms.BunifuDropdown.Indicator.Right;
            this.cmbSegundaPregunta.IndicatorColor = System.Drawing.Color.Teal;
            this.cmbSegundaPregunta.IndicatorLocation = Bunifu.UI.WinForms.BunifuDropdown.Indicator.Right;
            this.cmbSegundaPregunta.IndicatorThickness = 2;
            this.cmbSegundaPregunta.IsDropdownOpened = false;
            this.cmbSegundaPregunta.ItemBackColor = System.Drawing.Color.White;
            this.cmbSegundaPregunta.ItemBorderColor = System.Drawing.Color.White;
            this.cmbSegundaPregunta.ItemForeColor = System.Drawing.Color.Black;
            this.cmbSegundaPregunta.ItemHeight = 26;
            this.cmbSegundaPregunta.ItemHighLightColor = System.Drawing.Color.DarkTurquoise;
            this.cmbSegundaPregunta.ItemHighLightForeColor = System.Drawing.Color.White;
            this.cmbSegundaPregunta.ItemTopMargin = 3;
            this.cmbSegundaPregunta.Location = new System.Drawing.Point(60, 382);
            this.cmbSegundaPregunta.Name = "cmbSegundaPregunta";
            this.cmbSegundaPregunta.Size = new System.Drawing.Size(545, 32);
            this.cmbSegundaPregunta.TabIndex = 8;
            this.cmbSegundaPregunta.Text = null;
            this.cmbSegundaPregunta.TextAlignment = Bunifu.UI.WinForms.BunifuDropdown.TextAlign.Left;
            this.cmbSegundaPregunta.TextLeftMargin = 5;
            // 
            // cmbPrimeraPregunta
            // 
            this.cmbPrimeraPregunta.BackColor = System.Drawing.Color.Transparent;
            this.cmbPrimeraPregunta.BackgroundColor = System.Drawing.Color.White;
            this.cmbPrimeraPregunta.BorderColor = System.Drawing.Color.Silver;
            this.cmbPrimeraPregunta.BorderRadius = 5;
            this.cmbPrimeraPregunta.Color = System.Drawing.Color.Silver;
            this.cmbPrimeraPregunta.Direction = Bunifu.UI.WinForms.BunifuDropdown.Directions.Down;
            this.cmbPrimeraPregunta.DisabledBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            this.cmbPrimeraPregunta.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.cmbPrimeraPregunta.DisabledColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            this.cmbPrimeraPregunta.DisabledForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            this.cmbPrimeraPregunta.DisabledIndicatorColor = System.Drawing.Color.DarkGray;
            this.cmbPrimeraPregunta.DrawMode = System.Windows.Forms.DrawMode.OwnerDrawFixed;
            this.cmbPrimeraPregunta.DropdownBorderThickness = Bunifu.UI.WinForms.BunifuDropdown.BorderThickness.Thin;
            this.cmbPrimeraPregunta.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cmbPrimeraPregunta.DropDownTextAlign = Bunifu.UI.WinForms.BunifuDropdown.TextAlign.Left;
            this.cmbPrimeraPregunta.FillDropDown = true;
            this.cmbPrimeraPregunta.FillIndicator = false;
            this.cmbPrimeraPregunta.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.cmbPrimeraPregunta.Font = new System.Drawing.Font("Century Gothic", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.cmbPrimeraPregunta.ForeColor = System.Drawing.Color.Black;
            this.cmbPrimeraPregunta.FormattingEnabled = true;
            this.cmbPrimeraPregunta.Icon = null;
            this.cmbPrimeraPregunta.IndicatorAlignment = Bunifu.UI.WinForms.BunifuDropdown.Indicator.Right;
            this.cmbPrimeraPregunta.IndicatorColor = System.Drawing.Color.Teal;
            this.cmbPrimeraPregunta.IndicatorLocation = Bunifu.UI.WinForms.BunifuDropdown.Indicator.Right;
            this.cmbPrimeraPregunta.IndicatorThickness = 2;
            this.cmbPrimeraPregunta.IsDropdownOpened = false;
            this.cmbPrimeraPregunta.ItemBackColor = System.Drawing.Color.White;
            this.cmbPrimeraPregunta.ItemBorderColor = System.Drawing.Color.White;
            this.cmbPrimeraPregunta.ItemForeColor = System.Drawing.Color.Black;
            this.cmbPrimeraPregunta.ItemHeight = 26;
            this.cmbPrimeraPregunta.ItemHighLightColor = System.Drawing.Color.DarkTurquoise;
            this.cmbPrimeraPregunta.ItemHighLightForeColor = System.Drawing.Color.White;
            this.cmbPrimeraPregunta.ItemTopMargin = 3;
            this.cmbPrimeraPregunta.Location = new System.Drawing.Point(60, 278);
            this.cmbPrimeraPregunta.Name = "cmbPrimeraPregunta";
            this.cmbPrimeraPregunta.Size = new System.Drawing.Size(545, 32);
            this.cmbPrimeraPregunta.TabIndex = 7;
            this.cmbPrimeraPregunta.Text = null;
            this.cmbPrimeraPregunta.TextAlignment = Bunifu.UI.WinForms.BunifuDropdown.TextAlign.Left;
            this.cmbPrimeraPregunta.TextLeftMargin = 5;
            // 
            // pnlSombraBoton
            // 
            this.pnlSombraBoton.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right)));
            this.pnlSombraBoton.BackColor = System.Drawing.Color.Transparent;
            this.pnlSombraBoton.BorderColor = System.Drawing.Color.Transparent;
            this.pnlSombraBoton.BorderRadius = 10;
            this.pnlSombraBoton.BorderThickness = 1;
            this.pnlSombraBoton.Controls.Add(this.btnComprobar);
            this.pnlSombraBoton.FillStyle = Bunifu.UI.WinForms.BunifuShadowPanel.FillStyles.Solid;
            this.pnlSombraBoton.GradientMode = Bunifu.UI.WinForms.BunifuShadowPanel.GradientModes.Vertical;
            this.pnlSombraBoton.Location = new System.Drawing.Point(448, 708);
            this.pnlSombraBoton.Name = "pnlSombraBoton";
            this.pnlSombraBoton.Padding = new System.Windows.Forms.Padding(1, 1, 3, 3);
            this.pnlSombraBoton.PanelColor = System.Drawing.Color.Transparent;
            this.pnlSombraBoton.PanelColor2 = System.Drawing.Color.Transparent;
            this.pnlSombraBoton.ShadowColor = System.Drawing.Color.FromArgb(((int)(((byte)(90)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.pnlSombraBoton.ShadowDept = 2;
            this.pnlSombraBoton.ShadowDepth = 5;
            this.pnlSombraBoton.ShadowStyle = Bunifu.UI.WinForms.BunifuShadowPanel.ShadowStyles.Surrounded;
            this.pnlSombraBoton.ShadowTopLeftVisible = false;
            this.pnlSombraBoton.Size = new System.Drawing.Size(163, 65);
            this.pnlSombraBoton.Style = Bunifu.UI.WinForms.BunifuShadowPanel.BevelStyles.Flat;
            this.pnlSombraBoton.TabIndex = 6;
            // 
            // btnComprobar
            // 
            this.btnComprobar.AllowAnimations = true;
            this.btnComprobar.AllowMouseEffects = true;
            this.btnComprobar.AllowToggling = false;
            this.btnComprobar.AnimationSpeed = 200;
            this.btnComprobar.AutoGenerateColors = false;
            this.btnComprobar.AutoRoundBorders = false;
            this.btnComprobar.AutoSizeLeftIcon = true;
            this.btnComprobar.AutoSizeRightIcon = true;
            this.btnComprobar.BackColor = System.Drawing.Color.Transparent;
            this.btnComprobar.BackColor1 = System.Drawing.Color.LightSeaGreen;
            this.btnComprobar.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnComprobar.BackgroundImage")));
            this.btnComprobar.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnComprobar.ButtonText = "Registrar";
            this.btnComprobar.ButtonTextMarginLeft = 0;
            this.btnComprobar.ColorContrastOnClick = 45;
            this.btnComprobar.ColorContrastOnHover = 45;
            this.btnComprobar.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            this.btnComprobar.CustomizableEdges = borderEdges4;
            this.btnComprobar.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnComprobar.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnComprobar.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnComprobar.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnComprobar.Dock = System.Windows.Forms.DockStyle.Fill;
            this.btnComprobar.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.btnComprobar.Font = new System.Drawing.Font("Century Gothic", 14.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnComprobar.ForeColor = System.Drawing.Color.White;
            this.btnComprobar.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnComprobar.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.btnComprobar.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnComprobar.IconMarginLeft = 11;
            this.btnComprobar.IconPadding = 10;
            this.btnComprobar.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnComprobar.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.btnComprobar.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnComprobar.IconSize = 25;
            this.btnComprobar.IdleBorderColor = System.Drawing.Color.Transparent;
            this.btnComprobar.IdleBorderRadius = 15;
            this.btnComprobar.IdleBorderThickness = 1;
            this.btnComprobar.IdleFillColor = System.Drawing.Color.LightSeaGreen;
            this.btnComprobar.IdleIconLeftImage = null;
            this.btnComprobar.IdleIconRightImage = null;
            this.btnComprobar.IndicateFocus = false;
            this.btnComprobar.Location = new System.Drawing.Point(1, 1);
            this.btnComprobar.Name = "btnComprobar";
            this.btnComprobar.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnComprobar.OnDisabledState.BorderRadius = 15;
            this.btnComprobar.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnComprobar.OnDisabledState.BorderThickness = 1;
            this.btnComprobar.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnComprobar.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnComprobar.OnDisabledState.IconLeftImage = null;
            this.btnComprobar.OnDisabledState.IconRightImage = null;
            this.btnComprobar.onHoverState.BorderColor = System.Drawing.Color.Transparent;
            this.btnComprobar.onHoverState.BorderRadius = 15;
            this.btnComprobar.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnComprobar.onHoverState.BorderThickness = 1;
            this.btnComprobar.onHoverState.FillColor = System.Drawing.Color.MediumTurquoise;
            this.btnComprobar.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnComprobar.onHoverState.IconLeftImage = null;
            this.btnComprobar.onHoverState.IconRightImage = null;
            this.btnComprobar.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.btnComprobar.OnIdleState.BorderRadius = 15;
            this.btnComprobar.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnComprobar.OnIdleState.BorderThickness = 1;
            this.btnComprobar.OnIdleState.FillColor = System.Drawing.Color.LightSeaGreen;
            this.btnComprobar.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnComprobar.OnIdleState.IconLeftImage = null;
            this.btnComprobar.OnIdleState.IconRightImage = null;
            this.btnComprobar.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(3)))), ((int)(((byte)(166)))), ((int)(((byte)(158)))));
            this.btnComprobar.OnPressedState.BorderRadius = 15;
            this.btnComprobar.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnComprobar.OnPressedState.BorderThickness = 1;
            this.btnComprobar.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(3)))), ((int)(((byte)(166)))), ((int)(((byte)(158)))));
            this.btnComprobar.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnComprobar.OnPressedState.IconLeftImage = null;
            this.btnComprobar.OnPressedState.IconRightImage = null;
            this.btnComprobar.Size = new System.Drawing.Size(159, 61);
            this.btnComprobar.TabIndex = 5;
            this.btnComprobar.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnComprobar.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnComprobar.TextMarginLeft = 0;
            this.btnComprobar.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnComprobar.UseDefaultRadiusAndThickness = true;
            // 
            // lblTitulo
            // 
            this.lblTitulo.AllowParentOverrides = false;
            this.lblTitulo.AutoEllipsis = false;
            this.lblTitulo.Cursor = System.Windows.Forms.Cursors.Default;
            this.lblTitulo.CursorType = System.Windows.Forms.Cursors.Default;
            this.lblTitulo.Font = new System.Drawing.Font("Century Gothic", 18F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblTitulo.ForeColor = System.Drawing.Color.Black;
            this.lblTitulo.Location = new System.Drawing.Point(48, 54);
            this.lblTitulo.Name = "lblTitulo";
            this.lblTitulo.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.lblTitulo.Size = new System.Drawing.Size(278, 28);
            this.lblTitulo.TabIndex = 0;
            this.lblTitulo.Text = "Preguntas de Seguridad";
            this.lblTitulo.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.lblTitulo.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // txtUsuario
            // 
            this.txtUsuario.AcceptsReturn = false;
            this.txtUsuario.AcceptsTab = false;
            this.txtUsuario.AnimationSpeed = 200;
            this.txtUsuario.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtUsuario.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtUsuario.AutoSizeHeight = true;
            this.txtUsuario.BackColor = System.Drawing.Color.Transparent;
            this.txtUsuario.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtUsuario.BackgroundImage")));
            this.txtUsuario.BorderColorActive = System.Drawing.Color.CadetBlue;
            this.txtUsuario.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtUsuario.BorderColorHover = System.Drawing.Color.DarkTurquoise;
            this.txtUsuario.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtUsuario.BorderRadius = 15;
            this.txtUsuario.BorderThickness = 1;
            this.txtUsuario.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.txtUsuario.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtUsuario.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtUsuario.DefaultFont = new System.Drawing.Font("Century Gothic", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtUsuario.DefaultText = "";
            this.txtUsuario.FillColor = System.Drawing.Color.White;
            this.txtUsuario.HideSelection = true;
            this.txtUsuario.IconLeft = null;
            this.txtUsuario.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtUsuario.IconPadding = 10;
            this.txtUsuario.IconRight = null;
            this.txtUsuario.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtUsuario.Lines = new string[0];
            this.txtUsuario.Location = new System.Drawing.Point(60, 165);
            this.txtUsuario.MaxLength = 40;
            this.txtUsuario.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtUsuario.Modified = false;
            this.txtUsuario.Multiline = false;
            this.txtUsuario.Name = "txtUsuario";
            stateProperties41.BorderColor = System.Drawing.Color.CadetBlue;
            stateProperties41.FillColor = System.Drawing.Color.Empty;
            stateProperties41.ForeColor = System.Drawing.Color.Empty;
            stateProperties41.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtUsuario.OnActiveState = stateProperties41;
            stateProperties42.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties42.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties42.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties42.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtUsuario.OnDisabledState = stateProperties42;
            stateProperties43.BorderColor = System.Drawing.Color.DarkTurquoise;
            stateProperties43.FillColor = System.Drawing.Color.Empty;
            stateProperties43.ForeColor = System.Drawing.Color.Empty;
            stateProperties43.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtUsuario.OnHoverState = stateProperties43;
            stateProperties44.BorderColor = System.Drawing.Color.Silver;
            stateProperties44.FillColor = System.Drawing.Color.White;
            stateProperties44.ForeColor = System.Drawing.Color.Empty;
            stateProperties44.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtUsuario.OnIdleState = stateProperties44;
            this.txtUsuario.Padding = new System.Windows.Forms.Padding(3);
            this.txtUsuario.PasswordChar = '\0';
            this.txtUsuario.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtUsuario.PlaceholderText = "Usuario";
            this.txtUsuario.ReadOnly = false;
            this.txtUsuario.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtUsuario.SelectedText = "";
            this.txtUsuario.SelectionLength = 0;
            this.txtUsuario.SelectionStart = 0;
            this.txtUsuario.ShortcutsEnabled = false;
            this.txtUsuario.Size = new System.Drawing.Size(271, 47);
            this.txtUsuario.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtUsuario.TabIndex = 15;
            this.txtUsuario.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtUsuario.TextMarginBottom = 0;
            this.txtUsuario.TextMarginLeft = 3;
            this.txtUsuario.TextMarginTop = 1;
            this.txtUsuario.TextPlaceholder = "Usuario";
            this.txtUsuario.UseSystemPasswordChar = false;
            this.txtUsuario.WordWrap = true;
            // 
            // txtDocumento
            // 
            this.txtDocumento.AcceptsReturn = false;
            this.txtDocumento.AcceptsTab = false;
            this.txtDocumento.AnimationSpeed = 200;
            this.txtDocumento.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtDocumento.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtDocumento.AutoSizeHeight = true;
            this.txtDocumento.BackColor = System.Drawing.Color.Transparent;
            this.txtDocumento.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtDocumento.BackgroundImage")));
            this.txtDocumento.BorderColorActive = System.Drawing.Color.CadetBlue;
            this.txtDocumento.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtDocumento.BorderColorHover = System.Drawing.Color.DarkTurquoise;
            this.txtDocumento.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtDocumento.BorderRadius = 15;
            this.txtDocumento.BorderThickness = 1;
            this.txtDocumento.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.txtDocumento.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtDocumento.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtDocumento.DefaultFont = new System.Drawing.Font("Century Gothic", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtDocumento.DefaultText = "";
            this.txtDocumento.FillColor = System.Drawing.Color.White;
            this.txtDocumento.HideSelection = true;
            this.txtDocumento.IconLeft = null;
            this.txtDocumento.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtDocumento.IconPadding = 10;
            this.txtDocumento.IconRight = null;
            this.txtDocumento.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtDocumento.Lines = new string[0];
            this.txtDocumento.Location = new System.Drawing.Point(337, 165);
            this.txtDocumento.MaxLength = 40;
            this.txtDocumento.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtDocumento.Modified = false;
            this.txtDocumento.Multiline = false;
            this.txtDocumento.Name = "txtDocumento";
            stateProperties45.BorderColor = System.Drawing.Color.CadetBlue;
            stateProperties45.FillColor = System.Drawing.Color.Empty;
            stateProperties45.ForeColor = System.Drawing.Color.Empty;
            stateProperties45.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtDocumento.OnActiveState = stateProperties45;
            stateProperties46.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties46.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties46.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties46.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtDocumento.OnDisabledState = stateProperties46;
            stateProperties47.BorderColor = System.Drawing.Color.DarkTurquoise;
            stateProperties47.FillColor = System.Drawing.Color.Empty;
            stateProperties47.ForeColor = System.Drawing.Color.Empty;
            stateProperties47.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtDocumento.OnHoverState = stateProperties47;
            stateProperties48.BorderColor = System.Drawing.Color.Silver;
            stateProperties48.FillColor = System.Drawing.Color.White;
            stateProperties48.ForeColor = System.Drawing.Color.Empty;
            stateProperties48.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtDocumento.OnIdleState = stateProperties48;
            this.txtDocumento.Padding = new System.Windows.Forms.Padding(3);
            this.txtDocumento.PasswordChar = '\0';
            this.txtDocumento.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtDocumento.PlaceholderText = "Documento";
            this.txtDocumento.ReadOnly = false;
            this.txtDocumento.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtDocumento.SelectedText = "";
            this.txtDocumento.SelectionLength = 0;
            this.txtDocumento.SelectionStart = 0;
            this.txtDocumento.ShortcutsEnabled = false;
            this.txtDocumento.Size = new System.Drawing.Size(271, 47);
            this.txtDocumento.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtDocumento.TabIndex = 16;
            this.txtDocumento.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtDocumento.TextMarginBottom = 0;
            this.txtDocumento.TextMarginLeft = 3;
            this.txtDocumento.TextMarginTop = 1;
            this.txtDocumento.TextPlaceholder = "Documento";
            this.txtDocumento.UseSystemPasswordChar = false;
            this.txtDocumento.WordWrap = true;
            // 
            // pnlLineaDivisora
            // 
            this.pnlLineaDivisora.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.pnlLineaDivisora.BackgroundColor = System.Drawing.Color.LightSeaGreen;
            this.pnlLineaDivisora.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("pnlLineaDivisora.BackgroundImage")));
            this.pnlLineaDivisora.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.pnlLineaDivisora.BorderColor = System.Drawing.Color.Transparent;
            this.pnlLineaDivisora.BorderRadius = 3;
            this.pnlLineaDivisora.BorderThickness = 1;
            this.pnlLineaDivisora.Location = new System.Drawing.Point(60, 224);
            this.pnlLineaDivisora.Name = "pnlLineaDivisora";
            this.pnlLineaDivisora.ShowBorders = true;
            this.pnlLineaDivisora.Size = new System.Drawing.Size(549, 4);
            this.pnlLineaDivisora.TabIndex = 17;
            // 
            // lblIndicacion
            // 
            this.lblIndicacion.AllowParentOverrides = false;
            this.lblIndicacion.AutoEllipsis = false;
            this.lblIndicacion.CursorType = System.Windows.Forms.Cursors.Default;
            this.lblIndicacion.Font = new System.Drawing.Font("Century Gothic", 14.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblIndicacion.Location = new System.Drawing.Point(51, 241);
            this.lblIndicacion.Name = "lblIndicacion";
            this.lblIndicacion.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.lblIndicacion.Size = new System.Drawing.Size(341, 23);
            this.lblIndicacion.TabIndex = 18;
            this.lblIndicacion.Text = "Seleccione las preguntas y responda";
            this.lblIndicacion.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.lblIndicacion.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // lblIngreseCredenciales
            // 
            this.lblIngreseCredenciales.AllowParentOverrides = false;
            this.lblIngreseCredenciales.AutoEllipsis = false;
            this.lblIngreseCredenciales.CursorType = null;
            this.lblIngreseCredenciales.Font = new System.Drawing.Font("Century Gothic", 14.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblIngreseCredenciales.Location = new System.Drawing.Point(51, 126);
            this.lblIngreseCredenciales.Name = "lblIngreseCredenciales";
            this.lblIngreseCredenciales.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.lblIngreseCredenciales.Size = new System.Drawing.Size(320, 23);
            this.lblIngreseCredenciales.TabIndex = 19;
            this.lblIngreseCredenciales.Text = "Ingrese las siguientes credenciales";
            this.lblIngreseCredenciales.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.lblIngreseCredenciales.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // PreguntasdeSeguridadForm
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(715, 874);
            this.Controls.Add(this.pnlGradiente);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.MaximumSize = new System.Drawing.Size(715, 874);
            this.MinimumSize = new System.Drawing.Size(715, 874);
            this.Name = "PreguntasdeSeguridadForm";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "Preguntas de Seguridad";
            this.pnlGradiente.ResumeLayout(false);
            this.pnlSombraFondo.ResumeLayout(false);
            this.pnlSombraFondo.PerformLayout();
            this.pnlSombraBtn.ResumeLayout(false);
            this.pnlSombraBoton.ResumeLayout(false);
            this.ResumeLayout(false);

        }

        #endregion

        public Bunifu.UI.WinForms.BunifuGradientPanel pnlGradiente;
        public Bunifu.UI.WinForms.BunifuShadowPanel pnlSombraFondo;
        public Bunifu.UI.WinForms.BunifuTextBox txtCuartaPregunta;
        public Bunifu.UI.WinForms.BunifuTextBox txtTerceraPregunta;
        public Bunifu.UI.WinForms.BunifuTextBox txtSegundaPregunta;
        public Bunifu.UI.WinForms.BunifuTextBox txtPrimeraPregunta;
        public Bunifu.UI.WinForms.BunifuDropdown cmbCuartaPregunta;
        public Bunifu.UI.WinForms.BunifuDropdown cmbTerceraPregunta;
        public Bunifu.UI.WinForms.BunifuDropdown cmbSegundaPregunta;
        public Bunifu.UI.WinForms.BunifuDropdown cmbPrimeraPregunta;
        public Bunifu.UI.WinForms.BunifuShadowPanel pnlSombraBoton;
        public Bunifu.UI.WinForms.BunifuButton.BunifuButton2 btnComprobar;
        public Bunifu.UI.WinForms.BunifuLabel lblTitulo;
        public Bunifu.UI.WinForms.BunifuShadowPanel pnlSombraBtn;
        public Bunifu.UI.WinForms.BunifuButton.BunifuButton2 btnVerificarPregunta;
        public Bunifu.UI.WinForms.BunifuTextBox txtDocumento;
        public Bunifu.UI.WinForms.BunifuTextBox txtUsuario;
        public Bunifu.UI.WinForms.BunifuPanel pnlLineaDivisora;
        public Bunifu.UI.WinForms.BunifuLabel lblIndicacion;
        public Bunifu.UI.WinForms.BunifuLabel lblIngreseCredenciales;
    }
}