namespace Empresa_laboral_ADNE___Proyecto_PTC.Vista
{
    partial class PreguntasdeSeguridadForm
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(PreguntasdeSeguridadForm));
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties13 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties14 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties15 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties16 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            this.pnlGradiente = new Bunifu.UI.WinForms.BunifuGradientPanel();
            this.pnlSombraFondo = new Bunifu.UI.WinForms.BunifuShadowPanel();
            this.txtCuartaPregunta = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtTerceraPregunta = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtSegundaPregunta = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtPrimeraPregunta = new Bunifu.UI.WinForms.BunifuTextBox();
            this.cmbCuartaPregunta = new Bunifu.UI.WinForms.BunifuDropdown();
            this.cmbTerceraPregunta = new Bunifu.UI.WinForms.BunifuDropdown();
            this.cmbSegundaPregunta = new Bunifu.UI.WinForms.BunifuDropdown();
            this.cmbPrimeraPregunta = new Bunifu.UI.WinForms.BunifuDropdown();
            this.pnlSombraBoton = new Bunifu.UI.WinForms.BunifuShadowPanel();
            this.btnComprobar = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.lblTitulo = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuShadowPanel1 = new Bunifu.UI.WinForms.BunifuShadowPanel();
            this.btnVerificarPregunta = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.pnlGradiente.SuspendLayout();
            this.pnlSombraFondo.SuspendLayout();
            this.pnlSombraBoton.SuspendLayout();
            this.bunifuShadowPanel1.SuspendLayout();
            this.SuspendLayout();
            // 
            // pnlGradiente
            // 
            this.pnlGradiente.BackColor = System.Drawing.Color.Transparent;
            this.pnlGradiente.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("pnlGradiente.BackgroundImage")));
            this.pnlGradiente.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.pnlGradiente.BorderRadius = 1;
            this.pnlGradiente.Controls.Add(this.pnlSombraFondo);
            this.pnlGradiente.Dock = System.Windows.Forms.DockStyle.Fill;
            this.pnlGradiente.GradientBottomLeft = System.Drawing.Color.Teal;
            this.pnlGradiente.GradientBottomRight = System.Drawing.Color.Teal;
            this.pnlGradiente.GradientTopLeft = System.Drawing.Color.LightSeaGreen;
            this.pnlGradiente.GradientTopRight = System.Drawing.Color.LightSeaGreen;
            this.pnlGradiente.Location = new System.Drawing.Point(0, 0);
            this.pnlGradiente.Name = "pnlGradiente";
            this.pnlGradiente.Padding = new System.Windows.Forms.Padding(30);
            this.pnlGradiente.Quality = 10;
            this.pnlGradiente.Size = new System.Drawing.Size(730, 820);
            this.pnlGradiente.TabIndex = 1;
            // 
            // pnlSombraFondo
            // 
            this.pnlSombraFondo.BackColor = System.Drawing.Color.Transparent;
            this.pnlSombraFondo.BorderColor = System.Drawing.Color.WhiteSmoke;
            this.pnlSombraFondo.BorderRadius = 25;
            this.pnlSombraFondo.BorderThickness = 1;
            this.pnlSombraFondo.Controls.Add(this.bunifuShadowPanel1);
            this.pnlSombraFondo.Controls.Add(this.txtCuartaPregunta);
            this.pnlSombraFondo.Controls.Add(this.txtTerceraPregunta);
            this.pnlSombraFondo.Controls.Add(this.txtSegundaPregunta);
            this.pnlSombraFondo.Controls.Add(this.txtPrimeraPregunta);
            this.pnlSombraFondo.Controls.Add(this.cmbCuartaPregunta);
            this.pnlSombraFondo.Controls.Add(this.cmbTerceraPregunta);
            this.pnlSombraFondo.Controls.Add(this.cmbSegundaPregunta);
            this.pnlSombraFondo.Controls.Add(this.cmbPrimeraPregunta);
            this.pnlSombraFondo.Controls.Add(this.pnlSombraBoton);
            this.pnlSombraFondo.Controls.Add(this.lblTitulo);
            this.pnlSombraFondo.Dock = System.Windows.Forms.DockStyle.Fill;
            this.pnlSombraFondo.FillStyle = Bunifu.UI.WinForms.BunifuShadowPanel.FillStyles.Solid;
            this.pnlSombraFondo.Font = new System.Drawing.Font("Century Gothic", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.pnlSombraFondo.GradientMode = Bunifu.UI.WinForms.BunifuShadowPanel.GradientModes.Vertical;
            this.pnlSombraFondo.Location = new System.Drawing.Point(30, 30);
            this.pnlSombraFondo.Name = "pnlSombraFondo";
            this.pnlSombraFondo.PanelColor = System.Drawing.Color.WhiteSmoke;
            this.pnlSombraFondo.PanelColor2 = System.Drawing.Color.WhiteSmoke;
            this.pnlSombraFondo.ShadowColor = System.Drawing.Color.FromArgb(((int)(((byte)(190)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.pnlSombraFondo.ShadowDept = 2;
            this.pnlSombraFondo.ShadowDepth = 5;
            this.pnlSombraFondo.ShadowStyle = Bunifu.UI.WinForms.BunifuShadowPanel.ShadowStyles.Surrounded;
            this.pnlSombraFondo.ShadowTopLeftVisible = false;
            this.pnlSombraFondo.Size = new System.Drawing.Size(670, 760);
            this.pnlSombraFondo.Style = Bunifu.UI.WinForms.BunifuShadowPanel.BevelStyles.Flat;
            this.pnlSombraFondo.TabIndex = 0;
            // 
            // txtCuartaPregunta
            // 
            this.txtCuartaPregunta.AcceptsReturn = false;
            this.txtCuartaPregunta.AcceptsTab = false;
            this.txtCuartaPregunta.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.txtCuartaPregunta.AnimationSpeed = 200;
            this.txtCuartaPregunta.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtCuartaPregunta.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtCuartaPregunta.AutoSizeHeight = true;
            this.txtCuartaPregunta.BackColor = System.Drawing.Color.Transparent;
            this.txtCuartaPregunta.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtCuartaPregunta.BackgroundImage")));
            this.txtCuartaPregunta.BorderColorActive = System.Drawing.Color.CadetBlue;
            this.txtCuartaPregunta.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtCuartaPregunta.BorderColorHover = System.Drawing.Color.DarkTurquoise;
            this.txtCuartaPregunta.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtCuartaPregunta.BorderRadius = 5;
            this.txtCuartaPregunta.BorderThickness = 1;
            this.txtCuartaPregunta.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.txtCuartaPregunta.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtCuartaPregunta.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtCuartaPregunta.DefaultFont = new System.Drawing.Font("Century Gothic", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtCuartaPregunta.DefaultText = "";
            this.txtCuartaPregunta.FillColor = System.Drawing.Color.White;
            this.txtCuartaPregunta.HideSelection = true;
            this.txtCuartaPregunta.IconLeft = null;
            this.txtCuartaPregunta.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtCuartaPregunta.IconPadding = 10;
            this.txtCuartaPregunta.IconRight = null;
            this.txtCuartaPregunta.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtCuartaPregunta.Lines = new string[0];
            this.txtCuartaPregunta.Location = new System.Drawing.Point(52, 518);
            this.txtCuartaPregunta.MaxLength = 40;
            this.txtCuartaPregunta.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtCuartaPregunta.Modified = false;
            this.txtCuartaPregunta.Multiline = false;
            this.txtCuartaPregunta.Name = "txtCuartaPregunta";
            stateProperties1.BorderColor = System.Drawing.Color.CadetBlue;
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtCuartaPregunta.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtCuartaPregunta.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.DarkTurquoise;
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtCuartaPregunta.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.Silver;
            stateProperties4.FillColor = System.Drawing.Color.White;
            stateProperties4.ForeColor = System.Drawing.Color.Empty;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtCuartaPregunta.OnIdleState = stateProperties4;
            this.txtCuartaPregunta.Padding = new System.Windows.Forms.Padding(3);
            this.txtCuartaPregunta.PasswordChar = '\0';
            this.txtCuartaPregunta.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtCuartaPregunta.PlaceholderText = "Ingresa la respuesta";
            this.txtCuartaPregunta.ReadOnly = false;
            this.txtCuartaPregunta.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtCuartaPregunta.SelectedText = "";
            this.txtCuartaPregunta.SelectionLength = 0;
            this.txtCuartaPregunta.SelectionStart = 0;
            this.txtCuartaPregunta.ShortcutsEnabled = false;
            this.txtCuartaPregunta.Size = new System.Drawing.Size(564, 42);
            this.txtCuartaPregunta.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtCuartaPregunta.TabIndex = 14;
            this.txtCuartaPregunta.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtCuartaPregunta.TextMarginBottom = 0;
            this.txtCuartaPregunta.TextMarginLeft = 3;
            this.txtCuartaPregunta.TextMarginTop = 1;
            this.txtCuartaPregunta.TextPlaceholder = "Ingresa la respuesta";
            this.txtCuartaPregunta.UseSystemPasswordChar = false;
            this.txtCuartaPregunta.WordWrap = true;
            // 
            // txtTerceraPregunta
            // 
            this.txtTerceraPregunta.AcceptsReturn = false;
            this.txtTerceraPregunta.AcceptsTab = false;
            this.txtTerceraPregunta.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.txtTerceraPregunta.AnimationSpeed = 200;
            this.txtTerceraPregunta.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtTerceraPregunta.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtTerceraPregunta.AutoSizeHeight = true;
            this.txtTerceraPregunta.BackColor = System.Drawing.Color.Transparent;
            this.txtTerceraPregunta.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtTerceraPregunta.BackgroundImage")));
            this.txtTerceraPregunta.BorderColorActive = System.Drawing.Color.CadetBlue;
            this.txtTerceraPregunta.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtTerceraPregunta.BorderColorHover = System.Drawing.Color.DarkTurquoise;
            this.txtTerceraPregunta.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtTerceraPregunta.BorderRadius = 5;
            this.txtTerceraPregunta.BorderThickness = 1;
            this.txtTerceraPregunta.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.txtTerceraPregunta.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtTerceraPregunta.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtTerceraPregunta.DefaultFont = new System.Drawing.Font("Century Gothic", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtTerceraPregunta.DefaultText = "";
            this.txtTerceraPregunta.FillColor = System.Drawing.Color.White;
            this.txtTerceraPregunta.HideSelection = true;
            this.txtTerceraPregunta.IconLeft = null;
            this.txtTerceraPregunta.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtTerceraPregunta.IconPadding = 10;
            this.txtTerceraPregunta.IconRight = null;
            this.txtTerceraPregunta.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtTerceraPregunta.Lines = new string[0];
            this.txtTerceraPregunta.Location = new System.Drawing.Point(52, 412);
            this.txtTerceraPregunta.MaxLength = 40;
            this.txtTerceraPregunta.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtTerceraPregunta.Modified = false;
            this.txtTerceraPregunta.Multiline = false;
            this.txtTerceraPregunta.Name = "txtTerceraPregunta";
            stateProperties5.BorderColor = System.Drawing.Color.CadetBlue;
            stateProperties5.FillColor = System.Drawing.Color.Empty;
            stateProperties5.ForeColor = System.Drawing.Color.Empty;
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtTerceraPregunta.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties6.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties6.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtTerceraPregunta.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = System.Drawing.Color.DarkTurquoise;
            stateProperties7.FillColor = System.Drawing.Color.Empty;
            stateProperties7.ForeColor = System.Drawing.Color.Empty;
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtTerceraPregunta.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.Silver;
            stateProperties8.FillColor = System.Drawing.Color.White;
            stateProperties8.ForeColor = System.Drawing.Color.Empty;
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtTerceraPregunta.OnIdleState = stateProperties8;
            this.txtTerceraPregunta.Padding = new System.Windows.Forms.Padding(3);
            this.txtTerceraPregunta.PasswordChar = '\0';
            this.txtTerceraPregunta.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtTerceraPregunta.PlaceholderText = "Ingresa la respuesta";
            this.txtTerceraPregunta.ReadOnly = false;
            this.txtTerceraPregunta.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtTerceraPregunta.SelectedText = "";
            this.txtTerceraPregunta.SelectionLength = 0;
            this.txtTerceraPregunta.SelectionStart = 0;
            this.txtTerceraPregunta.ShortcutsEnabled = false;
            this.txtTerceraPregunta.Size = new System.Drawing.Size(564, 42);
            this.txtTerceraPregunta.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtTerceraPregunta.TabIndex = 13;
            this.txtTerceraPregunta.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtTerceraPregunta.TextMarginBottom = 0;
            this.txtTerceraPregunta.TextMarginLeft = 3;
            this.txtTerceraPregunta.TextMarginTop = 1;
            this.txtTerceraPregunta.TextPlaceholder = "Ingresa la respuesta";
            this.txtTerceraPregunta.UseSystemPasswordChar = false;
            this.txtTerceraPregunta.WordWrap = true;
            // 
            // txtSegundaPregunta
            // 
            this.txtSegundaPregunta.AcceptsReturn = false;
            this.txtSegundaPregunta.AcceptsTab = false;
            this.txtSegundaPregunta.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.txtSegundaPregunta.AnimationSpeed = 200;
            this.txtSegundaPregunta.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtSegundaPregunta.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtSegundaPregunta.AutoSizeHeight = true;
            this.txtSegundaPregunta.BackColor = System.Drawing.Color.Transparent;
            this.txtSegundaPregunta.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtSegundaPregunta.BackgroundImage")));
            this.txtSegundaPregunta.BorderColorActive = System.Drawing.Color.CadetBlue;
            this.txtSegundaPregunta.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtSegundaPregunta.BorderColorHover = System.Drawing.Color.DarkTurquoise;
            this.txtSegundaPregunta.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtSegundaPregunta.BorderRadius = 5;
            this.txtSegundaPregunta.BorderThickness = 1;
            this.txtSegundaPregunta.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.txtSegundaPregunta.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtSegundaPregunta.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtSegundaPregunta.DefaultFont = new System.Drawing.Font("Century Gothic", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtSegundaPregunta.DefaultText = "";
            this.txtSegundaPregunta.FillColor = System.Drawing.Color.White;
            this.txtSegundaPregunta.HideSelection = true;
            this.txtSegundaPregunta.IconLeft = null;
            this.txtSegundaPregunta.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtSegundaPregunta.IconPadding = 10;
            this.txtSegundaPregunta.IconRight = null;
            this.txtSegundaPregunta.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtSegundaPregunta.Lines = new string[0];
            this.txtSegundaPregunta.Location = new System.Drawing.Point(52, 303);
            this.txtSegundaPregunta.MaxLength = 40;
            this.txtSegundaPregunta.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtSegundaPregunta.Modified = false;
            this.txtSegundaPregunta.Multiline = false;
            this.txtSegundaPregunta.Name = "txtSegundaPregunta";
            stateProperties9.BorderColor = System.Drawing.Color.CadetBlue;
            stateProperties9.FillColor = System.Drawing.Color.Empty;
            stateProperties9.ForeColor = System.Drawing.Color.Empty;
            stateProperties9.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtSegundaPregunta.OnActiveState = stateProperties9;
            stateProperties10.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties10.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties10.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties10.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtSegundaPregunta.OnDisabledState = stateProperties10;
            stateProperties11.BorderColor = System.Drawing.Color.DarkTurquoise;
            stateProperties11.FillColor = System.Drawing.Color.Empty;
            stateProperties11.ForeColor = System.Drawing.Color.Empty;
            stateProperties11.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtSegundaPregunta.OnHoverState = stateProperties11;
            stateProperties12.BorderColor = System.Drawing.Color.Silver;
            stateProperties12.FillColor = System.Drawing.Color.White;
            stateProperties12.ForeColor = System.Drawing.Color.Empty;
            stateProperties12.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtSegundaPregunta.OnIdleState = stateProperties12;
            this.txtSegundaPregunta.Padding = new System.Windows.Forms.Padding(3);
            this.txtSegundaPregunta.PasswordChar = '\0';
            this.txtSegundaPregunta.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtSegundaPregunta.PlaceholderText = "Ingresa la respuesta";
            this.txtSegundaPregunta.ReadOnly = false;
            this.txtSegundaPregunta.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtSegundaPregunta.SelectedText = "";
            this.txtSegundaPregunta.SelectionLength = 0;
            this.txtSegundaPregunta.SelectionStart = 0;
            this.txtSegundaPregunta.ShortcutsEnabled = false;
            this.txtSegundaPregunta.Size = new System.Drawing.Size(564, 42);
            this.txtSegundaPregunta.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtSegundaPregunta.TabIndex = 12;
            this.txtSegundaPregunta.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtSegundaPregunta.TextMarginBottom = 0;
            this.txtSegundaPregunta.TextMarginLeft = 3;
            this.txtSegundaPregunta.TextMarginTop = 1;
            this.txtSegundaPregunta.TextPlaceholder = "Ingresa la respuesta";
            this.txtSegundaPregunta.UseSystemPasswordChar = false;
            this.txtSegundaPregunta.WordWrap = true;
            // 
            // txtPrimeraPregunta
            // 
            this.txtPrimeraPregunta.AcceptsReturn = false;
            this.txtPrimeraPregunta.AcceptsTab = false;
            this.txtPrimeraPregunta.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.txtPrimeraPregunta.AnimationSpeed = 200;
            this.txtPrimeraPregunta.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtPrimeraPregunta.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtPrimeraPregunta.AutoSizeHeight = true;
            this.txtPrimeraPregunta.BackColor = System.Drawing.Color.Transparent;
            this.txtPrimeraPregunta.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtPrimeraPregunta.BackgroundImage")));
            this.txtPrimeraPregunta.BorderColorActive = System.Drawing.Color.CadetBlue;
            this.txtPrimeraPregunta.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtPrimeraPregunta.BorderColorHover = System.Drawing.Color.DarkTurquoise;
            this.txtPrimeraPregunta.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtPrimeraPregunta.BorderRadius = 5;
            this.txtPrimeraPregunta.BorderThickness = 1;
            this.txtPrimeraPregunta.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.txtPrimeraPregunta.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtPrimeraPregunta.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtPrimeraPregunta.DefaultFont = new System.Drawing.Font("Century Gothic", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtPrimeraPregunta.DefaultText = "";
            this.txtPrimeraPregunta.FillColor = System.Drawing.Color.White;
            this.txtPrimeraPregunta.HideSelection = true;
            this.txtPrimeraPregunta.IconLeft = null;
            this.txtPrimeraPregunta.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtPrimeraPregunta.IconPadding = 10;
            this.txtPrimeraPregunta.IconRight = null;
            this.txtPrimeraPregunta.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtPrimeraPregunta.Lines = new string[0];
            this.txtPrimeraPregunta.Location = new System.Drawing.Point(52, 190);
            this.txtPrimeraPregunta.MaxLength = 40;
            this.txtPrimeraPregunta.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtPrimeraPregunta.Modified = false;
            this.txtPrimeraPregunta.Multiline = false;
            this.txtPrimeraPregunta.Name = "txtPrimeraPregunta";
            stateProperties13.BorderColor = System.Drawing.Color.CadetBlue;
            stateProperties13.FillColor = System.Drawing.Color.Empty;
            stateProperties13.ForeColor = System.Drawing.Color.Empty;
            stateProperties13.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtPrimeraPregunta.OnActiveState = stateProperties13;
            stateProperties14.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties14.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties14.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties14.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtPrimeraPregunta.OnDisabledState = stateProperties14;
            stateProperties15.BorderColor = System.Drawing.Color.DarkTurquoise;
            stateProperties15.FillColor = System.Drawing.Color.Empty;
            stateProperties15.ForeColor = System.Drawing.Color.Empty;
            stateProperties15.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtPrimeraPregunta.OnHoverState = stateProperties15;
            stateProperties16.BorderColor = System.Drawing.Color.Silver;
            stateProperties16.FillColor = System.Drawing.Color.White;
            stateProperties16.ForeColor = System.Drawing.Color.Empty;
            stateProperties16.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtPrimeraPregunta.OnIdleState = stateProperties16;
            this.txtPrimeraPregunta.Padding = new System.Windows.Forms.Padding(3);
            this.txtPrimeraPregunta.PasswordChar = '\0';
            this.txtPrimeraPregunta.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtPrimeraPregunta.PlaceholderText = "Ingresa la respuesta";
            this.txtPrimeraPregunta.ReadOnly = false;
            this.txtPrimeraPregunta.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtPrimeraPregunta.SelectedText = "";
            this.txtPrimeraPregunta.SelectionLength = 0;
            this.txtPrimeraPregunta.SelectionStart = 0;
            this.txtPrimeraPregunta.ShortcutsEnabled = false;
            this.txtPrimeraPregunta.Size = new System.Drawing.Size(564, 42);
            this.txtPrimeraPregunta.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtPrimeraPregunta.TabIndex = 11;
            this.txtPrimeraPregunta.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtPrimeraPregunta.TextMarginBottom = 0;
            this.txtPrimeraPregunta.TextMarginLeft = 3;
            this.txtPrimeraPregunta.TextMarginTop = 1;
            this.txtPrimeraPregunta.TextPlaceholder = "Ingresa la respuesta";
            this.txtPrimeraPregunta.UseSystemPasswordChar = false;
            this.txtPrimeraPregunta.WordWrap = true;
            // 
            // cmbCuartaPregunta
            // 
            this.cmbCuartaPregunta.BackColor = System.Drawing.Color.Transparent;
            this.cmbCuartaPregunta.BackgroundColor = System.Drawing.Color.White;
            this.cmbCuartaPregunta.BorderColor = System.Drawing.Color.Silver;
            this.cmbCuartaPregunta.BorderRadius = 5;
            this.cmbCuartaPregunta.Color = System.Drawing.Color.Silver;
            this.cmbCuartaPregunta.Direction = Bunifu.UI.WinForms.BunifuDropdown.Directions.Down;
            this.cmbCuartaPregunta.DisabledBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            this.cmbCuartaPregunta.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.cmbCuartaPregunta.DisabledColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            this.cmbCuartaPregunta.DisabledForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            this.cmbCuartaPregunta.DisabledIndicatorColor = System.Drawing.Color.DarkGray;
            this.cmbCuartaPregunta.DrawMode = System.Windows.Forms.DrawMode.OwnerDrawFixed;
            this.cmbCuartaPregunta.DropdownBorderThickness = Bunifu.UI.WinForms.BunifuDropdown.BorderThickness.Thin;
            this.cmbCuartaPregunta.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cmbCuartaPregunta.DropDownTextAlign = Bunifu.UI.WinForms.BunifuDropdown.TextAlign.Left;
            this.cmbCuartaPregunta.FillDropDown = true;
            this.cmbCuartaPregunta.FillIndicator = false;
            this.cmbCuartaPregunta.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.cmbCuartaPregunta.Font = new System.Drawing.Font("Century Gothic", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.cmbCuartaPregunta.ForeColor = System.Drawing.Color.Black;
            this.cmbCuartaPregunta.FormattingEnabled = true;
            this.cmbCuartaPregunta.Icon = null;
            this.cmbCuartaPregunta.IndicatorAlignment = Bunifu.UI.WinForms.BunifuDropdown.Indicator.Right;
            this.cmbCuartaPregunta.IndicatorColor = System.Drawing.Color.Teal;
            this.cmbCuartaPregunta.IndicatorLocation = Bunifu.UI.WinForms.BunifuDropdown.Indicator.Right;
            this.cmbCuartaPregunta.IndicatorThickness = 2;
            this.cmbCuartaPregunta.IsDropdownOpened = false;
            this.cmbCuartaPregunta.ItemBackColor = System.Drawing.Color.White;
            this.cmbCuartaPregunta.ItemBorderColor = System.Drawing.Color.White;
            this.cmbCuartaPregunta.ItemForeColor = System.Drawing.Color.Black;
            this.cmbCuartaPregunta.ItemHeight = 26;
            this.cmbCuartaPregunta.ItemHighLightColor = System.Drawing.Color.DarkTurquoise;
            this.cmbCuartaPregunta.ItemHighLightForeColor = System.Drawing.Color.White;
            this.cmbCuartaPregunta.ItemTopMargin = 3;
            this.cmbCuartaPregunta.Location = new System.Drawing.Point(52, 480);
            this.cmbCuartaPregunta.Name = "cmbCuartaPregunta";
            this.cmbCuartaPregunta.Size = new System.Drawing.Size(379, 32);
            this.cmbCuartaPregunta.TabIndex = 10;
            this.cmbCuartaPregunta.Text = null;
            this.cmbCuartaPregunta.TextAlignment = Bunifu.UI.WinForms.BunifuDropdown.TextAlign.Left;
            this.cmbCuartaPregunta.TextLeftMargin = 5;
            // 
            // cmbTerceraPregunta
            // 
            this.cmbTerceraPregunta.BackColor = System.Drawing.Color.Transparent;
            this.cmbTerceraPregunta.BackgroundColor = System.Drawing.Color.White;
            this.cmbTerceraPregunta.BorderColor = System.Drawing.Color.Silver;
            this.cmbTerceraPregunta.BorderRadius = 5;
            this.cmbTerceraPregunta.Color = System.Drawing.Color.Silver;
            this.cmbTerceraPregunta.Direction = Bunifu.UI.WinForms.BunifuDropdown.Directions.Down;
            this.cmbTerceraPregunta.DisabledBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            this.cmbTerceraPregunta.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.cmbTerceraPregunta.DisabledColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            this.cmbTerceraPregunta.DisabledForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            this.cmbTerceraPregunta.DisabledIndicatorColor = System.Drawing.Color.DarkGray;
            this.cmbTerceraPregunta.DrawMode = System.Windows.Forms.DrawMode.OwnerDrawFixed;
            this.cmbTerceraPregunta.DropdownBorderThickness = Bunifu.UI.WinForms.BunifuDropdown.BorderThickness.Thin;
            this.cmbTerceraPregunta.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cmbTerceraPregunta.DropDownTextAlign = Bunifu.UI.WinForms.BunifuDropdown.TextAlign.Left;
            this.cmbTerceraPregunta.FillDropDown = true;
            this.cmbTerceraPregunta.FillIndicator = false;
            this.cmbTerceraPregunta.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.cmbTerceraPregunta.Font = new System.Drawing.Font("Century Gothic", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.cmbTerceraPregunta.ForeColor = System.Drawing.Color.Black;
            this.cmbTerceraPregunta.FormattingEnabled = true;
            this.cmbTerceraPregunta.Icon = null;
            this.cmbTerceraPregunta.IndicatorAlignment = Bunifu.UI.WinForms.BunifuDropdown.Indicator.Right;
            this.cmbTerceraPregunta.IndicatorColor = System.Drawing.Color.Teal;
            this.cmbTerceraPregunta.IndicatorLocation = Bunifu.UI.WinForms.BunifuDropdown.Indicator.Right;
            this.cmbTerceraPregunta.IndicatorThickness = 2;
            this.cmbTerceraPregunta.IsDropdownOpened = false;
            this.cmbTerceraPregunta.ItemBackColor = System.Drawing.Color.White;
            this.cmbTerceraPregunta.ItemBorderColor = System.Drawing.Color.White;
            this.cmbTerceraPregunta.ItemForeColor = System.Drawing.Color.Black;
            this.cmbTerceraPregunta.ItemHeight = 26;
            this.cmbTerceraPregunta.ItemHighLightColor = System.Drawing.Color.DarkTurquoise;
            this.cmbTerceraPregunta.ItemHighLightForeColor = System.Drawing.Color.White;
            this.cmbTerceraPregunta.ItemTopMargin = 3;
            this.cmbTerceraPregunta.Location = new System.Drawing.Point(52, 374);
            this.cmbTerceraPregunta.Name = "cmbTerceraPregunta";
            this.cmbTerceraPregunta.Size = new System.Drawing.Size(379, 32);
            this.cmbTerceraPregunta.TabIndex = 9;
            this.cmbTerceraPregunta.Text = null;
            this.cmbTerceraPregunta.TextAlignment = Bunifu.UI.WinForms.BunifuDropdown.TextAlign.Left;
            this.cmbTerceraPregunta.TextLeftMargin = 5;
            // 
            // cmbSegundaPregunta
            // 
            this.cmbSegundaPregunta.BackColor = System.Drawing.Color.Transparent;
            this.cmbSegundaPregunta.BackgroundColor = System.Drawing.Color.White;
            this.cmbSegundaPregunta.BorderColor = System.Drawing.Color.Silver;
            this.cmbSegundaPregunta.BorderRadius = 5;
            this.cmbSegundaPregunta.Color = System.Drawing.Color.Silver;
            this.cmbSegundaPregunta.Direction = Bunifu.UI.WinForms.BunifuDropdown.Directions.Down;
            this.cmbSegundaPregunta.DisabledBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            this.cmbSegundaPregunta.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.cmbSegundaPregunta.DisabledColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            this.cmbSegundaPregunta.DisabledForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            this.cmbSegundaPregunta.DisabledIndicatorColor = System.Drawing.Color.DarkGray;
            this.cmbSegundaPregunta.DrawMode = System.Windows.Forms.DrawMode.OwnerDrawFixed;
            this.cmbSegundaPregunta.DropdownBorderThickness = Bunifu.UI.WinForms.BunifuDropdown.BorderThickness.Thin;
            this.cmbSegundaPregunta.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cmbSegundaPregunta.DropDownTextAlign = Bunifu.UI.WinForms.BunifuDropdown.TextAlign.Left;
            this.cmbSegundaPregunta.FillDropDown = true;
            this.cmbSegundaPregunta.FillIndicator = false;
            this.cmbSegundaPregunta.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.cmbSegundaPregunta.Font = new System.Drawing.Font("Century Gothic", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.cmbSegundaPregunta.ForeColor = System.Drawing.Color.Black;
            this.cmbSegundaPregunta.FormattingEnabled = true;
            this.cmbSegundaPregunta.Icon = null;
            this.cmbSegundaPregunta.IndicatorAlignment = Bunifu.UI.WinForms.BunifuDropdown.Indicator.Right;
            this.cmbSegundaPregunta.IndicatorColor = System.Drawing.Color.Teal;
            this.cmbSegundaPregunta.IndicatorLocation = Bunifu.UI.WinForms.BunifuDropdown.Indicator.Right;
            this.cmbSegundaPregunta.IndicatorThickness = 2;
            this.cmbSegundaPregunta.IsDropdownOpened = false;
            this.cmbSegundaPregunta.ItemBackColor = System.Drawing.Color.White;
            this.cmbSegundaPregunta.ItemBorderColor = System.Drawing.Color.White;
            this.cmbSegundaPregunta.ItemForeColor = System.Drawing.Color.Black;
            this.cmbSegundaPregunta.ItemHeight = 26;
            this.cmbSegundaPregunta.ItemHighLightColor = System.Drawing.Color.DarkTurquoise;
            this.cmbSegundaPregunta.ItemHighLightForeColor = System.Drawing.Color.White;
            this.cmbSegundaPregunta.ItemTopMargin = 3;
            this.cmbSegundaPregunta.Location = new System.Drawing.Point(52, 265);
            this.cmbSegundaPregunta.Name = "cmbSegundaPregunta";
            this.cmbSegundaPregunta.Size = new System.Drawing.Size(379, 32);
            this.cmbSegundaPregunta.TabIndex = 8;
            this.cmbSegundaPregunta.Text = null;
            this.cmbSegundaPregunta.TextAlignment = Bunifu.UI.WinForms.BunifuDropdown.TextAlign.Left;
            this.cmbSegundaPregunta.TextLeftMargin = 5;
            // 
            // cmbPrimeraPregunta
            // 
            this.cmbPrimeraPregunta.BackColor = System.Drawing.Color.Transparent;
            this.cmbPrimeraPregunta.BackgroundColor = System.Drawing.Color.White;
            this.cmbPrimeraPregunta.BorderColor = System.Drawing.Color.Silver;
            this.cmbPrimeraPregunta.BorderRadius = 5;
            this.cmbPrimeraPregunta.Color = System.Drawing.Color.Silver;
            this.cmbPrimeraPregunta.Direction = Bunifu.UI.WinForms.BunifuDropdown.Directions.Down;
            this.cmbPrimeraPregunta.DisabledBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            this.cmbPrimeraPregunta.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.cmbPrimeraPregunta.DisabledColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            this.cmbPrimeraPregunta.DisabledForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            this.cmbPrimeraPregunta.DisabledIndicatorColor = System.Drawing.Color.DarkGray;
            this.cmbPrimeraPregunta.DrawMode = System.Windows.Forms.DrawMode.OwnerDrawFixed;
            this.cmbPrimeraPregunta.DropdownBorderThickness = Bunifu.UI.WinForms.BunifuDropdown.BorderThickness.Thin;
            this.cmbPrimeraPregunta.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cmbPrimeraPregunta.DropDownTextAlign = Bunifu.UI.WinForms.BunifuDropdown.TextAlign.Left;
            this.cmbPrimeraPregunta.FillDropDown = true;
            this.cmbPrimeraPregunta.FillIndicator = false;
            this.cmbPrimeraPregunta.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.cmbPrimeraPregunta.Font = new System.Drawing.Font("Century Gothic", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.cmbPrimeraPregunta.ForeColor = System.Drawing.Color.Black;
            this.cmbPrimeraPregunta.FormattingEnabled = true;
            this.cmbPrimeraPregunta.Icon = null;
            this.cmbPrimeraPregunta.IndicatorAlignment = Bunifu.UI.WinForms.BunifuDropdown.Indicator.Right;
            this.cmbPrimeraPregunta.IndicatorColor = System.Drawing.Color.Teal;
            this.cmbPrimeraPregunta.IndicatorLocation = Bunifu.UI.WinForms.BunifuDropdown.Indicator.Right;
            this.cmbPrimeraPregunta.IndicatorThickness = 2;
            this.cmbPrimeraPregunta.IsDropdownOpened = false;
            this.cmbPrimeraPregunta.ItemBackColor = System.Drawing.Color.White;
            this.cmbPrimeraPregunta.ItemBorderColor = System.Drawing.Color.White;
            this.cmbPrimeraPregunta.ItemForeColor = System.Drawing.Color.Black;
            this.cmbPrimeraPregunta.ItemHeight = 26;
            this.cmbPrimeraPregunta.ItemHighLightColor = System.Drawing.Color.DarkTurquoise;
            this.cmbPrimeraPregunta.ItemHighLightForeColor = System.Drawing.Color.White;
            this.cmbPrimeraPregunta.ItemTopMargin = 3;
            this.cmbPrimeraPregunta.Location = new System.Drawing.Point(52, 152);
            this.cmbPrimeraPregunta.Name = "cmbPrimeraPregunta";
            this.cmbPrimeraPregunta.Size = new System.Drawing.Size(379, 32);
            this.cmbPrimeraPregunta.TabIndex = 7;
            this.cmbPrimeraPregunta.Text = null;
            this.cmbPrimeraPregunta.TextAlignment = Bunifu.UI.WinForms.BunifuDropdown.TextAlign.Left;
            this.cmbPrimeraPregunta.TextLeftMargin = 5;
            // 
            // pnlSombraBoton
            // 
            this.pnlSombraBoton.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right)));
            this.pnlSombraBoton.BackColor = System.Drawing.Color.Transparent;
            this.pnlSombraBoton.BorderColor = System.Drawing.Color.Transparent;
            this.pnlSombraBoton.BorderRadius = 10;
            this.pnlSombraBoton.BorderThickness = 1;
            this.pnlSombraBoton.Controls.Add(this.btnComprobar);
            this.pnlSombraBoton.FillStyle = Bunifu.UI.WinForms.BunifuShadowPanel.FillStyles.Solid;
            this.pnlSombraBoton.GradientMode = Bunifu.UI.WinForms.BunifuShadowPanel.GradientModes.Vertical;
            this.pnlSombraBoton.Location = new System.Drawing.Point(456, 648);
            this.pnlSombraBoton.Name = "pnlSombraBoton";
            this.pnlSombraBoton.Padding = new System.Windows.Forms.Padding(1, 1, 3, 3);
            this.pnlSombraBoton.PanelColor = System.Drawing.Color.Transparent;
            this.pnlSombraBoton.PanelColor2 = System.Drawing.Color.Transparent;
            this.pnlSombraBoton.ShadowColor = System.Drawing.Color.FromArgb(((int)(((byte)(90)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.pnlSombraBoton.ShadowDept = 2;
            this.pnlSombraBoton.ShadowDepth = 5;
            this.pnlSombraBoton.ShadowStyle = Bunifu.UI.WinForms.BunifuShadowPanel.ShadowStyles.Surrounded;
            this.pnlSombraBoton.ShadowTopLeftVisible = false;
            this.pnlSombraBoton.Size = new System.Drawing.Size(163, 65);
            this.pnlSombraBoton.Style = Bunifu.UI.WinForms.BunifuShadowPanel.BevelStyles.Flat;
            this.pnlSombraBoton.TabIndex = 6;
            // 
            // btnComprobar
            // 
            this.btnComprobar.AllowAnimations = true;
            this.btnComprobar.AllowMouseEffects = true;
            this.btnComprobar.AllowToggling = false;
            this.btnComprobar.AnimationSpeed = 200;
            this.btnComprobar.AutoGenerateColors = false;
            this.btnComprobar.AutoRoundBorders = false;
            this.btnComprobar.AutoSizeLeftIcon = true;
            this.btnComprobar.AutoSizeRightIcon = true;
            this.btnComprobar.BackColor = System.Drawing.Color.Transparent;
            this.btnComprobar.BackColor1 = System.Drawing.Color.LightSeaGreen;
            this.btnComprobar.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnComprobar.BackgroundImage")));
            this.btnComprobar.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnComprobar.ButtonText = "Registrar";
            this.btnComprobar.ButtonTextMarginLeft = 0;
            this.btnComprobar.ColorContrastOnClick = 45;
            this.btnComprobar.ColorContrastOnHover = 45;
            this.btnComprobar.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.btnComprobar.CustomizableEdges = borderEdges2;
            this.btnComprobar.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnComprobar.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnComprobar.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnComprobar.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnComprobar.Dock = System.Windows.Forms.DockStyle.Fill;
            this.btnComprobar.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.btnComprobar.Font = new System.Drawing.Font("Century Gothic", 14.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnComprobar.ForeColor = System.Drawing.Color.White;
            this.btnComprobar.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnComprobar.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.btnComprobar.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnComprobar.IconMarginLeft = 11;
            this.btnComprobar.IconPadding = 10;
            this.btnComprobar.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnComprobar.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.btnComprobar.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnComprobar.IconSize = 25;
            this.btnComprobar.IdleBorderColor = System.Drawing.Color.Transparent;
            this.btnComprobar.IdleBorderRadius = 15;
            this.btnComprobar.IdleBorderThickness = 1;
            this.btnComprobar.IdleFillColor = System.Drawing.Color.LightSeaGreen;
            this.btnComprobar.IdleIconLeftImage = null;
            this.btnComprobar.IdleIconRightImage = null;
            this.btnComprobar.IndicateFocus = false;
            this.btnComprobar.Location = new System.Drawing.Point(1, 1);
            this.btnComprobar.Name = "btnComprobar";
            this.btnComprobar.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnComprobar.OnDisabledState.BorderRadius = 15;
            this.btnComprobar.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnComprobar.OnDisabledState.BorderThickness = 1;
            this.btnComprobar.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnComprobar.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnComprobar.OnDisabledState.IconLeftImage = null;
            this.btnComprobar.OnDisabledState.IconRightImage = null;
            this.btnComprobar.onHoverState.BorderColor = System.Drawing.Color.Transparent;
            this.btnComprobar.onHoverState.BorderRadius = 15;
            this.btnComprobar.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnComprobar.onHoverState.BorderThickness = 1;
            this.btnComprobar.onHoverState.FillColor = System.Drawing.Color.MediumTurquoise;
            this.btnComprobar.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnComprobar.onHoverState.IconLeftImage = null;
            this.btnComprobar.onHoverState.IconRightImage = null;
            this.btnComprobar.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.btnComprobar.OnIdleState.BorderRadius = 15;
            this.btnComprobar.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnComprobar.OnIdleState.BorderThickness = 1;
            this.btnComprobar.OnIdleState.FillColor = System.Drawing.Color.LightSeaGreen;
            this.btnComprobar.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnComprobar.OnIdleState.IconLeftImage = null;
            this.btnComprobar.OnIdleState.IconRightImage = null;
            this.btnComprobar.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(3)))), ((int)(((byte)(166)))), ((int)(((byte)(158)))));
            this.btnComprobar.OnPressedState.BorderRadius = 15;
            this.btnComprobar.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnComprobar.OnPressedState.BorderThickness = 1;
            this.btnComprobar.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(3)))), ((int)(((byte)(166)))), ((int)(((byte)(158)))));
            this.btnComprobar.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnComprobar.OnPressedState.IconLeftImage = null;
            this.btnComprobar.OnPressedState.IconRightImage = null;
            this.btnComprobar.Size = new System.Drawing.Size(159, 61);
            this.btnComprobar.TabIndex = 5;
            this.btnComprobar.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnComprobar.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnComprobar.TextMarginLeft = 0;
            this.btnComprobar.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnComprobar.UseDefaultRadiusAndThickness = true;
            // 
            // lblTitulo
            // 
            this.lblTitulo.AllowParentOverrides = false;
            this.lblTitulo.AutoEllipsis = false;
            this.lblTitulo.Cursor = System.Windows.Forms.Cursors.Default;
            this.lblTitulo.CursorType = System.Windows.Forms.Cursors.Default;
            this.lblTitulo.Font = new System.Drawing.Font("Century Gothic", 20.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblTitulo.Location = new System.Drawing.Point(52, 61);
            this.lblTitulo.Name = "lblTitulo";
            this.lblTitulo.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.lblTitulo.Size = new System.Drawing.Size(385, 39);
            this.lblTitulo.TabIndex = 0;
            this.lblTitulo.Text = "Preguntas de Seguridad";
            this.lblTitulo.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.lblTitulo.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuShadowPanel1
            // 
            this.bunifuShadowPanel1.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right)));
            this.bunifuShadowPanel1.BackColor = System.Drawing.Color.Transparent;
            this.bunifuShadowPanel1.BorderColor = System.Drawing.Color.Transparent;
            this.bunifuShadowPanel1.BorderRadius = 10;
            this.bunifuShadowPanel1.BorderThickness = 1;
            this.bunifuShadowPanel1.Controls.Add(this.btnVerificarPregunta);
            this.bunifuShadowPanel1.FillStyle = Bunifu.UI.WinForms.BunifuShadowPanel.FillStyles.Solid;
            this.bunifuShadowPanel1.GradientMode = Bunifu.UI.WinForms.BunifuShadowPanel.GradientModes.Vertical;
            this.bunifuShadowPanel1.Location = new System.Drawing.Point(292, 648);
            this.bunifuShadowPanel1.Name = "bunifuShadowPanel1";
            this.bunifuShadowPanel1.Padding = new System.Windows.Forms.Padding(1, 1, 3, 3);
            this.bunifuShadowPanel1.PanelColor = System.Drawing.Color.Transparent;
            this.bunifuShadowPanel1.PanelColor2 = System.Drawing.Color.Transparent;
            this.bunifuShadowPanel1.ShadowColor = System.Drawing.Color.FromArgb(((int)(((byte)(90)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.bunifuShadowPanel1.ShadowDept = 2;
            this.bunifuShadowPanel1.ShadowDepth = 5;
            this.bunifuShadowPanel1.ShadowStyle = Bunifu.UI.WinForms.BunifuShadowPanel.ShadowStyles.Surrounded;
            this.bunifuShadowPanel1.ShadowTopLeftVisible = false;
            this.bunifuShadowPanel1.Size = new System.Drawing.Size(149, 65);
            this.bunifuShadowPanel1.Style = Bunifu.UI.WinForms.BunifuShadowPanel.BevelStyles.Flat;
            this.bunifuShadowPanel1.TabIndex = 7;
            // 
            // btnVerificarPregunta
            // 
            this.btnVerificarPregunta.AllowAnimations = true;
            this.btnVerificarPregunta.AllowMouseEffects = true;
            this.btnVerificarPregunta.AllowToggling = false;
            this.btnVerificarPregunta.AnimationSpeed = 200;
            this.btnVerificarPregunta.AutoGenerateColors = false;
            this.btnVerificarPregunta.AutoRoundBorders = false;
            this.btnVerificarPregunta.AutoSizeLeftIcon = true;
            this.btnVerificarPregunta.AutoSizeRightIcon = true;
            this.btnVerificarPregunta.BackColor = System.Drawing.Color.Transparent;
            this.btnVerificarPregunta.BackColor1 = System.Drawing.Color.LightSeaGreen;
            this.btnVerificarPregunta.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnVerificarPregunta.BackgroundImage")));
            this.btnVerificarPregunta.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnVerificarPregunta.ButtonText = "Verificar";
            this.btnVerificarPregunta.ButtonTextMarginLeft = 0;
            this.btnVerificarPregunta.ColorContrastOnClick = 45;
            this.btnVerificarPregunta.ColorContrastOnHover = 45;
            this.btnVerificarPregunta.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.btnVerificarPregunta.CustomizableEdges = borderEdges1;
            this.btnVerificarPregunta.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnVerificarPregunta.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnVerificarPregunta.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnVerificarPregunta.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnVerificarPregunta.Dock = System.Windows.Forms.DockStyle.Fill;
            this.btnVerificarPregunta.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.btnVerificarPregunta.Font = new System.Drawing.Font("Century Gothic", 14.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnVerificarPregunta.ForeColor = System.Drawing.Color.White;
            this.btnVerificarPregunta.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnVerificarPregunta.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.btnVerificarPregunta.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnVerificarPregunta.IconMarginLeft = 11;
            this.btnVerificarPregunta.IconPadding = 10;
            this.btnVerificarPregunta.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnVerificarPregunta.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.btnVerificarPregunta.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnVerificarPregunta.IconSize = 25;
            this.btnVerificarPregunta.IdleBorderColor = System.Drawing.Color.Transparent;
            this.btnVerificarPregunta.IdleBorderRadius = 15;
            this.btnVerificarPregunta.IdleBorderThickness = 1;
            this.btnVerificarPregunta.IdleFillColor = System.Drawing.Color.LightSeaGreen;
            this.btnVerificarPregunta.IdleIconLeftImage = null;
            this.btnVerificarPregunta.IdleIconRightImage = null;
            this.btnVerificarPregunta.IndicateFocus = false;
            this.btnVerificarPregunta.Location = new System.Drawing.Point(1, 1);
            this.btnVerificarPregunta.Name = "btnVerificarPregunta";
            this.btnVerificarPregunta.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnVerificarPregunta.OnDisabledState.BorderRadius = 15;
            this.btnVerificarPregunta.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnVerificarPregunta.OnDisabledState.BorderThickness = 1;
            this.btnVerificarPregunta.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnVerificarPregunta.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnVerificarPregunta.OnDisabledState.IconLeftImage = null;
            this.btnVerificarPregunta.OnDisabledState.IconRightImage = null;
            this.btnVerificarPregunta.onHoverState.BorderColor = System.Drawing.Color.Transparent;
            this.btnVerificarPregunta.onHoverState.BorderRadius = 15;
            this.btnVerificarPregunta.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnVerificarPregunta.onHoverState.BorderThickness = 1;
            this.btnVerificarPregunta.onHoverState.FillColor = System.Drawing.Color.MediumTurquoise;
            this.btnVerificarPregunta.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnVerificarPregunta.onHoverState.IconLeftImage = null;
            this.btnVerificarPregunta.onHoverState.IconRightImage = null;
            this.btnVerificarPregunta.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.btnVerificarPregunta.OnIdleState.BorderRadius = 15;
            this.btnVerificarPregunta.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnVerificarPregunta.OnIdleState.BorderThickness = 1;
            this.btnVerificarPregunta.OnIdleState.FillColor = System.Drawing.Color.LightSeaGreen;
            this.btnVerificarPregunta.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnVerificarPregunta.OnIdleState.IconLeftImage = null;
            this.btnVerificarPregunta.OnIdleState.IconRightImage = null;
            this.btnVerificarPregunta.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(3)))), ((int)(((byte)(166)))), ((int)(((byte)(158)))));
            this.btnVerificarPregunta.OnPressedState.BorderRadius = 15;
            this.btnVerificarPregunta.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnVerificarPregunta.OnPressedState.BorderThickness = 1;
            this.btnVerificarPregunta.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(3)))), ((int)(((byte)(166)))), ((int)(((byte)(158)))));
            this.btnVerificarPregunta.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnVerificarPregunta.OnPressedState.IconLeftImage = null;
            this.btnVerificarPregunta.OnPressedState.IconRightImage = null;
            this.btnVerificarPregunta.Size = new System.Drawing.Size(145, 61);
            this.btnVerificarPregunta.TabIndex = 5;
            this.btnVerificarPregunta.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnVerificarPregunta.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnVerificarPregunta.TextMarginLeft = 0;
            this.btnVerificarPregunta.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnVerificarPregunta.UseDefaultRadiusAndThickness = true;
            // 
            // PreguntasdeSeguridadForm
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(730, 820);
            this.Controls.Add(this.pnlGradiente);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.FixedToolWindow;
            this.MaximumSize = new System.Drawing.Size(746, 859);
            this.MinimumSize = new System.Drawing.Size(746, 859);
            this.Name = "PreguntasdeSeguridadForm";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "Preguntas de Seguridad";
            this.pnlGradiente.ResumeLayout(false);
            this.pnlSombraFondo.ResumeLayout(false);
            this.pnlSombraFondo.PerformLayout();
            this.pnlSombraBoton.ResumeLayout(false);
            this.bunifuShadowPanel1.ResumeLayout(false);
            this.ResumeLayout(false);

        }

        #endregion

        public Bunifu.UI.WinForms.BunifuGradientPanel pnlGradiente;
        public Bunifu.UI.WinForms.BunifuShadowPanel pnlSombraFondo;
        public Bunifu.UI.WinForms.BunifuTextBox txtCuartaPregunta;
        public Bunifu.UI.WinForms.BunifuTextBox txtTerceraPregunta;
        public Bunifu.UI.WinForms.BunifuTextBox txtSegundaPregunta;
        public Bunifu.UI.WinForms.BunifuTextBox txtPrimeraPregunta;
        public Bunifu.UI.WinForms.BunifuDropdown cmbCuartaPregunta;
        public Bunifu.UI.WinForms.BunifuDropdown cmbTerceraPregunta;
        public Bunifu.UI.WinForms.BunifuDropdown cmbSegundaPregunta;
        public Bunifu.UI.WinForms.BunifuDropdown cmbPrimeraPregunta;
        public Bunifu.UI.WinForms.BunifuShadowPanel pnlSombraBoton;
        public Bunifu.UI.WinForms.BunifuButton.BunifuButton2 btnComprobar;
        public Bunifu.UI.WinForms.BunifuLabel lblTitulo;
        public Bunifu.UI.WinForms.BunifuShadowPanel bunifuShadowPanel1;
        public Bunifu.UI.WinForms.BunifuButton.BunifuButton2 btnVerificarPregunta;
    }
}