namespace Empresa_laboral_ADNE___Proyecto_PTC.Vista
{
    partial class PreguntasdeSeguridadForm
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(PreguntasdeSeguridadForm));
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties13 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties14 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties15 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties16 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties17 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties18 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties19 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties20 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties21 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties22 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties23 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties24 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            this.pnlGradiente = new Bunifu.UI.WinForms.BunifuGradientPanel();
            this.menuStrip1 = new System.Windows.Forms.MenuStrip();
            this.txtDUIProfesional = new System.Windows.Forms.ToolStripTextBox();
            this.pnlSombraFondo = new Bunifu.UI.WinForms.BunifuShadowPanel();
            this.lblIngreseCredenciales = new Bunifu.UI.WinForms.BunifuLabel();
            this.lblIndicacion = new Bunifu.UI.WinForms.BunifuLabel();
            this.pnlLineaDivisora = new Bunifu.UI.WinForms.BunifuPanel();
            this.txtDocumento = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtUsuario = new Bunifu.UI.WinForms.BunifuTextBox();
            this.pnlSombraBtn = new Bunifu.UI.WinForms.BunifuShadowPanel();
            this.btnVerificarPregunta = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.txtCuartaPregunta = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtTerceraPregunta = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtSegundaPregunta = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtPrimeraPregunta = new Bunifu.UI.WinForms.BunifuTextBox();
            this.cmbCuartaPregunta = new Bunifu.UI.WinForms.BunifuDropdown();
            this.cmbTerceraPregunta = new Bunifu.UI.WinForms.BunifuDropdown();
            this.cmbSegundaPregunta = new Bunifu.UI.WinForms.BunifuDropdown();
            this.cmbPrimeraPregunta = new Bunifu.UI.WinForms.BunifuDropdown();
            this.pnlSombraBoton = new Bunifu.UI.WinForms.BunifuShadowPanel();
            this.btnRegistrar = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.lblTitulo = new Bunifu.UI.WinForms.BunifuLabel();
            this.NotificacionPreguntas = new Bunifu.UI.WinForms.BunifuSnackbar(this.components);
            this.pnlGradiente.SuspendLayout();
            this.menuStrip1.SuspendLayout();
            this.pnlSombraFondo.SuspendLayout();
            this.pnlSombraBtn.SuspendLayout();
            this.pnlSombraBoton.SuspendLayout();
            this.SuspendLayout();
            // 
            // pnlGradiente
            // 
            this.pnlGradiente.BackColor = System.Drawing.Color.Transparent;
            this.pnlGradiente.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("pnlGradiente.BackgroundImage")));
            this.pnlGradiente.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.pnlGradiente.BorderRadius = 1;
            this.pnlGradiente.Controls.Add(this.menuStrip1);
            this.pnlGradiente.Controls.Add(this.pnlSombraFondo);
            this.pnlGradiente.Dock = System.Windows.Forms.DockStyle.Fill;
            this.pnlGradiente.GradientBottomLeft = System.Drawing.Color.Teal;
            this.pnlGradiente.GradientBottomRight = System.Drawing.Color.Teal;
            this.pnlGradiente.GradientTopLeft = System.Drawing.Color.LightSeaGreen;
            this.pnlGradiente.GradientTopRight = System.Drawing.Color.LightSeaGreen;
            this.pnlGradiente.Location = new System.Drawing.Point(0, 0);
            this.pnlGradiente.Name = "pnlGradiente";
            this.pnlGradiente.Padding = new System.Windows.Forms.Padding(30);
            this.pnlGradiente.Quality = 10;
            this.pnlGradiente.Size = new System.Drawing.Size(715, 874);
            this.pnlGradiente.TabIndex = 1;
            // 
            // menuStrip1
            // 
            this.menuStrip1.Items.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.txtDUIProfesional});
            this.menuStrip1.Location = new System.Drawing.Point(30, 30);
            this.menuStrip1.Name = "menuStrip1";
            this.menuStrip1.Padding = new System.Windows.Forms.Padding(7, 2, 0, 2);
            this.menuStrip1.Size = new System.Drawing.Size(655, 27);
            this.menuStrip1.TabIndex = 15;
            this.menuStrip1.Text = "menuStrip1";
            this.menuStrip1.Visible = false;
            // 
            // txtDUIProfesional
            // 
            this.txtDUIProfesional.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.txtDUIProfesional.Name = "txtDUIProfesional";
            this.txtDUIProfesional.Size = new System.Drawing.Size(116, 23);
            // 
            // pnlSombraFondo
            // 
            this.pnlSombraFondo.BackColor = System.Drawing.Color.Transparent;
            this.pnlSombraFondo.BorderColor = System.Drawing.Color.WhiteSmoke;
            this.pnlSombraFondo.BorderRadius = 25;
            this.pnlSombraFondo.BorderThickness = 1;
            this.pnlSombraFondo.Controls.Add(this.lblIngreseCredenciales);
            this.pnlSombraFondo.Controls.Add(this.lblIndicacion);
            this.pnlSombraFondo.Controls.Add(this.pnlLineaDivisora);
            this.pnlSombraFondo.Controls.Add(this.txtDocumento);
            this.pnlSombraFondo.Controls.Add(this.txtUsuario);
            this.pnlSombraFondo.Controls.Add(this.pnlSombraBtn);
            this.pnlSombraFondo.Controls.Add(this.txtCuartaPregunta);
            this.pnlSombraFondo.Controls.Add(this.txtTerceraPregunta);
            this.pnlSombraFondo.Controls.Add(this.txtSegundaPregunta);
            this.pnlSombraFondo.Controls.Add(this.txtPrimeraPregunta);
            this.pnlSombraFondo.Controls.Add(this.cmbCuartaPregunta);
            this.pnlSombraFondo.Controls.Add(this.cmbTerceraPregunta);
            this.pnlSombraFondo.Controls.Add(this.cmbSegundaPregunta);
            this.pnlSombraFondo.Controls.Add(this.cmbPrimeraPregunta);
            this.pnlSombraFondo.Controls.Add(this.pnlSombraBoton);
            this.pnlSombraFondo.Controls.Add(this.lblTitulo);
            this.pnlSombraFondo.Dock = System.Windows.Forms.DockStyle.Fill;
            this.pnlSombraFondo.FillStyle = Bunifu.UI.WinForms.BunifuShadowPanel.FillStyles.Solid;
            this.pnlSombraFondo.Font = new System.Drawing.Font("Century Gothic", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.pnlSombraFondo.GradientMode = Bunifu.UI.WinForms.BunifuShadowPanel.GradientModes.Vertical;
            this.pnlSombraFondo.Location = new System.Drawing.Point(30, 30);
            this.pnlSombraFondo.Name = "pnlSombraFondo";
            this.pnlSombraFondo.PanelColor = System.Drawing.Color.WhiteSmoke;
            this.pnlSombraFondo.PanelColor2 = System.Drawing.Color.WhiteSmoke;
            this.pnlSombraFondo.ShadowColor = System.Drawing.Color.FromArgb(((int)(((byte)(190)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.pnlSombraFondo.ShadowDept = 2;
            this.pnlSombraFondo.ShadowDepth = 5;
            this.pnlSombraFondo.ShadowStyle = Bunifu.UI.WinForms.BunifuShadowPanel.ShadowStyles.Surrounded;
            this.pnlSombraFondo.ShadowTopLeftVisible = false;
            this.pnlSombraFondo.Size = new System.Drawing.Size(655, 814);
            this.pnlSombraFondo.Style = Bunifu.UI.WinForms.BunifuShadowPanel.BevelStyles.Flat;
            this.pnlSombraFondo.TabIndex = 0;
            // 
            // lblIngreseCredenciales
            // 
            this.lblIngreseCredenciales.AllowParentOverrides = false;
            this.lblIngreseCredenciales.AutoEllipsis = false;
            this.lblIngreseCredenciales.CursorType = null;
            this.lblIngreseCredenciales.Font = new System.Drawing.Font("Century Gothic", 14.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblIngreseCredenciales.Location = new System.Drawing.Point(51, 126);
            this.lblIngreseCredenciales.Name = "lblIngreseCredenciales";
            this.lblIngreseCredenciales.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.lblIngreseCredenciales.Size = new System.Drawing.Size(320, 23);
            this.lblIngreseCredenciales.TabIndex = 19;
            this.lblIngreseCredenciales.Text = "Ingrese las siguientes credenciales";
            this.lblIngreseCredenciales.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.lblIngreseCredenciales.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // lblIndicacion
            // 
            this.lblIndicacion.AllowParentOverrides = false;
            this.lblIndicacion.AutoEllipsis = false;
            this.lblIndicacion.Cursor = System.Windows.Forms.Cursors.Default;
            this.lblIndicacion.CursorType = System.Windows.Forms.Cursors.Default;
            this.lblIndicacion.Font = new System.Drawing.Font("Century Gothic", 14.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblIndicacion.Location = new System.Drawing.Point(51, 241);
            this.lblIndicacion.Name = "lblIndicacion";
            this.lblIndicacion.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.lblIndicacion.Size = new System.Drawing.Size(341, 23);
            this.lblIndicacion.TabIndex = 18;
            this.lblIndicacion.Text = "Seleccione las preguntas y responda";
            this.lblIndicacion.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.lblIndicacion.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // pnlLineaDivisora
            // 
            this.pnlLineaDivisora.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.pnlLineaDivisora.BackgroundColor = System.Drawing.Color.LightSeaGreen;
            this.pnlLineaDivisora.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("pnlLineaDivisora.BackgroundImage")));
            this.pnlLineaDivisora.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.pnlLineaDivisora.BorderColor = System.Drawing.Color.Transparent;
            this.pnlLineaDivisora.BorderRadius = 3;
            this.pnlLineaDivisora.BorderThickness = 1;
            this.pnlLineaDivisora.Location = new System.Drawing.Point(60, 224);
            this.pnlLineaDivisora.Name = "pnlLineaDivisora";
            this.pnlLineaDivisora.ShowBorders = true;
            this.pnlLineaDivisora.Size = new System.Drawing.Size(549, 4);
            this.pnlLineaDivisora.TabIndex = 17;
            // 
            // txtDocumento
            // 
            this.txtDocumento.AcceptsReturn = false;
            this.txtDocumento.AcceptsTab = false;
            this.txtDocumento.AnimationSpeed = 200;
            this.txtDocumento.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtDocumento.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtDocumento.AutoSizeHeight = true;
            this.txtDocumento.BackColor = System.Drawing.Color.Transparent;
            this.txtDocumento.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtDocumento.BackgroundImage")));
            this.txtDocumento.BorderColorActive = System.Drawing.Color.CadetBlue;
            this.txtDocumento.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtDocumento.BorderColorHover = System.Drawing.Color.DarkTurquoise;
            this.txtDocumento.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtDocumento.BorderRadius = 15;
            this.txtDocumento.BorderThickness = 1;
            this.txtDocumento.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.txtDocumento.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtDocumento.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtDocumento.DefaultFont = new System.Drawing.Font("Century Gothic", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtDocumento.DefaultText = "";
            this.txtDocumento.FillColor = System.Drawing.Color.White;
            this.txtDocumento.HideSelection = true;
            this.txtDocumento.IconLeft = null;
            this.txtDocumento.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtDocumento.IconPadding = 10;
            this.txtDocumento.IconRight = null;
            this.txtDocumento.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtDocumento.Lines = new string[0];
            this.txtDocumento.Location = new System.Drawing.Point(337, 165);
            this.txtDocumento.MaxLength = 11;
            this.txtDocumento.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtDocumento.Modified = false;
            this.txtDocumento.Multiline = false;
            this.txtDocumento.Name = "txtDocumento";
            stateProperties1.BorderColor = System.Drawing.Color.CadetBlue;
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtDocumento.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtDocumento.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.DarkTurquoise;
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtDocumento.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.Silver;
            stateProperties4.FillColor = System.Drawing.Color.White;
            stateProperties4.ForeColor = System.Drawing.Color.Empty;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtDocumento.OnIdleState = stateProperties4;
            this.txtDocumento.Padding = new System.Windows.Forms.Padding(3);
            this.txtDocumento.PasswordChar = '\0';
            this.txtDocumento.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtDocumento.PlaceholderText = "Documento";
            this.txtDocumento.ReadOnly = false;
            this.txtDocumento.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtDocumento.SelectedText = "";
            this.txtDocumento.SelectionLength = 0;
            this.txtDocumento.SelectionStart = 0;
            this.txtDocumento.ShortcutsEnabled = false;
            this.txtDocumento.Size = new System.Drawing.Size(271, 42);
            this.txtDocumento.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtDocumento.TabIndex = 16;
            this.txtDocumento.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtDocumento.TextMarginBottom = 0;
            this.txtDocumento.TextMarginLeft = 3;
            this.txtDocumento.TextMarginTop = 1;
            this.txtDocumento.TextPlaceholder = "Documento";
            this.txtDocumento.UseSystemPasswordChar = false;
            this.txtDocumento.WordWrap = true;
            // 
            // txtUsuario
            // 
            this.txtUsuario.AcceptsReturn = false;
            this.txtUsuario.AcceptsTab = false;
            this.txtUsuario.AnimationSpeed = 200;
            this.txtUsuario.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtUsuario.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtUsuario.AutoSizeHeight = true;
            this.txtUsuario.BackColor = System.Drawing.Color.Transparent;
            this.txtUsuario.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtUsuario.BackgroundImage")));
            this.txtUsuario.BorderColorActive = System.Drawing.Color.CadetBlue;
            this.txtUsuario.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtUsuario.BorderColorHover = System.Drawing.Color.DarkTurquoise;
            this.txtUsuario.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtUsuario.BorderRadius = 15;
            this.txtUsuario.BorderThickness = 1;
            this.txtUsuario.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.txtUsuario.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtUsuario.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtUsuario.DefaultFont = new System.Drawing.Font("Century Gothic", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtUsuario.DefaultText = "";
            this.txtUsuario.FillColor = System.Drawing.Color.White;
            this.txtUsuario.HideSelection = true;
            this.txtUsuario.IconLeft = null;
            this.txtUsuario.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtUsuario.IconPadding = 10;
            this.txtUsuario.IconRight = null;
            this.txtUsuario.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtUsuario.Lines = new string[0];
            this.txtUsuario.Location = new System.Drawing.Point(60, 165);
            this.txtUsuario.MaxLength = 30;
            this.txtUsuario.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtUsuario.Modified = false;
            this.txtUsuario.Multiline = false;
            this.txtUsuario.Name = "txtUsuario";
            stateProperties5.BorderColor = System.Drawing.Color.CadetBlue;
            stateProperties5.FillColor = System.Drawing.Color.Empty;
            stateProperties5.ForeColor = System.Drawing.Color.Empty;
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtUsuario.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties6.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties6.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtUsuario.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = System.Drawing.Color.DarkTurquoise;
            stateProperties7.FillColor = System.Drawing.Color.Empty;
            stateProperties7.ForeColor = System.Drawing.Color.Empty;
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtUsuario.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.Silver;
            stateProperties8.FillColor = System.Drawing.Color.White;
            stateProperties8.ForeColor = System.Drawing.Color.Empty;
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtUsuario.OnIdleState = stateProperties8;
            this.txtUsuario.Padding = new System.Windows.Forms.Padding(3);
            this.txtUsuario.PasswordChar = '\0';
            this.txtUsuario.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtUsuario.PlaceholderText = "Usuario";
            this.txtUsuario.ReadOnly = false;
            this.txtUsuario.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtUsuario.SelectedText = "";
            this.txtUsuario.SelectionLength = 0;
            this.txtUsuario.SelectionStart = 0;
            this.txtUsuario.ShortcutsEnabled = false;
            this.txtUsuario.Size = new System.Drawing.Size(271, 42);
            this.txtUsuario.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtUsuario.TabIndex = 15;
            this.txtUsuario.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtUsuario.TextMarginBottom = 0;
            this.txtUsuario.TextMarginLeft = 3;
            this.txtUsuario.TextMarginTop = 1;
            this.txtUsuario.TextPlaceholder = "Usuario";
            this.txtUsuario.UseSystemPasswordChar = false;
            this.txtUsuario.WordWrap = true;
            // 
            // pnlSombraBtn
            // 
            this.pnlSombraBtn.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right)));
            this.pnlSombraBtn.BackColor = System.Drawing.Color.Transparent;
            this.pnlSombraBtn.BorderColor = System.Drawing.Color.Transparent;
            this.pnlSombraBtn.BorderRadius = 10;
            this.pnlSombraBtn.BorderThickness = 1;
            this.pnlSombraBtn.Controls.Add(this.btnVerificarPregunta);
            this.pnlSombraBtn.FillStyle = Bunifu.UI.WinForms.BunifuShadowPanel.FillStyles.Solid;
            this.pnlSombraBtn.GradientMode = Bunifu.UI.WinForms.BunifuShadowPanel.GradientModes.Vertical;
            this.pnlSombraBtn.Location = new System.Drawing.Point(279, 709);
            this.pnlSombraBtn.Name = "pnlSombraBtn";
            this.pnlSombraBtn.Padding = new System.Windows.Forms.Padding(1, 1, 3, 3);
            this.pnlSombraBtn.PanelColor = System.Drawing.Color.Transparent;
            this.pnlSombraBtn.PanelColor2 = System.Drawing.Color.Transparent;
            this.pnlSombraBtn.ShadowColor = System.Drawing.Color.FromArgb(((int)(((byte)(90)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.pnlSombraBtn.ShadowDept = 2;
            this.pnlSombraBtn.ShadowDepth = 5;
            this.pnlSombraBtn.ShadowStyle = Bunifu.UI.WinForms.BunifuShadowPanel.ShadowStyles.Surrounded;
            this.pnlSombraBtn.ShadowTopLeftVisible = false;
            this.pnlSombraBtn.Size = new System.Drawing.Size(163, 65);
            this.pnlSombraBtn.Style = Bunifu.UI.WinForms.BunifuShadowPanel.BevelStyles.Flat;
            this.pnlSombraBtn.TabIndex = 7;
            // 
            // btnVerificarPregunta
            // 
            this.btnVerificarPregunta.AllowAnimations = true;
            this.btnVerificarPregunta.AllowMouseEffects = true;
            this.btnVerificarPregunta.AllowToggling = false;
            this.btnVerificarPregunta.AnimationSpeed = 200;
            this.btnVerificarPregunta.AutoGenerateColors = false;
            this.btnVerificarPregunta.AutoRoundBorders = false;
            this.btnVerificarPregunta.AutoSizeLeftIcon = true;
            this.btnVerificarPregunta.AutoSizeRightIcon = true;
            this.btnVerificarPregunta.BackColor = System.Drawing.Color.Transparent;
            this.btnVerificarPregunta.BackColor1 = System.Drawing.Color.LightSeaGreen;
            this.btnVerificarPregunta.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnVerificarPregunta.BackgroundImage")));
            this.btnVerificarPregunta.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnVerificarPregunta.ButtonText = "Verificar";
            this.btnVerificarPregunta.ButtonTextMarginLeft = 0;
            this.btnVerificarPregunta.ColorContrastOnClick = 45;
            this.btnVerificarPregunta.ColorContrastOnHover = 45;
            this.btnVerificarPregunta.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.btnVerificarPregunta.CustomizableEdges = borderEdges1;
            this.btnVerificarPregunta.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnVerificarPregunta.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnVerificarPregunta.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnVerificarPregunta.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnVerificarPregunta.Dock = System.Windows.Forms.DockStyle.Fill;
            this.btnVerificarPregunta.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.btnVerificarPregunta.Font = new System.Drawing.Font("Century Gothic", 14.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnVerificarPregunta.ForeColor = System.Drawing.Color.White;
            this.btnVerificarPregunta.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnVerificarPregunta.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.btnVerificarPregunta.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnVerificarPregunta.IconMarginLeft = 11;
            this.btnVerificarPregunta.IconPadding = 10;
            this.btnVerificarPregunta.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnVerificarPregunta.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.btnVerificarPregunta.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnVerificarPregunta.IconSize = 25;
            this.btnVerificarPregunta.IdleBorderColor = System.Drawing.Color.Transparent;
            this.btnVerificarPregunta.IdleBorderRadius = 15;
            this.btnVerificarPregunta.IdleBorderThickness = 1;
            this.btnVerificarPregunta.IdleFillColor = System.Drawing.Color.LightSeaGreen;
            this.btnVerificarPregunta.IdleIconLeftImage = null;
            this.btnVerificarPregunta.IdleIconRightImage = null;
            this.btnVerificarPregunta.IndicateFocus = false;
            this.btnVerificarPregunta.Location = new System.Drawing.Point(1, 1);
            this.btnVerificarPregunta.Name = "btnVerificarPregunta";
            this.btnVerificarPregunta.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnVerificarPregunta.OnDisabledState.BorderRadius = 15;
            this.btnVerificarPregunta.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnVerificarPregunta.OnDisabledState.BorderThickness = 1;
            this.btnVerificarPregunta.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnVerificarPregunta.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnVerificarPregunta.OnDisabledState.IconLeftImage = null;
            this.btnVerificarPregunta.OnDisabledState.IconRightImage = null;
            this.btnVerificarPregunta.onHoverState.BorderColor = System.Drawing.Color.Transparent;
            this.btnVerificarPregunta.onHoverState.BorderRadius = 15;
            this.btnVerificarPregunta.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnVerificarPregunta.onHoverState.BorderThickness = 1;
            this.btnVerificarPregunta.onHoverState.FillColor = System.Drawing.Color.MediumTurquoise;
            this.btnVerificarPregunta.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnVerificarPregunta.onHoverState.IconLeftImage = null;
            this.btnVerificarPregunta.onHoverState.IconRightImage = null;
            this.btnVerificarPregunta.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.btnVerificarPregunta.OnIdleState.BorderRadius = 15;
            this.btnVerificarPregunta.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnVerificarPregunta.OnIdleState.BorderThickness = 1;
            this.btnVerificarPregunta.OnIdleState.FillColor = System.Drawing.Color.LightSeaGreen;
            this.btnVerificarPregunta.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnVerificarPregunta.OnIdleState.IconLeftImage = null;
            this.btnVerificarPregunta.OnIdleState.IconRightImage = null;
            this.btnVerificarPregunta.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(3)))), ((int)(((byte)(166)))), ((int)(((byte)(158)))));
            this.btnVerificarPregunta.OnPressedState.BorderRadius = 15;
            this.btnVerificarPregunta.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnVerificarPregunta.OnPressedState.BorderThickness = 1;
            this.btnVerificarPregunta.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(3)))), ((int)(((byte)(166)))), ((int)(((byte)(158)))));
            this.btnVerificarPregunta.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnVerificarPregunta.OnPressedState.IconLeftImage = null;
            this.btnVerificarPregunta.OnPressedState.IconRightImage = null;
            this.btnVerificarPregunta.Size = new System.Drawing.Size(159, 61);
            this.btnVerificarPregunta.TabIndex = 5;
            this.btnVerificarPregunta.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnVerificarPregunta.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnVerificarPregunta.TextMarginLeft = 0;
            this.btnVerificarPregunta.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnVerificarPregunta.UseDefaultRadiusAndThickness = true;
            // 
            // txtCuartaPregunta
            // 
            this.txtCuartaPregunta.AcceptsReturn = false;
            this.txtCuartaPregunta.AcceptsTab = false;
            this.txtCuartaPregunta.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.txtCuartaPregunta.AnimationSpeed = 200;
            this.txtCuartaPregunta.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtCuartaPregunta.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtCuartaPregunta.AutoSizeHeight = true;
            this.txtCuartaPregunta.BackColor = System.Drawing.Color.Transparent;
            this.txtCuartaPregunta.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtCuartaPregunta.BackgroundImage")));
            this.txtCuartaPregunta.BorderColorActive = System.Drawing.Color.CadetBlue;
            this.txtCuartaPregunta.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtCuartaPregunta.BorderColorHover = System.Drawing.Color.DarkTurquoise;
            this.txtCuartaPregunta.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtCuartaPregunta.BorderRadius = 15;
            this.txtCuartaPregunta.BorderThickness = 1;
            this.txtCuartaPregunta.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.txtCuartaPregunta.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtCuartaPregunta.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtCuartaPregunta.DefaultFont = new System.Drawing.Font("Century Gothic", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtCuartaPregunta.DefaultText = "";
            this.txtCuartaPregunta.FillColor = System.Drawing.Color.White;
            this.txtCuartaPregunta.HideSelection = true;
            this.txtCuartaPregunta.IconLeft = null;
            this.txtCuartaPregunta.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtCuartaPregunta.IconPadding = 10;
            this.txtCuartaPregunta.IconRight = null;
            this.txtCuartaPregunta.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtCuartaPregunta.Lines = new string[0];
            this.txtCuartaPregunta.Location = new System.Drawing.Point(60, 627);
            this.txtCuartaPregunta.MaxLength = 40;
            this.txtCuartaPregunta.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtCuartaPregunta.Modified = false;
            this.txtCuartaPregunta.Multiline = false;
            this.txtCuartaPregunta.Name = "txtCuartaPregunta";
            stateProperties9.BorderColor = System.Drawing.Color.CadetBlue;
            stateProperties9.FillColor = System.Drawing.Color.Empty;
            stateProperties9.ForeColor = System.Drawing.Color.Empty;
            stateProperties9.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtCuartaPregunta.OnActiveState = stateProperties9;
            stateProperties10.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties10.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties10.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties10.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtCuartaPregunta.OnDisabledState = stateProperties10;
            stateProperties11.BorderColor = System.Drawing.Color.DarkTurquoise;
            stateProperties11.FillColor = System.Drawing.Color.Empty;
            stateProperties11.ForeColor = System.Drawing.Color.Empty;
            stateProperties11.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtCuartaPregunta.OnHoverState = stateProperties11;
            stateProperties12.BorderColor = System.Drawing.Color.Silver;
            stateProperties12.FillColor = System.Drawing.Color.White;
            stateProperties12.ForeColor = System.Drawing.Color.Empty;
            stateProperties12.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtCuartaPregunta.OnIdleState = stateProperties12;
            this.txtCuartaPregunta.Padding = new System.Windows.Forms.Padding(3);
            this.txtCuartaPregunta.PasswordChar = '\0';
            this.txtCuartaPregunta.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtCuartaPregunta.PlaceholderText = "Ingresa la respuesta";
            this.txtCuartaPregunta.ReadOnly = false;
            this.txtCuartaPregunta.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtCuartaPregunta.SelectedText = "";
            this.txtCuartaPregunta.SelectionLength = 0;
            this.txtCuartaPregunta.SelectionStart = 0;
            this.txtCuartaPregunta.ShortcutsEnabled = false;
            this.txtCuartaPregunta.Size = new System.Drawing.Size(546, 42);
            this.txtCuartaPregunta.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtCuartaPregunta.TabIndex = 14;
            this.txtCuartaPregunta.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtCuartaPregunta.TextMarginBottom = 0;
            this.txtCuartaPregunta.TextMarginLeft = 3;
            this.txtCuartaPregunta.TextMarginTop = 1;
            this.txtCuartaPregunta.TextPlaceholder = "Ingresa la respuesta";
            this.txtCuartaPregunta.UseSystemPasswordChar = false;
            this.txtCuartaPregunta.WordWrap = true;
            // 
            // txtTerceraPregunta
            // 
            this.txtTerceraPregunta.AcceptsReturn = false;
            this.txtTerceraPregunta.AcceptsTab = false;
            this.txtTerceraPregunta.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.txtTerceraPregunta.AnimationSpeed = 200;
            this.txtTerceraPregunta.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtTerceraPregunta.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtTerceraPregunta.AutoSizeHeight = true;
            this.txtTerceraPregunta.BackColor = System.Drawing.Color.Transparent;
            this.txtTerceraPregunta.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtTerceraPregunta.BackgroundImage")));
            this.txtTerceraPregunta.BorderColorActive = System.Drawing.Color.CadetBlue;
            this.txtTerceraPregunta.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtTerceraPregunta.BorderColorHover = System.Drawing.Color.DarkTurquoise;
            this.txtTerceraPregunta.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtTerceraPregunta.BorderRadius = 15;
            this.txtTerceraPregunta.BorderThickness = 1;
            this.txtTerceraPregunta.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.txtTerceraPregunta.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtTerceraPregunta.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtTerceraPregunta.DefaultFont = new System.Drawing.Font("Century Gothic", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtTerceraPregunta.DefaultText = "";
            this.txtTerceraPregunta.FillColor = System.Drawing.Color.White;
            this.txtTerceraPregunta.HideSelection = true;
            this.txtTerceraPregunta.IconLeft = null;
            this.txtTerceraPregunta.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtTerceraPregunta.IconPadding = 10;
            this.txtTerceraPregunta.IconRight = null;
            this.txtTerceraPregunta.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtTerceraPregunta.Lines = new string[0];
            this.txtTerceraPregunta.Location = new System.Drawing.Point(60, 523);
            this.txtTerceraPregunta.MaxLength = 40;
            this.txtTerceraPregunta.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtTerceraPregunta.Modified = false;
            this.txtTerceraPregunta.Multiline = false;
            this.txtTerceraPregunta.Name = "txtTerceraPregunta";
            stateProperties13.BorderColor = System.Drawing.Color.CadetBlue;
            stateProperties13.FillColor = System.Drawing.Color.Empty;
            stateProperties13.ForeColor = System.Drawing.Color.Empty;
            stateProperties13.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtTerceraPregunta.OnActiveState = stateProperties13;
            stateProperties14.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties14.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties14.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties14.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtTerceraPregunta.OnDisabledState = stateProperties14;
            stateProperties15.BorderColor = System.Drawing.Color.DarkTurquoise;
            stateProperties15.FillColor = System.Drawing.Color.Empty;
            stateProperties15.ForeColor = System.Drawing.Color.Empty;
            stateProperties15.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtTerceraPregunta.OnHoverState = stateProperties15;
            stateProperties16.BorderColor = System.Drawing.Color.Silver;
            stateProperties16.FillColor = System.Drawing.Color.White;
            stateProperties16.ForeColor = System.Drawing.Color.Empty;
            stateProperties16.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtTerceraPregunta.OnIdleState = stateProperties16;
            this.txtTerceraPregunta.Padding = new System.Windows.Forms.Padding(3);
            this.txtTerceraPregunta.PasswordChar = '\0';
            this.txtTerceraPregunta.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtTerceraPregunta.PlaceholderText = "Ingresa la respuesta";
            this.txtTerceraPregunta.ReadOnly = false;
            this.txtTerceraPregunta.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtTerceraPregunta.SelectedText = "";
            this.txtTerceraPregunta.SelectionLength = 0;
            this.txtTerceraPregunta.SelectionStart = 0;
            this.txtTerceraPregunta.ShortcutsEnabled = false;
            this.txtTerceraPregunta.Size = new System.Drawing.Size(546, 42);
            this.txtTerceraPregunta.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtTerceraPregunta.TabIndex = 13;
            this.txtTerceraPregunta.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtTerceraPregunta.TextMarginBottom = 0;
            this.txtTerceraPregunta.TextMarginLeft = 3;
            this.txtTerceraPregunta.TextMarginTop = 1;
            this.txtTerceraPregunta.TextPlaceholder = "Ingresa la respuesta";
            this.txtTerceraPregunta.UseSystemPasswordChar = false;
            this.txtTerceraPregunta.WordWrap = true;
            // 
            // txtSegundaPregunta
            // 
            this.txtSegundaPregunta.AcceptsReturn = false;
            this.txtSegundaPregunta.AcceptsTab = false;
            this.txtSegundaPregunta.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.txtSegundaPregunta.AnimationSpeed = 200;
            this.txtSegundaPregunta.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtSegundaPregunta.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtSegundaPregunta.AutoSizeHeight = true;
            this.txtSegundaPregunta.BackColor = System.Drawing.Color.Transparent;
            this.txtSegundaPregunta.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtSegundaPregunta.BackgroundImage")));
            this.txtSegundaPregunta.BorderColorActive = System.Drawing.Color.CadetBlue;
            this.txtSegundaPregunta.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtSegundaPregunta.BorderColorHover = System.Drawing.Color.DarkTurquoise;
            this.txtSegundaPregunta.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtSegundaPregunta.BorderRadius = 15;
            this.txtSegundaPregunta.BorderThickness = 1;
            this.txtSegundaPregunta.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.txtSegundaPregunta.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtSegundaPregunta.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtSegundaPregunta.DefaultFont = new System.Drawing.Font("Century Gothic", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtSegundaPregunta.DefaultText = "";
            this.txtSegundaPregunta.FillColor = System.Drawing.Color.White;
            this.txtSegundaPregunta.HideSelection = true;
            this.txtSegundaPregunta.IconLeft = null;
            this.txtSegundaPregunta.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtSegundaPregunta.IconPadding = 10;
            this.txtSegundaPregunta.IconRight = null;
            this.txtSegundaPregunta.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtSegundaPregunta.Lines = new string[0];
            this.txtSegundaPregunta.Location = new System.Drawing.Point(60, 420);
            this.txtSegundaPregunta.MaxLength = 40;
            this.txtSegundaPregunta.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtSegundaPregunta.Modified = false;
            this.txtSegundaPregunta.Multiline = false;
            this.txtSegundaPregunta.Name = "txtSegundaPregunta";
            stateProperties17.BorderColor = System.Drawing.Color.CadetBlue;
            stateProperties17.FillColor = System.Drawing.Color.Empty;
            stateProperties17.ForeColor = System.Drawing.Color.Empty;
            stateProperties17.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtSegundaPregunta.OnActiveState = stateProperties17;
            stateProperties18.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties18.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties18.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties18.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtSegundaPregunta.OnDisabledState = stateProperties18;
            stateProperties19.BorderColor = System.Drawing.Color.DarkTurquoise;
            stateProperties19.FillColor = System.Drawing.Color.Empty;
            stateProperties19.ForeColor = System.Drawing.Color.Empty;
            stateProperties19.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtSegundaPregunta.OnHoverState = stateProperties19;
            stateProperties20.BorderColor = System.Drawing.Color.Silver;
            stateProperties20.FillColor = System.Drawing.Color.White;
            stateProperties20.ForeColor = System.Drawing.Color.Empty;
            stateProperties20.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtSegundaPregunta.OnIdleState = stateProperties20;
            this.txtSegundaPregunta.Padding = new System.Windows.Forms.Padding(3);
            this.txtSegundaPregunta.PasswordChar = '\0';
            this.txtSegundaPregunta.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtSegundaPregunta.PlaceholderText = "Ingresa la respuesta";
            this.txtSegundaPregunta.ReadOnly = false;
            this.txtSegundaPregunta.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtSegundaPregunta.SelectedText = "";
            this.txtSegundaPregunta.SelectionLength = 0;
            this.txtSegundaPregunta.SelectionStart = 0;
            this.txtSegundaPregunta.ShortcutsEnabled = false;
            this.txtSegundaPregunta.Size = new System.Drawing.Size(546, 42);
            this.txtSegundaPregunta.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtSegundaPregunta.TabIndex = 12;
            this.txtSegundaPregunta.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtSegundaPregunta.TextMarginBottom = 0;
            this.txtSegundaPregunta.TextMarginLeft = 3;
            this.txtSegundaPregunta.TextMarginTop = 1;
            this.txtSegundaPregunta.TextPlaceholder = "Ingresa la respuesta";
            this.txtSegundaPregunta.UseSystemPasswordChar = false;
            this.txtSegundaPregunta.WordWrap = true;
            // 
            // txtPrimeraPregunta
            // 
            this.txtPrimeraPregunta.AcceptsReturn = false;
            this.txtPrimeraPregunta.AcceptsTab = false;
            this.txtPrimeraPregunta.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.txtPrimeraPregunta.AnimationSpeed = 200;
            this.txtPrimeraPregunta.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtPrimeraPregunta.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtPrimeraPregunta.AutoSizeHeight = true;
            this.txtPrimeraPregunta.BackColor = System.Drawing.Color.Transparent;
            this.txtPrimeraPregunta.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtPrimeraPregunta.BackgroundImage")));
            this.txtPrimeraPregunta.BorderColorActive = System.Drawing.Color.CadetBlue;
            this.txtPrimeraPregunta.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtPrimeraPregunta.BorderColorHover = System.Drawing.Color.DarkTurquoise;
            this.txtPrimeraPregunta.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtPrimeraPregunta.BorderRadius = 15;
            this.txtPrimeraPregunta.BorderThickness = 1;
            this.txtPrimeraPregunta.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.txtPrimeraPregunta.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtPrimeraPregunta.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtPrimeraPregunta.DefaultFont = new System.Drawing.Font("Century Gothic", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtPrimeraPregunta.DefaultText = "";
            this.txtPrimeraPregunta.FillColor = System.Drawing.Color.White;
            this.txtPrimeraPregunta.HideSelection = true;
            this.txtPrimeraPregunta.IconLeft = null;
            this.txtPrimeraPregunta.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtPrimeraPregunta.IconPadding = 10;
            this.txtPrimeraPregunta.IconRight = null;
            this.txtPrimeraPregunta.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtPrimeraPregunta.Lines = new string[0];
            this.txtPrimeraPregunta.Location = new System.Drawing.Point(60, 316);
            this.txtPrimeraPregunta.MaxLength = 40;
            this.txtPrimeraPregunta.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtPrimeraPregunta.Modified = false;
            this.txtPrimeraPregunta.Multiline = false;
            this.txtPrimeraPregunta.Name = "txtPrimeraPregunta";
            stateProperties21.BorderColor = System.Drawing.Color.CadetBlue;
            stateProperties21.FillColor = System.Drawing.Color.Empty;
            stateProperties21.ForeColor = System.Drawing.Color.Empty;
            stateProperties21.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtPrimeraPregunta.OnActiveState = stateProperties21;
            stateProperties22.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties22.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties22.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties22.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtPrimeraPregunta.OnDisabledState = stateProperties22;
            stateProperties23.BorderColor = System.Drawing.Color.DarkTurquoise;
            stateProperties23.FillColor = System.Drawing.Color.Empty;
            stateProperties23.ForeColor = System.Drawing.Color.Empty;
            stateProperties23.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtPrimeraPregunta.OnHoverState = stateProperties23;
            stateProperties24.BorderColor = System.Drawing.Color.Silver;
            stateProperties24.FillColor = System.Drawing.Color.White;
            stateProperties24.ForeColor = System.Drawing.Color.Empty;
            stateProperties24.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtPrimeraPregunta.OnIdleState = stateProperties24;
            this.txtPrimeraPregunta.Padding = new System.Windows.Forms.Padding(3);
            this.txtPrimeraPregunta.PasswordChar = '\0';
            this.txtPrimeraPregunta.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtPrimeraPregunta.PlaceholderText = "Ingresa la respuesta";
            this.txtPrimeraPregunta.ReadOnly = false;
            this.txtPrimeraPregunta.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtPrimeraPregunta.SelectedText = "";
            this.txtPrimeraPregunta.SelectionLength = 0;
            this.txtPrimeraPregunta.SelectionStart = 0;
            this.txtPrimeraPregunta.ShortcutsEnabled = false;
            this.txtPrimeraPregunta.Size = new System.Drawing.Size(546, 42);
            this.txtPrimeraPregunta.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtPrimeraPregunta.TabIndex = 11;
            this.txtPrimeraPregunta.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtPrimeraPregunta.TextMarginBottom = 0;
            this.txtPrimeraPregunta.TextMarginLeft = 3;
            this.txtPrimeraPregunta.TextMarginTop = 1;
            this.txtPrimeraPregunta.TextPlaceholder = "Ingresa la respuesta";
            this.txtPrimeraPregunta.UseSystemPasswordChar = false;
            this.txtPrimeraPregunta.WordWrap = true;
            // 
            // cmbCuartaPregunta
            // 
            this.cmbCuartaPregunta.BackColor = System.Drawing.Color.Transparent;
            this.cmbCuartaPregunta.BackgroundColor = System.Drawing.Color.White;
            this.cmbCuartaPregunta.BorderColor = System.Drawing.Color.Silver;
            this.cmbCuartaPregunta.BorderRadius = 5;
            this.cmbCuartaPregunta.Color = System.Drawing.Color.Silver;
            this.cmbCuartaPregunta.Direction = Bunifu.UI.WinForms.BunifuDropdown.Directions.Down;
            this.cmbCuartaPregunta.DisabledBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            this.cmbCuartaPregunta.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.cmbCuartaPregunta.DisabledColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            this.cmbCuartaPregunta.DisabledForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            this.cmbCuartaPregunta.DisabledIndicatorColor = System.Drawing.Color.DarkGray;
            this.cmbCuartaPregunta.DrawMode = System.Windows.Forms.DrawMode.OwnerDrawFixed;
            this.cmbCuartaPregunta.DropdownBorderThickness = Bunifu.UI.WinForms.BunifuDropdown.BorderThickness.Thin;
            this.cmbCuartaPregunta.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cmbCuartaPregunta.DropDownTextAlign = Bunifu.UI.WinForms.BunifuDropdown.TextAlign.Left;
            this.cmbCuartaPregunta.FillDropDown = true;
            this.cmbCuartaPregunta.FillIndicator = false;
            this.cmbCuartaPregunta.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.cmbCuartaPregunta.Font = new System.Drawing.Font("Century Gothic", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.cmbCuartaPregunta.ForeColor = System.Drawing.Color.Black;
            this.cmbCuartaPregunta.FormattingEnabled = true;
            this.cmbCuartaPregunta.Icon = null;
            this.cmbCuartaPregunta.IndicatorAlignment = Bunifu.UI.WinForms.BunifuDropdown.Indicator.Right;
            this.cmbCuartaPregunta.IndicatorColor = System.Drawing.Color.Teal;
            this.cmbCuartaPregunta.IndicatorLocation = Bunifu.UI.WinForms.BunifuDropdown.Indicator.Right;
            this.cmbCuartaPregunta.IndicatorThickness = 2;
            this.cmbCuartaPregunta.IsDropdownOpened = false;
            this.cmbCuartaPregunta.ItemBackColor = System.Drawing.Color.White;
            this.cmbCuartaPregunta.ItemBorderColor = System.Drawing.Color.White;
            this.cmbCuartaPregunta.ItemForeColor = System.Drawing.Color.Black;
            this.cmbCuartaPregunta.ItemHeight = 26;
            this.cmbCuartaPregunta.ItemHighLightColor = System.Drawing.Color.DarkTurquoise;
            this.cmbCuartaPregunta.ItemHighLightForeColor = System.Drawing.Color.White;
            this.cmbCuartaPregunta.ItemTopMargin = 3;
            this.cmbCuartaPregunta.Location = new System.Drawing.Point(60, 589);
            this.cmbCuartaPregunta.Name = "cmbCuartaPregunta";
            this.cmbCuartaPregunta.Size = new System.Drawing.Size(545, 32);
            this.cmbCuartaPregunta.TabIndex = 10;
            this.cmbCuartaPregunta.Text = null;
            this.cmbCuartaPregunta.TextAlignment = Bunifu.UI.WinForms.BunifuDropdown.TextAlign.Left;
            this.cmbCuartaPregunta.TextLeftMargin = 5;
            // 
            // cmbTerceraPregunta
            // 
            this.cmbTerceraPregunta.BackColor = System.Drawing.Color.Transparent;
            this.cmbTerceraPregunta.BackgroundColor = System.Drawing.Color.White;
            this.cmbTerceraPregunta.BorderColor = System.Drawing.Color.Silver;
            this.cmbTerceraPregunta.BorderRadius = 5;
            this.cmbTerceraPregunta.Color = System.Drawing.Color.Silver;
            this.cmbTerceraPregunta.Direction = Bunifu.UI.WinForms.BunifuDropdown.Directions.Down;
            this.cmbTerceraPregunta.DisabledBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            this.cmbTerceraPregunta.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.cmbTerceraPregunta.DisabledColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            this.cmbTerceraPregunta.DisabledForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            this.cmbTerceraPregunta.DisabledIndicatorColor = System.Drawing.Color.DarkGray;
            this.cmbTerceraPregunta.DrawMode = System.Windows.Forms.DrawMode.OwnerDrawFixed;
            this.cmbTerceraPregunta.DropdownBorderThickness = Bunifu.UI.WinForms.BunifuDropdown.BorderThickness.Thin;
            this.cmbTerceraPregunta.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cmbTerceraPregunta.DropDownTextAlign = Bunifu.UI.WinForms.BunifuDropdown.TextAlign.Left;
            this.cmbTerceraPregunta.FillDropDown = true;
            this.cmbTerceraPregunta.FillIndicator = false;
            this.cmbTerceraPregunta.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.cmbTerceraPregunta.Font = new System.Drawing.Font("Century Gothic", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.cmbTerceraPregunta.ForeColor = System.Drawing.Color.Black;
            this.cmbTerceraPregunta.FormattingEnabled = true;
            this.cmbTerceraPregunta.Icon = null;
            this.cmbTerceraPregunta.IndicatorAlignment = Bunifu.UI.WinForms.BunifuDropdown.Indicator.Right;
            this.cmbTerceraPregunta.IndicatorColor = System.Drawing.Color.Teal;
            this.cmbTerceraPregunta.IndicatorLocation = Bunifu.UI.WinForms.BunifuDropdown.Indicator.Right;
            this.cmbTerceraPregunta.IndicatorThickness = 2;
            this.cmbTerceraPregunta.IsDropdownOpened = false;
            this.cmbTerceraPregunta.ItemBackColor = System.Drawing.Color.White;
            this.cmbTerceraPregunta.ItemBorderColor = System.Drawing.Color.White;
            this.cmbTerceraPregunta.ItemForeColor = System.Drawing.Color.Black;
            this.cmbTerceraPregunta.ItemHeight = 26;
            this.cmbTerceraPregunta.ItemHighLightColor = System.Drawing.Color.DarkTurquoise;
            this.cmbTerceraPregunta.ItemHighLightForeColor = System.Drawing.Color.White;
            this.cmbTerceraPregunta.ItemTopMargin = 3;
            this.cmbTerceraPregunta.Location = new System.Drawing.Point(60, 485);
            this.cmbTerceraPregunta.Name = "cmbTerceraPregunta";
            this.cmbTerceraPregunta.Size = new System.Drawing.Size(545, 32);
            this.cmbTerceraPregunta.TabIndex = 9;
            this.cmbTerceraPregunta.Text = null;
            this.cmbTerceraPregunta.TextAlignment = Bunifu.UI.WinForms.BunifuDropdown.TextAlign.Left;
            this.cmbTerceraPregunta.TextLeftMargin = 5;
            // 
            // cmbSegundaPregunta
            // 
            this.cmbSegundaPregunta.BackColor = System.Drawing.Color.Transparent;
            this.cmbSegundaPregunta.BackgroundColor = System.Drawing.Color.White;
            this.cmbSegundaPregunta.BorderColor = System.Drawing.Color.Silver;
            this.cmbSegundaPregunta.BorderRadius = 5;
            this.cmbSegundaPregunta.Color = System.Drawing.Color.Silver;
            this.cmbSegundaPregunta.Direction = Bunifu.UI.WinForms.BunifuDropdown.Directions.Down;
            this.cmbSegundaPregunta.DisabledBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            this.cmbSegundaPregunta.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.cmbSegundaPregunta.DisabledColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            this.cmbSegundaPregunta.DisabledForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            this.cmbSegundaPregunta.DisabledIndicatorColor = System.Drawing.Color.DarkGray;
            this.cmbSegundaPregunta.DrawMode = System.Windows.Forms.DrawMode.OwnerDrawFixed;
            this.cmbSegundaPregunta.DropdownBorderThickness = Bunifu.UI.WinForms.BunifuDropdown.BorderThickness.Thin;
            this.cmbSegundaPregunta.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cmbSegundaPregunta.DropDownTextAlign = Bunifu.UI.WinForms.BunifuDropdown.TextAlign.Left;
            this.cmbSegundaPregunta.FillDropDown = true;
            this.cmbSegundaPregunta.FillIndicator = false;
            this.cmbSegundaPregunta.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.cmbSegundaPregunta.Font = new System.Drawing.Font("Century Gothic", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.cmbSegundaPregunta.ForeColor = System.Drawing.Color.Black;
            this.cmbSegundaPregunta.FormattingEnabled = true;
            this.cmbSegundaPregunta.Icon = null;
            this.cmbSegundaPregunta.IndicatorAlignment = Bunifu.UI.WinForms.BunifuDropdown.Indicator.Right;
            this.cmbSegundaPregunta.IndicatorColor = System.Drawing.Color.Teal;
            this.cmbSegundaPregunta.IndicatorLocation = Bunifu.UI.WinForms.BunifuDropdown.Indicator.Right;
            this.cmbSegundaPregunta.IndicatorThickness = 2;
            this.cmbSegundaPregunta.IsDropdownOpened = false;
            this.cmbSegundaPregunta.ItemBackColor = System.Drawing.Color.White;
            this.cmbSegundaPregunta.ItemBorderColor = System.Drawing.Color.White;
            this.cmbSegundaPregunta.ItemForeColor = System.Drawing.Color.Black;
            this.cmbSegundaPregunta.ItemHeight = 26;
            this.cmbSegundaPregunta.ItemHighLightColor = System.Drawing.Color.DarkTurquoise;
            this.cmbSegundaPregunta.ItemHighLightForeColor = System.Drawing.Color.White;
            this.cmbSegundaPregunta.ItemTopMargin = 3;
            this.cmbSegundaPregunta.Location = new System.Drawing.Point(60, 382);
            this.cmbSegundaPregunta.Name = "cmbSegundaPregunta";
            this.cmbSegundaPregunta.Size = new System.Drawing.Size(545, 32);
            this.cmbSegundaPregunta.TabIndex = 8;
            this.cmbSegundaPregunta.Text = null;
            this.cmbSegundaPregunta.TextAlignment = Bunifu.UI.WinForms.BunifuDropdown.TextAlign.Left;
            this.cmbSegundaPregunta.TextLeftMargin = 5;
            // 
            // cmbPrimeraPregunta
            // 
            this.cmbPrimeraPregunta.BackColor = System.Drawing.Color.Transparent;
            this.cmbPrimeraPregunta.BackgroundColor = System.Drawing.Color.White;
            this.cmbPrimeraPregunta.BorderColor = System.Drawing.Color.Silver;
            this.cmbPrimeraPregunta.BorderRadius = 5;
            this.cmbPrimeraPregunta.Color = System.Drawing.Color.Silver;
            this.cmbPrimeraPregunta.Direction = Bunifu.UI.WinForms.BunifuDropdown.Directions.Down;
            this.cmbPrimeraPregunta.DisabledBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            this.cmbPrimeraPregunta.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.cmbPrimeraPregunta.DisabledColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            this.cmbPrimeraPregunta.DisabledForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            this.cmbPrimeraPregunta.DisabledIndicatorColor = System.Drawing.Color.DarkGray;
            this.cmbPrimeraPregunta.DrawMode = System.Windows.Forms.DrawMode.OwnerDrawFixed;
            this.cmbPrimeraPregunta.DropdownBorderThickness = Bunifu.UI.WinForms.BunifuDropdown.BorderThickness.Thin;
            this.cmbPrimeraPregunta.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cmbPrimeraPregunta.DropDownTextAlign = Bunifu.UI.WinForms.BunifuDropdown.TextAlign.Left;
            this.cmbPrimeraPregunta.FillDropDown = true;
            this.cmbPrimeraPregunta.FillIndicator = false;
            this.cmbPrimeraPregunta.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.cmbPrimeraPregunta.Font = new System.Drawing.Font("Century Gothic", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.cmbPrimeraPregunta.ForeColor = System.Drawing.Color.Black;
            this.cmbPrimeraPregunta.FormattingEnabled = true;
            this.cmbPrimeraPregunta.Icon = null;
            this.cmbPrimeraPregunta.IndicatorAlignment = Bunifu.UI.WinForms.BunifuDropdown.Indicator.Right;
            this.cmbPrimeraPregunta.IndicatorColor = System.Drawing.Color.Teal;
            this.cmbPrimeraPregunta.IndicatorLocation = Bunifu.UI.WinForms.BunifuDropdown.Indicator.Right;
            this.cmbPrimeraPregunta.IndicatorThickness = 2;
            this.cmbPrimeraPregunta.IsDropdownOpened = false;
            this.cmbPrimeraPregunta.ItemBackColor = System.Drawing.Color.White;
            this.cmbPrimeraPregunta.ItemBorderColor = System.Drawing.Color.White;
            this.cmbPrimeraPregunta.ItemForeColor = System.Drawing.Color.Black;
            this.cmbPrimeraPregunta.ItemHeight = 26;
            this.cmbPrimeraPregunta.ItemHighLightColor = System.Drawing.Color.DarkTurquoise;
            this.cmbPrimeraPregunta.ItemHighLightForeColor = System.Drawing.Color.White;
            this.cmbPrimeraPregunta.ItemTopMargin = 3;
            this.cmbPrimeraPregunta.Location = new System.Drawing.Point(60, 278);
            this.cmbPrimeraPregunta.Name = "cmbPrimeraPregunta";
            this.cmbPrimeraPregunta.Size = new System.Drawing.Size(545, 32);
            this.cmbPrimeraPregunta.TabIndex = 7;
            this.cmbPrimeraPregunta.Text = null;
            this.cmbPrimeraPregunta.TextAlignment = Bunifu.UI.WinForms.BunifuDropdown.TextAlign.Left;
            this.cmbPrimeraPregunta.TextLeftMargin = 5;
            // 
            // pnlSombraBoton
            // 
            this.pnlSombraBoton.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right)));
            this.pnlSombraBoton.BackColor = System.Drawing.Color.Transparent;
            this.pnlSombraBoton.BorderColor = System.Drawing.Color.Transparent;
            this.pnlSombraBoton.BorderRadius = 10;
            this.pnlSombraBoton.BorderThickness = 1;
            this.pnlSombraBoton.Controls.Add(this.btnRegistrar);
            this.pnlSombraBoton.FillStyle = Bunifu.UI.WinForms.BunifuShadowPanel.FillStyles.Solid;
            this.pnlSombraBoton.GradientMode = Bunifu.UI.WinForms.BunifuShadowPanel.GradientModes.Vertical;
            this.pnlSombraBoton.Location = new System.Drawing.Point(448, 708);
            this.pnlSombraBoton.Name = "pnlSombraBoton";
            this.pnlSombraBoton.Padding = new System.Windows.Forms.Padding(1, 1, 3, 3);
            this.pnlSombraBoton.PanelColor = System.Drawing.Color.Transparent;
            this.pnlSombraBoton.PanelColor2 = System.Drawing.Color.Transparent;
            this.pnlSombraBoton.ShadowColor = System.Drawing.Color.FromArgb(((int)(((byte)(90)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.pnlSombraBoton.ShadowDept = 2;
            this.pnlSombraBoton.ShadowDepth = 5;
            this.pnlSombraBoton.ShadowStyle = Bunifu.UI.WinForms.BunifuShadowPanel.ShadowStyles.Surrounded;
            this.pnlSombraBoton.ShadowTopLeftVisible = false;
            this.pnlSombraBoton.Size = new System.Drawing.Size(163, 65);
            this.pnlSombraBoton.Style = Bunifu.UI.WinForms.BunifuShadowPanel.BevelStyles.Flat;
            this.pnlSombraBoton.TabIndex = 6;
            // 
            // btnRegistrar
            // 
            this.btnRegistrar.AllowAnimations = true;
            this.btnRegistrar.AllowMouseEffects = true;
            this.btnRegistrar.AllowToggling = false;
            this.btnRegistrar.AnimationSpeed = 200;
            this.btnRegistrar.AutoGenerateColors = false;
            this.btnRegistrar.AutoRoundBorders = false;
            this.btnRegistrar.AutoSizeLeftIcon = true;
            this.btnRegistrar.AutoSizeRightIcon = true;
            this.btnRegistrar.BackColor = System.Drawing.Color.Transparent;
            this.btnRegistrar.BackColor1 = System.Drawing.Color.LightSeaGreen;
            this.btnRegistrar.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnRegistrar.BackgroundImage")));
            this.btnRegistrar.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnRegistrar.ButtonText = "Registrar";
            this.btnRegistrar.ButtonTextMarginLeft = 0;
            this.btnRegistrar.ColorContrastOnClick = 45;
            this.btnRegistrar.ColorContrastOnHover = 45;
            this.btnRegistrar.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.btnRegistrar.CustomizableEdges = borderEdges2;
            this.btnRegistrar.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnRegistrar.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnRegistrar.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnRegistrar.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnRegistrar.Dock = System.Windows.Forms.DockStyle.Fill;
            this.btnRegistrar.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.btnRegistrar.Font = new System.Drawing.Font("Century Gothic", 14.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnRegistrar.ForeColor = System.Drawing.Color.White;
            this.btnRegistrar.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnRegistrar.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.btnRegistrar.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnRegistrar.IconMarginLeft = 11;
            this.btnRegistrar.IconPadding = 10;
            this.btnRegistrar.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnRegistrar.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.btnRegistrar.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnRegistrar.IconSize = 25;
            this.btnRegistrar.IdleBorderColor = System.Drawing.Color.Transparent;
            this.btnRegistrar.IdleBorderRadius = 15;
            this.btnRegistrar.IdleBorderThickness = 1;
            this.btnRegistrar.IdleFillColor = System.Drawing.Color.LightSeaGreen;
            this.btnRegistrar.IdleIconLeftImage = null;
            this.btnRegistrar.IdleIconRightImage = null;
            this.btnRegistrar.IndicateFocus = false;
            this.btnRegistrar.Location = new System.Drawing.Point(1, 1);
            this.btnRegistrar.Name = "btnRegistrar";
            this.btnRegistrar.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnRegistrar.OnDisabledState.BorderRadius = 15;
            this.btnRegistrar.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnRegistrar.OnDisabledState.BorderThickness = 1;
            this.btnRegistrar.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnRegistrar.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnRegistrar.OnDisabledState.IconLeftImage = null;
            this.btnRegistrar.OnDisabledState.IconRightImage = null;
            this.btnRegistrar.onHoverState.BorderColor = System.Drawing.Color.Transparent;
            this.btnRegistrar.onHoverState.BorderRadius = 15;
            this.btnRegistrar.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnRegistrar.onHoverState.BorderThickness = 1;
            this.btnRegistrar.onHoverState.FillColor = System.Drawing.Color.MediumTurquoise;
            this.btnRegistrar.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnRegistrar.onHoverState.IconLeftImage = null;
            this.btnRegistrar.onHoverState.IconRightImage = null;
            this.btnRegistrar.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.btnRegistrar.OnIdleState.BorderRadius = 15;
            this.btnRegistrar.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnRegistrar.OnIdleState.BorderThickness = 1;
            this.btnRegistrar.OnIdleState.FillColor = System.Drawing.Color.LightSeaGreen;
            this.btnRegistrar.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnRegistrar.OnIdleState.IconLeftImage = null;
            this.btnRegistrar.OnIdleState.IconRightImage = null;
            this.btnRegistrar.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(3)))), ((int)(((byte)(166)))), ((int)(((byte)(158)))));
            this.btnRegistrar.OnPressedState.BorderRadius = 15;
            this.btnRegistrar.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnRegistrar.OnPressedState.BorderThickness = 1;
            this.btnRegistrar.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(3)))), ((int)(((byte)(166)))), ((int)(((byte)(158)))));
            this.btnRegistrar.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnRegistrar.OnPressedState.IconLeftImage = null;
            this.btnRegistrar.OnPressedState.IconRightImage = null;
            this.btnRegistrar.Size = new System.Drawing.Size(159, 61);
            this.btnRegistrar.TabIndex = 5;
            this.btnRegistrar.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnRegistrar.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnRegistrar.TextMarginLeft = 0;
            this.btnRegistrar.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnRegistrar.UseDefaultRadiusAndThickness = true;
            // 
            // lblTitulo
            // 
            this.lblTitulo.AllowParentOverrides = false;
            this.lblTitulo.AutoEllipsis = false;
            this.lblTitulo.Cursor = System.Windows.Forms.Cursors.Default;
            this.lblTitulo.CursorType = System.Windows.Forms.Cursors.Default;
            this.lblTitulo.Font = new System.Drawing.Font("Century Gothic", 18F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblTitulo.ForeColor = System.Drawing.Color.Black;
            this.lblTitulo.Location = new System.Drawing.Point(48, 54);
            this.lblTitulo.Name = "lblTitulo";
            this.lblTitulo.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.lblTitulo.Size = new System.Drawing.Size(278, 28);
            this.lblTitulo.TabIndex = 0;
            this.lblTitulo.Text = "Preguntas de Seguridad";
            this.lblTitulo.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.lblTitulo.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // NotificacionPreguntas
            // 
            this.NotificacionPreguntas.AllowDragging = false;
            this.NotificacionPreguntas.AllowMultipleViews = true;
            this.NotificacionPreguntas.ClickToClose = true;
            this.NotificacionPreguntas.DoubleClickToClose = true;
            this.NotificacionPreguntas.DurationAfterIdle = 3000;
            this.NotificacionPreguntas.ErrorOptions.ActionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.NotificacionPreguntas.ErrorOptions.ActionBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.NotificacionPreguntas.ErrorOptions.ActionBorderRadius = 1;
            this.NotificacionPreguntas.ErrorOptions.ActionFont = new System.Drawing.Font("Segoe UI", 8.25F, System.Drawing.FontStyle.Bold);
            this.NotificacionPreguntas.ErrorOptions.ActionForeColor = System.Drawing.Color.Black;
            this.NotificacionPreguntas.ErrorOptions.BackColor = System.Drawing.Color.White;
            this.NotificacionPreguntas.ErrorOptions.BorderColor = System.Drawing.Color.White;
            this.NotificacionPreguntas.ErrorOptions.CloseIconColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(204)))), ((int)(((byte)(199)))));
            this.NotificacionPreguntas.ErrorOptions.Font = new System.Drawing.Font("Century Gothic", 15.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.NotificacionPreguntas.ErrorOptions.ForeColor = System.Drawing.Color.Black;
            this.NotificacionPreguntas.ErrorOptions.Icon = ((System.Drawing.Image)(resources.GetObject("resource.Icon")));
            this.NotificacionPreguntas.ErrorOptions.IconLeftMargin = 12;
            this.NotificacionPreguntas.FadeCloseIcon = false;
            this.NotificacionPreguntas.Host = Bunifu.UI.WinForms.BunifuSnackbar.Hosts.FormOwner;
            this.NotificacionPreguntas.InformationOptions.ActionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.NotificacionPreguntas.InformationOptions.ActionBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.NotificacionPreguntas.InformationOptions.ActionBorderRadius = 1;
            this.NotificacionPreguntas.InformationOptions.ActionFont = new System.Drawing.Font("Segoe UI", 8.25F, System.Drawing.FontStyle.Bold);
            this.NotificacionPreguntas.InformationOptions.ActionForeColor = System.Drawing.Color.Black;
            this.NotificacionPreguntas.InformationOptions.BackColor = System.Drawing.Color.White;
            this.NotificacionPreguntas.InformationOptions.BorderColor = System.Drawing.Color.White;
            this.NotificacionPreguntas.InformationOptions.CloseIconColor = System.Drawing.Color.FromArgb(((int)(((byte)(145)))), ((int)(((byte)(213)))), ((int)(((byte)(255)))));
            this.NotificacionPreguntas.InformationOptions.Font = new System.Drawing.Font("Segoe UI", 9.75F);
            this.NotificacionPreguntas.InformationOptions.ForeColor = System.Drawing.Color.Black;
            this.NotificacionPreguntas.InformationOptions.Icon = ((System.Drawing.Image)(resources.GetObject("resource.Icon1")));
            this.NotificacionPreguntas.InformationOptions.IconLeftMargin = 12;
            this.NotificacionPreguntas.Margin = 10;
            this.NotificacionPreguntas.MaximumSize = new System.Drawing.Size(0, 0);
            this.NotificacionPreguntas.MaximumViews = 1;
            this.NotificacionPreguntas.MessageRightMargin = 15;
            this.NotificacionPreguntas.MessageTopMargin = 0;
            this.NotificacionPreguntas.MinimumSize = new System.Drawing.Size(0, 0);
            this.NotificacionPreguntas.ShowBorders = false;
            this.NotificacionPreguntas.ShowCloseIcon = false;
            this.NotificacionPreguntas.ShowIcon = true;
            this.NotificacionPreguntas.ShowShadows = true;
            this.NotificacionPreguntas.SuccessOptions.ActionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.NotificacionPreguntas.SuccessOptions.ActionBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.NotificacionPreguntas.SuccessOptions.ActionBorderRadius = 1;
            this.NotificacionPreguntas.SuccessOptions.ActionFont = new System.Drawing.Font("Segoe UI", 8.25F, System.Drawing.FontStyle.Bold);
            this.NotificacionPreguntas.SuccessOptions.ActionForeColor = System.Drawing.Color.Black;
            this.NotificacionPreguntas.SuccessOptions.BackColor = System.Drawing.Color.White;
            this.NotificacionPreguntas.SuccessOptions.BorderColor = System.Drawing.Color.White;
            this.NotificacionPreguntas.SuccessOptions.CloseIconColor = System.Drawing.Color.FromArgb(((int)(((byte)(246)))), ((int)(((byte)(255)))), ((int)(((byte)(237)))));
            this.NotificacionPreguntas.SuccessOptions.Font = new System.Drawing.Font("Century Gothic", 15.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.NotificacionPreguntas.SuccessOptions.ForeColor = System.Drawing.Color.Black;
            this.NotificacionPreguntas.SuccessOptions.Icon = ((System.Drawing.Image)(resources.GetObject("resource.Icon2")));
            this.NotificacionPreguntas.SuccessOptions.IconLeftMargin = 12;
            this.NotificacionPreguntas.ViewsMargin = 7;
            this.NotificacionPreguntas.WarningOptions.ActionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.NotificacionPreguntas.WarningOptions.ActionBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.NotificacionPreguntas.WarningOptions.ActionBorderRadius = 1;
            this.NotificacionPreguntas.WarningOptions.ActionFont = new System.Drawing.Font("Segoe UI", 8.25F, System.Drawing.FontStyle.Bold);
            this.NotificacionPreguntas.WarningOptions.ActionForeColor = System.Drawing.Color.Black;
            this.NotificacionPreguntas.WarningOptions.BackColor = System.Drawing.Color.White;
            this.NotificacionPreguntas.WarningOptions.BorderColor = System.Drawing.Color.White;
            this.NotificacionPreguntas.WarningOptions.CloseIconColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(229)))), ((int)(((byte)(143)))));
            this.NotificacionPreguntas.WarningOptions.Font = new System.Drawing.Font("Century Gothic", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.NotificacionPreguntas.WarningOptions.ForeColor = System.Drawing.Color.Black;
            this.NotificacionPreguntas.WarningOptions.Icon = ((System.Drawing.Image)(resources.GetObject("resource.Icon3")));
            this.NotificacionPreguntas.WarningOptions.IconLeftMargin = 12;
            this.NotificacionPreguntas.ZoomCloseIcon = true;
            // 
            // PreguntasdeSeguridadForm
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(715, 874);
            this.Controls.Add(this.pnlGradiente);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.MaximumSize = new System.Drawing.Size(715, 874);
            this.MinimumSize = new System.Drawing.Size(715, 874);
            this.Name = "PreguntasdeSeguridadForm";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "Preguntas de Seguridad";
            this.pnlGradiente.ResumeLayout(false);
            this.pnlGradiente.PerformLayout();
            this.menuStrip1.ResumeLayout(false);
            this.menuStrip1.PerformLayout();
            this.pnlSombraFondo.ResumeLayout(false);
            this.pnlSombraFondo.PerformLayout();
            this.pnlSombraBtn.ResumeLayout(false);
            this.pnlSombraBoton.ResumeLayout(false);
            this.ResumeLayout(false);

        }

        #endregion

        public Bunifu.UI.WinForms.BunifuGradientPanel pnlGradiente;
        public Bunifu.UI.WinForms.BunifuShadowPanel pnlSombraFondo;
        public Bunifu.UI.WinForms.BunifuTextBox txtCuartaPregunta;
        public Bunifu.UI.WinForms.BunifuTextBox txtTerceraPregunta;
        public Bunifu.UI.WinForms.BunifuTextBox txtSegundaPregunta;
        public Bunifu.UI.WinForms.BunifuTextBox txtPrimeraPregunta;
        public Bunifu.UI.WinForms.BunifuDropdown cmbCuartaPregunta;
        public Bunifu.UI.WinForms.BunifuDropdown cmbTerceraPregunta;
        public Bunifu.UI.WinForms.BunifuDropdown cmbSegundaPregunta;
        public Bunifu.UI.WinForms.BunifuDropdown cmbPrimeraPregunta;
        public Bunifu.UI.WinForms.BunifuShadowPanel pnlSombraBoton;
        public Bunifu.UI.WinForms.BunifuButton.BunifuButton2 btnRegistrar;
        public Bunifu.UI.WinForms.BunifuLabel lblTitulo;
        public Bunifu.UI.WinForms.BunifuShadowPanel pnlSombraBtn;
        public Bunifu.UI.WinForms.BunifuButton.BunifuButton2 btnVerificarPregunta;
        public Bunifu.UI.WinForms.BunifuTextBox txtDocumento;
        public Bunifu.UI.WinForms.BunifuTextBox txtUsuario;
        public Bunifu.UI.WinForms.BunifuPanel pnlLineaDivisora;
        public Bunifu.UI.WinForms.BunifuLabel lblIndicacion;
        public Bunifu.UI.WinForms.BunifuLabel lblIngreseCredenciales;
        private System.Windows.Forms.MenuStrip menuStrip1;
        public System.Windows.Forms.ToolStripTextBox txtDUIProfesional;
        public Bunifu.UI.WinForms.BunifuSnackbar NotificacionPreguntas;
    }
}